// Code generated by ent, DO NOT EDIT.

package kms

import (
	"danny.vn/hotpot/pkg/storage/ent/gcp/kms/bronzegcpkmscryptokey"
	"danny.vn/hotpot/pkg/storage/ent/gcp/kms/bronzegcpkmskeyring"
	"danny.vn/hotpot/pkg/storage/ent/gcp/kms/bronzehistorygcpkmscryptokey"
	"danny.vn/hotpot/pkg/storage/ent/gcp/kms/bronzehistorygcpkmskeyring"
	"danny.vn/hotpot/pkg/storage/ent/gcp/kms/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bronzegcpkmscryptokeyFields := schema.BronzeGCPKMSCryptoKey{}.Fields()
	_ = bronzegcpkmscryptokeyFields
	// bronzegcpkmscryptokeyDescName is the schema descriptor for name field.
	bronzegcpkmscryptokeyDescName := bronzegcpkmscryptokeyFields[1].Descriptor()
	// bronzegcpkmscryptokey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	bronzegcpkmscryptokey.NameValidator = bronzegcpkmscryptokeyDescName.Validators[0].(func(string) error)
	// bronzegcpkmscryptokeyDescImportOnly is the schema descriptor for import_only field.
	bronzegcpkmscryptokeyDescImportOnly := bronzegcpkmscryptokeyFields[7].Descriptor()
	// bronzegcpkmscryptokey.DefaultImportOnly holds the default value on creation for the import_only field.
	bronzegcpkmscryptokey.DefaultImportOnly = bronzegcpkmscryptokeyDescImportOnly.Default.(bool)
	// bronzegcpkmscryptokeyDescProjectID is the schema descriptor for project_id field.
	bronzegcpkmscryptokeyDescProjectID := bronzegcpkmscryptokeyFields[12].Descriptor()
	// bronzegcpkmscryptokey.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	bronzegcpkmscryptokey.ProjectIDValidator = bronzegcpkmscryptokeyDescProjectID.Validators[0].(func(string) error)
	bronzegcpkmskeyringFields := schema.BronzeGCPKMSKeyRing{}.Fields()
	_ = bronzegcpkmskeyringFields
	// bronzegcpkmskeyringDescName is the schema descriptor for name field.
	bronzegcpkmskeyringDescName := bronzegcpkmskeyringFields[1].Descriptor()
	// bronzegcpkmskeyring.NameValidator is a validator for the "name" field. It is called by the builders before save.
	bronzegcpkmskeyring.NameValidator = bronzegcpkmskeyringDescName.Validators[0].(func(string) error)
	// bronzegcpkmskeyringDescProjectID is the schema descriptor for project_id field.
	bronzegcpkmskeyringDescProjectID := bronzegcpkmskeyringFields[3].Descriptor()
	// bronzegcpkmskeyring.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	bronzegcpkmskeyring.ProjectIDValidator = bronzegcpkmskeyringDescProjectID.Validators[0].(func(string) error)
	bronzehistorygcpkmscryptokeyFields := schema.BronzeHistoryGCPKMSCryptoKey{}.Fields()
	_ = bronzehistorygcpkmscryptokeyFields
	// bronzehistorygcpkmscryptokeyDescResourceID is the schema descriptor for resource_id field.
	bronzehistorygcpkmscryptokeyDescResourceID := bronzehistorygcpkmscryptokeyFields[1].Descriptor()
	// bronzehistorygcpkmscryptokey.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	bronzehistorygcpkmscryptokey.ResourceIDValidator = bronzehistorygcpkmscryptokeyDescResourceID.Validators[0].(func(string) error)
	// bronzehistorygcpkmscryptokeyDescName is the schema descriptor for name field.
	bronzehistorygcpkmscryptokeyDescName := bronzehistorygcpkmscryptokeyFields[2].Descriptor()
	// bronzehistorygcpkmscryptokey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	bronzehistorygcpkmscryptokey.NameValidator = bronzehistorygcpkmscryptokeyDescName.Validators[0].(func(string) error)
	// bronzehistorygcpkmscryptokeyDescImportOnly is the schema descriptor for import_only field.
	bronzehistorygcpkmscryptokeyDescImportOnly := bronzehistorygcpkmscryptokeyFields[8].Descriptor()
	// bronzehistorygcpkmscryptokey.DefaultImportOnly holds the default value on creation for the import_only field.
	bronzehistorygcpkmscryptokey.DefaultImportOnly = bronzehistorygcpkmscryptokeyDescImportOnly.Default.(bool)
	// bronzehistorygcpkmscryptokeyDescProjectID is the schema descriptor for project_id field.
	bronzehistorygcpkmscryptokeyDescProjectID := bronzehistorygcpkmscryptokeyFields[13].Descriptor()
	// bronzehistorygcpkmscryptokey.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	bronzehistorygcpkmscryptokey.ProjectIDValidator = bronzehistorygcpkmscryptokeyDescProjectID.Validators[0].(func(string) error)
	bronzehistorygcpkmskeyringFields := schema.BronzeHistoryGCPKMSKeyRing{}.Fields()
	_ = bronzehistorygcpkmskeyringFields
	// bronzehistorygcpkmskeyringDescResourceID is the schema descriptor for resource_id field.
	bronzehistorygcpkmskeyringDescResourceID := bronzehistorygcpkmskeyringFields[1].Descriptor()
	// bronzehistorygcpkmskeyring.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	bronzehistorygcpkmskeyring.ResourceIDValidator = bronzehistorygcpkmskeyringDescResourceID.Validators[0].(func(string) error)
	// bronzehistorygcpkmskeyringDescName is the schema descriptor for name field.
	bronzehistorygcpkmskeyringDescName := bronzehistorygcpkmskeyringFields[2].Descriptor()
	// bronzehistorygcpkmskeyring.NameValidator is a validator for the "name" field. It is called by the builders before save.
	bronzehistorygcpkmskeyring.NameValidator = bronzehistorygcpkmskeyringDescName.Validators[0].(func(string) error)
	// bronzehistorygcpkmskeyringDescProjectID is the schema descriptor for project_id field.
	bronzehistorygcpkmskeyringDescProjectID := bronzehistorygcpkmskeyringFields[4].Descriptor()
	// bronzehistorygcpkmskeyring.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	bronzehistorygcpkmskeyring.ProjectIDValidator = bronzehistorygcpkmskeyringDescProjectID.Validators[0].(func(string) error)
}
