// Code generated by ent, DO NOT EDIT.

package bronzehistorygcpstoragebucketiampolicybinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dannyota/hotpot/pkg/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldLTE(FieldID, id))
}

// HistoryID applies equality check predicate on the "history_id" field. It's identical to HistoryIDEQ.
func HistoryID(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEQ(FieldHistoryID, v))
}

// PolicyHistoryID applies equality check predicate on the "policy_history_id" field. It's identical to PolicyHistoryIDEQ.
func PolicyHistoryID(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEQ(FieldPolicyHistoryID, v))
}

// ValidFrom applies equality check predicate on the "valid_from" field. It's identical to ValidFromEQ.
func ValidFrom(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEQ(FieldValidFrom, v))
}

// ValidTo applies equality check predicate on the "valid_to" field. It's identical to ValidToEQ.
func ValidTo(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEQ(FieldValidTo, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEQ(FieldRole, v))
}

// HistoryIDEQ applies the EQ predicate on the "history_id" field.
func HistoryIDEQ(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEQ(FieldHistoryID, v))
}

// HistoryIDNEQ applies the NEQ predicate on the "history_id" field.
func HistoryIDNEQ(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNEQ(FieldHistoryID, v))
}

// HistoryIDIn applies the In predicate on the "history_id" field.
func HistoryIDIn(vs ...uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldIn(FieldHistoryID, vs...))
}

// HistoryIDNotIn applies the NotIn predicate on the "history_id" field.
func HistoryIDNotIn(vs ...uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNotIn(FieldHistoryID, vs...))
}

// HistoryIDGT applies the GT predicate on the "history_id" field.
func HistoryIDGT(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldGT(FieldHistoryID, v))
}

// HistoryIDGTE applies the GTE predicate on the "history_id" field.
func HistoryIDGTE(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldGTE(FieldHistoryID, v))
}

// HistoryIDLT applies the LT predicate on the "history_id" field.
func HistoryIDLT(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldLT(FieldHistoryID, v))
}

// HistoryIDLTE applies the LTE predicate on the "history_id" field.
func HistoryIDLTE(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldLTE(FieldHistoryID, v))
}

// PolicyHistoryIDEQ applies the EQ predicate on the "policy_history_id" field.
func PolicyHistoryIDEQ(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEQ(FieldPolicyHistoryID, v))
}

// PolicyHistoryIDNEQ applies the NEQ predicate on the "policy_history_id" field.
func PolicyHistoryIDNEQ(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNEQ(FieldPolicyHistoryID, v))
}

// PolicyHistoryIDIn applies the In predicate on the "policy_history_id" field.
func PolicyHistoryIDIn(vs ...uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldIn(FieldPolicyHistoryID, vs...))
}

// PolicyHistoryIDNotIn applies the NotIn predicate on the "policy_history_id" field.
func PolicyHistoryIDNotIn(vs ...uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNotIn(FieldPolicyHistoryID, vs...))
}

// PolicyHistoryIDGT applies the GT predicate on the "policy_history_id" field.
func PolicyHistoryIDGT(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldGT(FieldPolicyHistoryID, v))
}

// PolicyHistoryIDGTE applies the GTE predicate on the "policy_history_id" field.
func PolicyHistoryIDGTE(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldGTE(FieldPolicyHistoryID, v))
}

// PolicyHistoryIDLT applies the LT predicate on the "policy_history_id" field.
func PolicyHistoryIDLT(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldLT(FieldPolicyHistoryID, v))
}

// PolicyHistoryIDLTE applies the LTE predicate on the "policy_history_id" field.
func PolicyHistoryIDLTE(v uint) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldLTE(FieldPolicyHistoryID, v))
}

// ValidFromEQ applies the EQ predicate on the "valid_from" field.
func ValidFromEQ(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEQ(FieldValidFrom, v))
}

// ValidFromNEQ applies the NEQ predicate on the "valid_from" field.
func ValidFromNEQ(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNEQ(FieldValidFrom, v))
}

// ValidFromIn applies the In predicate on the "valid_from" field.
func ValidFromIn(vs ...time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldIn(FieldValidFrom, vs...))
}

// ValidFromNotIn applies the NotIn predicate on the "valid_from" field.
func ValidFromNotIn(vs ...time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNotIn(FieldValidFrom, vs...))
}

// ValidFromGT applies the GT predicate on the "valid_from" field.
func ValidFromGT(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldGT(FieldValidFrom, v))
}

// ValidFromGTE applies the GTE predicate on the "valid_from" field.
func ValidFromGTE(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldGTE(FieldValidFrom, v))
}

// ValidFromLT applies the LT predicate on the "valid_from" field.
func ValidFromLT(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldLT(FieldValidFrom, v))
}

// ValidFromLTE applies the LTE predicate on the "valid_from" field.
func ValidFromLTE(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldLTE(FieldValidFrom, v))
}

// ValidToEQ applies the EQ predicate on the "valid_to" field.
func ValidToEQ(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEQ(FieldValidTo, v))
}

// ValidToNEQ applies the NEQ predicate on the "valid_to" field.
func ValidToNEQ(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNEQ(FieldValidTo, v))
}

// ValidToIn applies the In predicate on the "valid_to" field.
func ValidToIn(vs ...time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldIn(FieldValidTo, vs...))
}

// ValidToNotIn applies the NotIn predicate on the "valid_to" field.
func ValidToNotIn(vs ...time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNotIn(FieldValidTo, vs...))
}

// ValidToGT applies the GT predicate on the "valid_to" field.
func ValidToGT(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldGT(FieldValidTo, v))
}

// ValidToGTE applies the GTE predicate on the "valid_to" field.
func ValidToGTE(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldGTE(FieldValidTo, v))
}

// ValidToLT applies the LT predicate on the "valid_to" field.
func ValidToLT(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldLT(FieldValidTo, v))
}

// ValidToLTE applies the LTE predicate on the "valid_to" field.
func ValidToLTE(v time.Time) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldLTE(FieldValidTo, v))
}

// ValidToIsNil applies the IsNil predicate on the "valid_to" field.
func ValidToIsNil() predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldIsNull(FieldValidTo))
}

// ValidToNotNil applies the NotNil predicate on the "valid_to" field.
func ValidToNotNil() predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNotNull(FieldValidTo))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldContainsFold(FieldRole, v))
}

// MembersJSONIsNil applies the IsNil predicate on the "members_json" field.
func MembersJSONIsNil() predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldIsNull(FieldMembersJSON))
}

// MembersJSONNotNil applies the NotNil predicate on the "members_json" field.
func MembersJSONNotNil() predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNotNull(FieldMembersJSON))
}

// ConditionJSONIsNil applies the IsNil predicate on the "condition_json" field.
func ConditionJSONIsNil() predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldIsNull(FieldConditionJSON))
}

// ConditionJSONNotNil applies the NotNil predicate on the "condition_json" field.
func ConditionJSONNotNil() predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.FieldNotNull(FieldConditionJSON))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding) predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding {
	return predicate.BronzeHistoryGCPStorageBucketIamPolicyBinding(sql.NotPredicates(p))
}
