// Code generated by ent, DO NOT EDIT.

package reference

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"danny.vn/hotpot/pkg/storage/ent/reference/bronzereferenceoscorerule"
	"danny.vn/hotpot/pkg/storage/ent/reference/internal"
	"danny.vn/hotpot/pkg/storage/ent/reference/predicate"
)

// BronzeReferenceOSCoreRuleDelete is the builder for deleting a BronzeReferenceOSCoreRule entity.
type BronzeReferenceOSCoreRuleDelete struct {
	config
	hooks    []Hook
	mutation *BronzeReferenceOSCoreRuleMutation
}

// Where appends a list predicates to the BronzeReferenceOSCoreRuleDelete builder.
func (_d *BronzeReferenceOSCoreRuleDelete) Where(ps ...predicate.BronzeReferenceOSCoreRule) *BronzeReferenceOSCoreRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BronzeReferenceOSCoreRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BronzeReferenceOSCoreRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BronzeReferenceOSCoreRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bronzereferenceoscorerule.Table, sqlgraph.NewFieldSpec(bronzereferenceoscorerule.FieldID, field.TypeString))
	_spec.Node.Schema = _d.schemaConfig.BronzeReferenceOSCoreRule
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BronzeReferenceOSCoreRuleDeleteOne is the builder for deleting a single BronzeReferenceOSCoreRule entity.
type BronzeReferenceOSCoreRuleDeleteOne struct {
	_d *BronzeReferenceOSCoreRuleDelete
}

// Where appends a list predicates to the BronzeReferenceOSCoreRuleDelete builder.
func (_d *BronzeReferenceOSCoreRuleDeleteOne) Where(ps ...predicate.BronzeReferenceOSCoreRule) *BronzeReferenceOSCoreRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BronzeReferenceOSCoreRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bronzereferenceoscorerule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BronzeReferenceOSCoreRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
