// Code generated by ent, DO NOT EDIT.

package reference

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/dannyota/hotpot/pkg/storage/ent/reference/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/dannyota/hotpot/pkg/storage/ent/reference/bronzereferencecpe"
	"github.com/dannyota/hotpot/pkg/storage/ent/reference/bronzereferencerpmpackage"
	"github.com/dannyota/hotpot/pkg/storage/ent/reference/bronzereferenceubuntupackage"

	"github.com/dannyota/hotpot/pkg/storage/ent/reference/internal"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// BronzeReferenceCPE is the client for interacting with the BronzeReferenceCPE builders.
	BronzeReferenceCPE *BronzeReferenceCPEClient
	// BronzeReferenceRPMPackage is the client for interacting with the BronzeReferenceRPMPackage builders.
	BronzeReferenceRPMPackage *BronzeReferenceRPMPackageClient
	// BronzeReferenceUbuntuPackage is the client for interacting with the BronzeReferenceUbuntuPackage builders.
	BronzeReferenceUbuntuPackage *BronzeReferenceUbuntuPackageClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.BronzeReferenceCPE = NewBronzeReferenceCPEClient(c.config)
	c.BronzeReferenceRPMPackage = NewBronzeReferenceRPMPackageClient(c.config)
	c.BronzeReferenceUbuntuPackage = NewBronzeReferenceUbuntuPackageClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
		// schemaConfig contains alternative names for all tables.
		schemaConfig SchemaConfig
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("reference: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("reference: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                          ctx,
		config:                       cfg,
		BronzeReferenceCPE:           NewBronzeReferenceCPEClient(cfg),
		BronzeReferenceRPMPackage:    NewBronzeReferenceRPMPackageClient(cfg),
		BronzeReferenceUbuntuPackage: NewBronzeReferenceUbuntuPackageClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                          ctx,
		config:                       cfg,
		BronzeReferenceCPE:           NewBronzeReferenceCPEClient(cfg),
		BronzeReferenceRPMPackage:    NewBronzeReferenceRPMPackageClient(cfg),
		BronzeReferenceUbuntuPackage: NewBronzeReferenceUbuntuPackageClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		BronzeReferenceCPE.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.BronzeReferenceCPE.Use(hooks...)
	c.BronzeReferenceRPMPackage.Use(hooks...)
	c.BronzeReferenceUbuntuPackage.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.BronzeReferenceCPE.Intercept(interceptors...)
	c.BronzeReferenceRPMPackage.Intercept(interceptors...)
	c.BronzeReferenceUbuntuPackage.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BronzeReferenceCPEMutation:
		return c.BronzeReferenceCPE.mutate(ctx, m)
	case *BronzeReferenceRPMPackageMutation:
		return c.BronzeReferenceRPMPackage.mutate(ctx, m)
	case *BronzeReferenceUbuntuPackageMutation:
		return c.BronzeReferenceUbuntuPackage.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("reference: unknown mutation type %T", m)
	}
}

// BronzeReferenceCPEClient is a client for the BronzeReferenceCPE schema.
type BronzeReferenceCPEClient struct {
	config
}

// NewBronzeReferenceCPEClient returns a client for the BronzeReferenceCPE from the given config.
func NewBronzeReferenceCPEClient(c config) *BronzeReferenceCPEClient {
	return &BronzeReferenceCPEClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bronzereferencecpe.Hooks(f(g(h())))`.
func (c *BronzeReferenceCPEClient) Use(hooks ...Hook) {
	c.hooks.BronzeReferenceCPE = append(c.hooks.BronzeReferenceCPE, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bronzereferencecpe.Intercept(f(g(h())))`.
func (c *BronzeReferenceCPEClient) Intercept(interceptors ...Interceptor) {
	c.inters.BronzeReferenceCPE = append(c.inters.BronzeReferenceCPE, interceptors...)
}

// Create returns a builder for creating a BronzeReferenceCPE entity.
func (c *BronzeReferenceCPEClient) Create() *BronzeReferenceCPECreate {
	mutation := newBronzeReferenceCPEMutation(c.config, OpCreate)
	return &BronzeReferenceCPECreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BronzeReferenceCPE entities.
func (c *BronzeReferenceCPEClient) CreateBulk(builders ...*BronzeReferenceCPECreate) *BronzeReferenceCPECreateBulk {
	return &BronzeReferenceCPECreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BronzeReferenceCPEClient) MapCreateBulk(slice any, setFunc func(*BronzeReferenceCPECreate, int)) *BronzeReferenceCPECreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BronzeReferenceCPECreateBulk{err: fmt.Errorf("calling to BronzeReferenceCPEClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BronzeReferenceCPECreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BronzeReferenceCPECreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BronzeReferenceCPE.
func (c *BronzeReferenceCPEClient) Update() *BronzeReferenceCPEUpdate {
	mutation := newBronzeReferenceCPEMutation(c.config, OpUpdate)
	return &BronzeReferenceCPEUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BronzeReferenceCPEClient) UpdateOne(_m *BronzeReferenceCPE) *BronzeReferenceCPEUpdateOne {
	mutation := newBronzeReferenceCPEMutation(c.config, OpUpdateOne, withBronzeReferenceCPE(_m))
	return &BronzeReferenceCPEUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BronzeReferenceCPEClient) UpdateOneID(id string) *BronzeReferenceCPEUpdateOne {
	mutation := newBronzeReferenceCPEMutation(c.config, OpUpdateOne, withBronzeReferenceCPEID(id))
	return &BronzeReferenceCPEUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BronzeReferenceCPE.
func (c *BronzeReferenceCPEClient) Delete() *BronzeReferenceCPEDelete {
	mutation := newBronzeReferenceCPEMutation(c.config, OpDelete)
	return &BronzeReferenceCPEDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BronzeReferenceCPEClient) DeleteOne(_m *BronzeReferenceCPE) *BronzeReferenceCPEDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BronzeReferenceCPEClient) DeleteOneID(id string) *BronzeReferenceCPEDeleteOne {
	builder := c.Delete().Where(bronzereferencecpe.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BronzeReferenceCPEDeleteOne{builder}
}

// Query returns a query builder for BronzeReferenceCPE.
func (c *BronzeReferenceCPEClient) Query() *BronzeReferenceCPEQuery {
	return &BronzeReferenceCPEQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBronzeReferenceCPE},
		inters: c.Interceptors(),
	}
}

// Get returns a BronzeReferenceCPE entity by its id.
func (c *BronzeReferenceCPEClient) Get(ctx context.Context, id string) (*BronzeReferenceCPE, error) {
	return c.Query().Where(bronzereferencecpe.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BronzeReferenceCPEClient) GetX(ctx context.Context, id string) *BronzeReferenceCPE {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BronzeReferenceCPEClient) Hooks() []Hook {
	return c.hooks.BronzeReferenceCPE
}

// Interceptors returns the client interceptors.
func (c *BronzeReferenceCPEClient) Interceptors() []Interceptor {
	return c.inters.BronzeReferenceCPE
}

func (c *BronzeReferenceCPEClient) mutate(ctx context.Context, m *BronzeReferenceCPEMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BronzeReferenceCPECreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BronzeReferenceCPEUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BronzeReferenceCPEUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BronzeReferenceCPEDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("reference: unknown BronzeReferenceCPE mutation op: %q", m.Op())
	}
}

// BronzeReferenceRPMPackageClient is a client for the BronzeReferenceRPMPackage schema.
type BronzeReferenceRPMPackageClient struct {
	config
}

// NewBronzeReferenceRPMPackageClient returns a client for the BronzeReferenceRPMPackage from the given config.
func NewBronzeReferenceRPMPackageClient(c config) *BronzeReferenceRPMPackageClient {
	return &BronzeReferenceRPMPackageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bronzereferencerpmpackage.Hooks(f(g(h())))`.
func (c *BronzeReferenceRPMPackageClient) Use(hooks ...Hook) {
	c.hooks.BronzeReferenceRPMPackage = append(c.hooks.BronzeReferenceRPMPackage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bronzereferencerpmpackage.Intercept(f(g(h())))`.
func (c *BronzeReferenceRPMPackageClient) Intercept(interceptors ...Interceptor) {
	c.inters.BronzeReferenceRPMPackage = append(c.inters.BronzeReferenceRPMPackage, interceptors...)
}

// Create returns a builder for creating a BronzeReferenceRPMPackage entity.
func (c *BronzeReferenceRPMPackageClient) Create() *BronzeReferenceRPMPackageCreate {
	mutation := newBronzeReferenceRPMPackageMutation(c.config, OpCreate)
	return &BronzeReferenceRPMPackageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BronzeReferenceRPMPackage entities.
func (c *BronzeReferenceRPMPackageClient) CreateBulk(builders ...*BronzeReferenceRPMPackageCreate) *BronzeReferenceRPMPackageCreateBulk {
	return &BronzeReferenceRPMPackageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BronzeReferenceRPMPackageClient) MapCreateBulk(slice any, setFunc func(*BronzeReferenceRPMPackageCreate, int)) *BronzeReferenceRPMPackageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BronzeReferenceRPMPackageCreateBulk{err: fmt.Errorf("calling to BronzeReferenceRPMPackageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BronzeReferenceRPMPackageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BronzeReferenceRPMPackageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BronzeReferenceRPMPackage.
func (c *BronzeReferenceRPMPackageClient) Update() *BronzeReferenceRPMPackageUpdate {
	mutation := newBronzeReferenceRPMPackageMutation(c.config, OpUpdate)
	return &BronzeReferenceRPMPackageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BronzeReferenceRPMPackageClient) UpdateOne(_m *BronzeReferenceRPMPackage) *BronzeReferenceRPMPackageUpdateOne {
	mutation := newBronzeReferenceRPMPackageMutation(c.config, OpUpdateOne, withBronzeReferenceRPMPackage(_m))
	return &BronzeReferenceRPMPackageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BronzeReferenceRPMPackageClient) UpdateOneID(id string) *BronzeReferenceRPMPackageUpdateOne {
	mutation := newBronzeReferenceRPMPackageMutation(c.config, OpUpdateOne, withBronzeReferenceRPMPackageID(id))
	return &BronzeReferenceRPMPackageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BronzeReferenceRPMPackage.
func (c *BronzeReferenceRPMPackageClient) Delete() *BronzeReferenceRPMPackageDelete {
	mutation := newBronzeReferenceRPMPackageMutation(c.config, OpDelete)
	return &BronzeReferenceRPMPackageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BronzeReferenceRPMPackageClient) DeleteOne(_m *BronzeReferenceRPMPackage) *BronzeReferenceRPMPackageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BronzeReferenceRPMPackageClient) DeleteOneID(id string) *BronzeReferenceRPMPackageDeleteOne {
	builder := c.Delete().Where(bronzereferencerpmpackage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BronzeReferenceRPMPackageDeleteOne{builder}
}

// Query returns a query builder for BronzeReferenceRPMPackage.
func (c *BronzeReferenceRPMPackageClient) Query() *BronzeReferenceRPMPackageQuery {
	return &BronzeReferenceRPMPackageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBronzeReferenceRPMPackage},
		inters: c.Interceptors(),
	}
}

// Get returns a BronzeReferenceRPMPackage entity by its id.
func (c *BronzeReferenceRPMPackageClient) Get(ctx context.Context, id string) (*BronzeReferenceRPMPackage, error) {
	return c.Query().Where(bronzereferencerpmpackage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BronzeReferenceRPMPackageClient) GetX(ctx context.Context, id string) *BronzeReferenceRPMPackage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BronzeReferenceRPMPackageClient) Hooks() []Hook {
	return c.hooks.BronzeReferenceRPMPackage
}

// Interceptors returns the client interceptors.
func (c *BronzeReferenceRPMPackageClient) Interceptors() []Interceptor {
	return c.inters.BronzeReferenceRPMPackage
}

func (c *BronzeReferenceRPMPackageClient) mutate(ctx context.Context, m *BronzeReferenceRPMPackageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BronzeReferenceRPMPackageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BronzeReferenceRPMPackageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BronzeReferenceRPMPackageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BronzeReferenceRPMPackageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("reference: unknown BronzeReferenceRPMPackage mutation op: %q", m.Op())
	}
}

// BronzeReferenceUbuntuPackageClient is a client for the BronzeReferenceUbuntuPackage schema.
type BronzeReferenceUbuntuPackageClient struct {
	config
}

// NewBronzeReferenceUbuntuPackageClient returns a client for the BronzeReferenceUbuntuPackage from the given config.
func NewBronzeReferenceUbuntuPackageClient(c config) *BronzeReferenceUbuntuPackageClient {
	return &BronzeReferenceUbuntuPackageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bronzereferenceubuntupackage.Hooks(f(g(h())))`.
func (c *BronzeReferenceUbuntuPackageClient) Use(hooks ...Hook) {
	c.hooks.BronzeReferenceUbuntuPackage = append(c.hooks.BronzeReferenceUbuntuPackage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bronzereferenceubuntupackage.Intercept(f(g(h())))`.
func (c *BronzeReferenceUbuntuPackageClient) Intercept(interceptors ...Interceptor) {
	c.inters.BronzeReferenceUbuntuPackage = append(c.inters.BronzeReferenceUbuntuPackage, interceptors...)
}

// Create returns a builder for creating a BronzeReferenceUbuntuPackage entity.
func (c *BronzeReferenceUbuntuPackageClient) Create() *BronzeReferenceUbuntuPackageCreate {
	mutation := newBronzeReferenceUbuntuPackageMutation(c.config, OpCreate)
	return &BronzeReferenceUbuntuPackageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BronzeReferenceUbuntuPackage entities.
func (c *BronzeReferenceUbuntuPackageClient) CreateBulk(builders ...*BronzeReferenceUbuntuPackageCreate) *BronzeReferenceUbuntuPackageCreateBulk {
	return &BronzeReferenceUbuntuPackageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BronzeReferenceUbuntuPackageClient) MapCreateBulk(slice any, setFunc func(*BronzeReferenceUbuntuPackageCreate, int)) *BronzeReferenceUbuntuPackageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BronzeReferenceUbuntuPackageCreateBulk{err: fmt.Errorf("calling to BronzeReferenceUbuntuPackageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BronzeReferenceUbuntuPackageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BronzeReferenceUbuntuPackageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BronzeReferenceUbuntuPackage.
func (c *BronzeReferenceUbuntuPackageClient) Update() *BronzeReferenceUbuntuPackageUpdate {
	mutation := newBronzeReferenceUbuntuPackageMutation(c.config, OpUpdate)
	return &BronzeReferenceUbuntuPackageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BronzeReferenceUbuntuPackageClient) UpdateOne(_m *BronzeReferenceUbuntuPackage) *BronzeReferenceUbuntuPackageUpdateOne {
	mutation := newBronzeReferenceUbuntuPackageMutation(c.config, OpUpdateOne, withBronzeReferenceUbuntuPackage(_m))
	return &BronzeReferenceUbuntuPackageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BronzeReferenceUbuntuPackageClient) UpdateOneID(id string) *BronzeReferenceUbuntuPackageUpdateOne {
	mutation := newBronzeReferenceUbuntuPackageMutation(c.config, OpUpdateOne, withBronzeReferenceUbuntuPackageID(id))
	return &BronzeReferenceUbuntuPackageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BronzeReferenceUbuntuPackage.
func (c *BronzeReferenceUbuntuPackageClient) Delete() *BronzeReferenceUbuntuPackageDelete {
	mutation := newBronzeReferenceUbuntuPackageMutation(c.config, OpDelete)
	return &BronzeReferenceUbuntuPackageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BronzeReferenceUbuntuPackageClient) DeleteOne(_m *BronzeReferenceUbuntuPackage) *BronzeReferenceUbuntuPackageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BronzeReferenceUbuntuPackageClient) DeleteOneID(id string) *BronzeReferenceUbuntuPackageDeleteOne {
	builder := c.Delete().Where(bronzereferenceubuntupackage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BronzeReferenceUbuntuPackageDeleteOne{builder}
}

// Query returns a query builder for BronzeReferenceUbuntuPackage.
func (c *BronzeReferenceUbuntuPackageClient) Query() *BronzeReferenceUbuntuPackageQuery {
	return &BronzeReferenceUbuntuPackageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBronzeReferenceUbuntuPackage},
		inters: c.Interceptors(),
	}
}

// Get returns a BronzeReferenceUbuntuPackage entity by its id.
func (c *BronzeReferenceUbuntuPackageClient) Get(ctx context.Context, id string) (*BronzeReferenceUbuntuPackage, error) {
	return c.Query().Where(bronzereferenceubuntupackage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BronzeReferenceUbuntuPackageClient) GetX(ctx context.Context, id string) *BronzeReferenceUbuntuPackage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BronzeReferenceUbuntuPackageClient) Hooks() []Hook {
	return c.hooks.BronzeReferenceUbuntuPackage
}

// Interceptors returns the client interceptors.
func (c *BronzeReferenceUbuntuPackageClient) Interceptors() []Interceptor {
	return c.inters.BronzeReferenceUbuntuPackage
}

func (c *BronzeReferenceUbuntuPackageClient) mutate(ctx context.Context, m *BronzeReferenceUbuntuPackageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BronzeReferenceUbuntuPackageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BronzeReferenceUbuntuPackageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BronzeReferenceUbuntuPackageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BronzeReferenceUbuntuPackageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("reference: unknown BronzeReferenceUbuntuPackage mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		BronzeReferenceCPE, BronzeReferenceRPMPackage,
		BronzeReferenceUbuntuPackage []ent.Hook
	}
	inters struct {
		BronzeReferenceCPE, BronzeReferenceRPMPackage,
		BronzeReferenceUbuntuPackage []ent.Interceptor
	}
)

// SchemaConfig represents alternative schema names for all tables
// that can be passed at runtime.
type SchemaConfig = internal.SchemaConfig

// AlternateSchemas allows alternate schema names to be
// passed into ent operations.
func AlternateSchema(schemaConfig SchemaConfig) Option {
	return func(c *config) {
		c.schemaConfig = schemaConfig
	}
}
