// Code generated by ent, DO NOT EDIT.

package bronzegcpredisinstance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dannyota/hotpot/pkg/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldID, id))
}

// CollectedAt applies equality check predicate on the "collected_at" field. It's identical to CollectedAtEQ.
func CollectedAt(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldCollectedAt, v))
}

// FirstCollectedAt applies equality check predicate on the "first_collected_at" field. It's identical to FirstCollectedAtEQ.
func FirstCollectedAt(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldFirstCollectedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldName, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldDisplayName, v))
}

// LocationID applies equality check predicate on the "location_id" field. It's identical to LocationIDEQ.
func LocationID(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldLocationID, v))
}

// AlternativeLocationID applies equality check predicate on the "alternative_location_id" field. It's identical to AlternativeLocationIDEQ.
func AlternativeLocationID(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldAlternativeLocationID, v))
}

// RedisVersion applies equality check predicate on the "redis_version" field. It's identical to RedisVersionEQ.
func RedisVersion(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldRedisVersion, v))
}

// ReservedIPRange applies equality check predicate on the "reserved_ip_range" field. It's identical to ReservedIPRangeEQ.
func ReservedIPRange(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldReservedIPRange, v))
}

// SecondaryIPRange applies equality check predicate on the "secondary_ip_range" field. It's identical to SecondaryIPRangeEQ.
func SecondaryIPRange(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldSecondaryIPRange, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldHost, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldPort, v))
}

// CurrentLocationID applies equality check predicate on the "current_location_id" field. It's identical to CurrentLocationIDEQ.
func CurrentLocationID(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldCurrentLocationID, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldCreateTime, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldState, v))
}

// StatusMessage applies equality check predicate on the "status_message" field. It's identical to StatusMessageEQ.
func StatusMessage(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldStatusMessage, v))
}

// Tier applies equality check predicate on the "tier" field. It's identical to TierEQ.
func Tier(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldTier, v))
}

// MemorySizeGB applies equality check predicate on the "memory_size_gb" field. It's identical to MemorySizeGBEQ.
func MemorySizeGB(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldMemorySizeGB, v))
}

// AuthorizedNetwork applies equality check predicate on the "authorized_network" field. It's identical to AuthorizedNetworkEQ.
func AuthorizedNetwork(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldAuthorizedNetwork, v))
}

// PersistenceIamIdentity applies equality check predicate on the "persistence_iam_identity" field. It's identical to PersistenceIamIdentityEQ.
func PersistenceIamIdentity(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldPersistenceIamIdentity, v))
}

// ConnectMode applies equality check predicate on the "connect_mode" field. It's identical to ConnectModeEQ.
func ConnectMode(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldConnectMode, v))
}

// AuthEnabled applies equality check predicate on the "auth_enabled" field. It's identical to AuthEnabledEQ.
func AuthEnabled(v bool) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldAuthEnabled, v))
}

// TransitEncryptionMode applies equality check predicate on the "transit_encryption_mode" field. It's identical to TransitEncryptionModeEQ.
func TransitEncryptionMode(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldTransitEncryptionMode, v))
}

// ReplicaCount applies equality check predicate on the "replica_count" field. It's identical to ReplicaCountEQ.
func ReplicaCount(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldReplicaCount, v))
}

// ReadEndpoint applies equality check predicate on the "read_endpoint" field. It's identical to ReadEndpointEQ.
func ReadEndpoint(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldReadEndpoint, v))
}

// ReadEndpointPort applies equality check predicate on the "read_endpoint_port" field. It's identical to ReadEndpointPortEQ.
func ReadEndpointPort(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldReadEndpointPort, v))
}

// ReadReplicasMode applies equality check predicate on the "read_replicas_mode" field. It's identical to ReadReplicasModeEQ.
func ReadReplicasMode(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldReadReplicasMode, v))
}

// CustomerManagedKey applies equality check predicate on the "customer_managed_key" field. It's identical to CustomerManagedKeyEQ.
func CustomerManagedKey(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldCustomerManagedKey, v))
}

// MaintenanceVersion applies equality check predicate on the "maintenance_version" field. It's identical to MaintenanceVersionEQ.
func MaintenanceVersion(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldMaintenanceVersion, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldProjectID, v))
}

// CollectedAtEQ applies the EQ predicate on the "collected_at" field.
func CollectedAtEQ(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldCollectedAt, v))
}

// CollectedAtNEQ applies the NEQ predicate on the "collected_at" field.
func CollectedAtNEQ(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldCollectedAt, v))
}

// CollectedAtIn applies the In predicate on the "collected_at" field.
func CollectedAtIn(vs ...time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldCollectedAt, vs...))
}

// CollectedAtNotIn applies the NotIn predicate on the "collected_at" field.
func CollectedAtNotIn(vs ...time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldCollectedAt, vs...))
}

// CollectedAtGT applies the GT predicate on the "collected_at" field.
func CollectedAtGT(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldCollectedAt, v))
}

// CollectedAtGTE applies the GTE predicate on the "collected_at" field.
func CollectedAtGTE(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldCollectedAt, v))
}

// CollectedAtLT applies the LT predicate on the "collected_at" field.
func CollectedAtLT(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldCollectedAt, v))
}

// CollectedAtLTE applies the LTE predicate on the "collected_at" field.
func CollectedAtLTE(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldCollectedAt, v))
}

// FirstCollectedAtEQ applies the EQ predicate on the "first_collected_at" field.
func FirstCollectedAtEQ(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldFirstCollectedAt, v))
}

// FirstCollectedAtNEQ applies the NEQ predicate on the "first_collected_at" field.
func FirstCollectedAtNEQ(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldFirstCollectedAt, v))
}

// FirstCollectedAtIn applies the In predicate on the "first_collected_at" field.
func FirstCollectedAtIn(vs ...time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldFirstCollectedAt, vs...))
}

// FirstCollectedAtNotIn applies the NotIn predicate on the "first_collected_at" field.
func FirstCollectedAtNotIn(vs ...time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldFirstCollectedAt, vs...))
}

// FirstCollectedAtGT applies the GT predicate on the "first_collected_at" field.
func FirstCollectedAtGT(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldFirstCollectedAt, v))
}

// FirstCollectedAtGTE applies the GTE predicate on the "first_collected_at" field.
func FirstCollectedAtGTE(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldFirstCollectedAt, v))
}

// FirstCollectedAtLT applies the LT predicate on the "first_collected_at" field.
func FirstCollectedAtLT(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldFirstCollectedAt, v))
}

// FirstCollectedAtLTE applies the LTE predicate on the "first_collected_at" field.
func FirstCollectedAtLTE(v time.Time) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldFirstCollectedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldName, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameIsNil applies the IsNil predicate on the "display_name" field.
func DisplayNameIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldDisplayName))
}

// DisplayNameNotNil applies the NotNil predicate on the "display_name" field.
func DisplayNameNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldDisplayName))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldDisplayName, v))
}

// LabelsJSONIsNil applies the IsNil predicate on the "labels_json" field.
func LabelsJSONIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldLabelsJSON))
}

// LabelsJSONNotNil applies the NotNil predicate on the "labels_json" field.
func LabelsJSONNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldLabelsJSON))
}

// LocationIDEQ applies the EQ predicate on the "location_id" field.
func LocationIDEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldLocationID, v))
}

// LocationIDNEQ applies the NEQ predicate on the "location_id" field.
func LocationIDNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldLocationID, v))
}

// LocationIDIn applies the In predicate on the "location_id" field.
func LocationIDIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldLocationID, vs...))
}

// LocationIDNotIn applies the NotIn predicate on the "location_id" field.
func LocationIDNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldLocationID, vs...))
}

// LocationIDGT applies the GT predicate on the "location_id" field.
func LocationIDGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldLocationID, v))
}

// LocationIDGTE applies the GTE predicate on the "location_id" field.
func LocationIDGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldLocationID, v))
}

// LocationIDLT applies the LT predicate on the "location_id" field.
func LocationIDLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldLocationID, v))
}

// LocationIDLTE applies the LTE predicate on the "location_id" field.
func LocationIDLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldLocationID, v))
}

// LocationIDContains applies the Contains predicate on the "location_id" field.
func LocationIDContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldLocationID, v))
}

// LocationIDHasPrefix applies the HasPrefix predicate on the "location_id" field.
func LocationIDHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldLocationID, v))
}

// LocationIDHasSuffix applies the HasSuffix predicate on the "location_id" field.
func LocationIDHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldLocationID, v))
}

// LocationIDIsNil applies the IsNil predicate on the "location_id" field.
func LocationIDIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldLocationID))
}

// LocationIDNotNil applies the NotNil predicate on the "location_id" field.
func LocationIDNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldLocationID))
}

// LocationIDEqualFold applies the EqualFold predicate on the "location_id" field.
func LocationIDEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldLocationID, v))
}

// LocationIDContainsFold applies the ContainsFold predicate on the "location_id" field.
func LocationIDContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldLocationID, v))
}

// AlternativeLocationIDEQ applies the EQ predicate on the "alternative_location_id" field.
func AlternativeLocationIDEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldAlternativeLocationID, v))
}

// AlternativeLocationIDNEQ applies the NEQ predicate on the "alternative_location_id" field.
func AlternativeLocationIDNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldAlternativeLocationID, v))
}

// AlternativeLocationIDIn applies the In predicate on the "alternative_location_id" field.
func AlternativeLocationIDIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldAlternativeLocationID, vs...))
}

// AlternativeLocationIDNotIn applies the NotIn predicate on the "alternative_location_id" field.
func AlternativeLocationIDNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldAlternativeLocationID, vs...))
}

// AlternativeLocationIDGT applies the GT predicate on the "alternative_location_id" field.
func AlternativeLocationIDGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldAlternativeLocationID, v))
}

// AlternativeLocationIDGTE applies the GTE predicate on the "alternative_location_id" field.
func AlternativeLocationIDGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldAlternativeLocationID, v))
}

// AlternativeLocationIDLT applies the LT predicate on the "alternative_location_id" field.
func AlternativeLocationIDLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldAlternativeLocationID, v))
}

// AlternativeLocationIDLTE applies the LTE predicate on the "alternative_location_id" field.
func AlternativeLocationIDLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldAlternativeLocationID, v))
}

// AlternativeLocationIDContains applies the Contains predicate on the "alternative_location_id" field.
func AlternativeLocationIDContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldAlternativeLocationID, v))
}

// AlternativeLocationIDHasPrefix applies the HasPrefix predicate on the "alternative_location_id" field.
func AlternativeLocationIDHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldAlternativeLocationID, v))
}

// AlternativeLocationIDHasSuffix applies the HasSuffix predicate on the "alternative_location_id" field.
func AlternativeLocationIDHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldAlternativeLocationID, v))
}

// AlternativeLocationIDIsNil applies the IsNil predicate on the "alternative_location_id" field.
func AlternativeLocationIDIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldAlternativeLocationID))
}

// AlternativeLocationIDNotNil applies the NotNil predicate on the "alternative_location_id" field.
func AlternativeLocationIDNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldAlternativeLocationID))
}

// AlternativeLocationIDEqualFold applies the EqualFold predicate on the "alternative_location_id" field.
func AlternativeLocationIDEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldAlternativeLocationID, v))
}

// AlternativeLocationIDContainsFold applies the ContainsFold predicate on the "alternative_location_id" field.
func AlternativeLocationIDContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldAlternativeLocationID, v))
}

// RedisVersionEQ applies the EQ predicate on the "redis_version" field.
func RedisVersionEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldRedisVersion, v))
}

// RedisVersionNEQ applies the NEQ predicate on the "redis_version" field.
func RedisVersionNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldRedisVersion, v))
}

// RedisVersionIn applies the In predicate on the "redis_version" field.
func RedisVersionIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldRedisVersion, vs...))
}

// RedisVersionNotIn applies the NotIn predicate on the "redis_version" field.
func RedisVersionNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldRedisVersion, vs...))
}

// RedisVersionGT applies the GT predicate on the "redis_version" field.
func RedisVersionGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldRedisVersion, v))
}

// RedisVersionGTE applies the GTE predicate on the "redis_version" field.
func RedisVersionGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldRedisVersion, v))
}

// RedisVersionLT applies the LT predicate on the "redis_version" field.
func RedisVersionLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldRedisVersion, v))
}

// RedisVersionLTE applies the LTE predicate on the "redis_version" field.
func RedisVersionLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldRedisVersion, v))
}

// RedisVersionContains applies the Contains predicate on the "redis_version" field.
func RedisVersionContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldRedisVersion, v))
}

// RedisVersionHasPrefix applies the HasPrefix predicate on the "redis_version" field.
func RedisVersionHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldRedisVersion, v))
}

// RedisVersionHasSuffix applies the HasSuffix predicate on the "redis_version" field.
func RedisVersionHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldRedisVersion, v))
}

// RedisVersionIsNil applies the IsNil predicate on the "redis_version" field.
func RedisVersionIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldRedisVersion))
}

// RedisVersionNotNil applies the NotNil predicate on the "redis_version" field.
func RedisVersionNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldRedisVersion))
}

// RedisVersionEqualFold applies the EqualFold predicate on the "redis_version" field.
func RedisVersionEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldRedisVersion, v))
}

// RedisVersionContainsFold applies the ContainsFold predicate on the "redis_version" field.
func RedisVersionContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldRedisVersion, v))
}

// ReservedIPRangeEQ applies the EQ predicate on the "reserved_ip_range" field.
func ReservedIPRangeEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldReservedIPRange, v))
}

// ReservedIPRangeNEQ applies the NEQ predicate on the "reserved_ip_range" field.
func ReservedIPRangeNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldReservedIPRange, v))
}

// ReservedIPRangeIn applies the In predicate on the "reserved_ip_range" field.
func ReservedIPRangeIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldReservedIPRange, vs...))
}

// ReservedIPRangeNotIn applies the NotIn predicate on the "reserved_ip_range" field.
func ReservedIPRangeNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldReservedIPRange, vs...))
}

// ReservedIPRangeGT applies the GT predicate on the "reserved_ip_range" field.
func ReservedIPRangeGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldReservedIPRange, v))
}

// ReservedIPRangeGTE applies the GTE predicate on the "reserved_ip_range" field.
func ReservedIPRangeGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldReservedIPRange, v))
}

// ReservedIPRangeLT applies the LT predicate on the "reserved_ip_range" field.
func ReservedIPRangeLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldReservedIPRange, v))
}

// ReservedIPRangeLTE applies the LTE predicate on the "reserved_ip_range" field.
func ReservedIPRangeLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldReservedIPRange, v))
}

// ReservedIPRangeContains applies the Contains predicate on the "reserved_ip_range" field.
func ReservedIPRangeContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldReservedIPRange, v))
}

// ReservedIPRangeHasPrefix applies the HasPrefix predicate on the "reserved_ip_range" field.
func ReservedIPRangeHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldReservedIPRange, v))
}

// ReservedIPRangeHasSuffix applies the HasSuffix predicate on the "reserved_ip_range" field.
func ReservedIPRangeHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldReservedIPRange, v))
}

// ReservedIPRangeIsNil applies the IsNil predicate on the "reserved_ip_range" field.
func ReservedIPRangeIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldReservedIPRange))
}

// ReservedIPRangeNotNil applies the NotNil predicate on the "reserved_ip_range" field.
func ReservedIPRangeNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldReservedIPRange))
}

// ReservedIPRangeEqualFold applies the EqualFold predicate on the "reserved_ip_range" field.
func ReservedIPRangeEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldReservedIPRange, v))
}

// ReservedIPRangeContainsFold applies the ContainsFold predicate on the "reserved_ip_range" field.
func ReservedIPRangeContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldReservedIPRange, v))
}

// SecondaryIPRangeEQ applies the EQ predicate on the "secondary_ip_range" field.
func SecondaryIPRangeEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldSecondaryIPRange, v))
}

// SecondaryIPRangeNEQ applies the NEQ predicate on the "secondary_ip_range" field.
func SecondaryIPRangeNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldSecondaryIPRange, v))
}

// SecondaryIPRangeIn applies the In predicate on the "secondary_ip_range" field.
func SecondaryIPRangeIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldSecondaryIPRange, vs...))
}

// SecondaryIPRangeNotIn applies the NotIn predicate on the "secondary_ip_range" field.
func SecondaryIPRangeNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldSecondaryIPRange, vs...))
}

// SecondaryIPRangeGT applies the GT predicate on the "secondary_ip_range" field.
func SecondaryIPRangeGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldSecondaryIPRange, v))
}

// SecondaryIPRangeGTE applies the GTE predicate on the "secondary_ip_range" field.
func SecondaryIPRangeGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldSecondaryIPRange, v))
}

// SecondaryIPRangeLT applies the LT predicate on the "secondary_ip_range" field.
func SecondaryIPRangeLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldSecondaryIPRange, v))
}

// SecondaryIPRangeLTE applies the LTE predicate on the "secondary_ip_range" field.
func SecondaryIPRangeLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldSecondaryIPRange, v))
}

// SecondaryIPRangeContains applies the Contains predicate on the "secondary_ip_range" field.
func SecondaryIPRangeContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldSecondaryIPRange, v))
}

// SecondaryIPRangeHasPrefix applies the HasPrefix predicate on the "secondary_ip_range" field.
func SecondaryIPRangeHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldSecondaryIPRange, v))
}

// SecondaryIPRangeHasSuffix applies the HasSuffix predicate on the "secondary_ip_range" field.
func SecondaryIPRangeHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldSecondaryIPRange, v))
}

// SecondaryIPRangeIsNil applies the IsNil predicate on the "secondary_ip_range" field.
func SecondaryIPRangeIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldSecondaryIPRange))
}

// SecondaryIPRangeNotNil applies the NotNil predicate on the "secondary_ip_range" field.
func SecondaryIPRangeNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldSecondaryIPRange))
}

// SecondaryIPRangeEqualFold applies the EqualFold predicate on the "secondary_ip_range" field.
func SecondaryIPRangeEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldSecondaryIPRange, v))
}

// SecondaryIPRangeContainsFold applies the ContainsFold predicate on the "secondary_ip_range" field.
func SecondaryIPRangeContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldSecondaryIPRange, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldHost, v))
}

// HostIsNil applies the IsNil predicate on the "host" field.
func HostIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldHost))
}

// HostNotNil applies the NotNil predicate on the "host" field.
func HostNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldHost))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldHost, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldPort, v))
}

// PortIsNil applies the IsNil predicate on the "port" field.
func PortIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldPort))
}

// PortNotNil applies the NotNil predicate on the "port" field.
func PortNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldPort))
}

// CurrentLocationIDEQ applies the EQ predicate on the "current_location_id" field.
func CurrentLocationIDEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldCurrentLocationID, v))
}

// CurrentLocationIDNEQ applies the NEQ predicate on the "current_location_id" field.
func CurrentLocationIDNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldCurrentLocationID, v))
}

// CurrentLocationIDIn applies the In predicate on the "current_location_id" field.
func CurrentLocationIDIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldCurrentLocationID, vs...))
}

// CurrentLocationIDNotIn applies the NotIn predicate on the "current_location_id" field.
func CurrentLocationIDNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldCurrentLocationID, vs...))
}

// CurrentLocationIDGT applies the GT predicate on the "current_location_id" field.
func CurrentLocationIDGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldCurrentLocationID, v))
}

// CurrentLocationIDGTE applies the GTE predicate on the "current_location_id" field.
func CurrentLocationIDGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldCurrentLocationID, v))
}

// CurrentLocationIDLT applies the LT predicate on the "current_location_id" field.
func CurrentLocationIDLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldCurrentLocationID, v))
}

// CurrentLocationIDLTE applies the LTE predicate on the "current_location_id" field.
func CurrentLocationIDLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldCurrentLocationID, v))
}

// CurrentLocationIDContains applies the Contains predicate on the "current_location_id" field.
func CurrentLocationIDContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldCurrentLocationID, v))
}

// CurrentLocationIDHasPrefix applies the HasPrefix predicate on the "current_location_id" field.
func CurrentLocationIDHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldCurrentLocationID, v))
}

// CurrentLocationIDHasSuffix applies the HasSuffix predicate on the "current_location_id" field.
func CurrentLocationIDHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldCurrentLocationID, v))
}

// CurrentLocationIDIsNil applies the IsNil predicate on the "current_location_id" field.
func CurrentLocationIDIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldCurrentLocationID))
}

// CurrentLocationIDNotNil applies the NotNil predicate on the "current_location_id" field.
func CurrentLocationIDNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldCurrentLocationID))
}

// CurrentLocationIDEqualFold applies the EqualFold predicate on the "current_location_id" field.
func CurrentLocationIDEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldCurrentLocationID, v))
}

// CurrentLocationIDContainsFold applies the ContainsFold predicate on the "current_location_id" field.
func CurrentLocationIDContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldCurrentLocationID, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeContains applies the Contains predicate on the "create_time" field.
func CreateTimeContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldCreateTime, v))
}

// CreateTimeHasPrefix applies the HasPrefix predicate on the "create_time" field.
func CreateTimeHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldCreateTime, v))
}

// CreateTimeHasSuffix applies the HasSuffix predicate on the "create_time" field.
func CreateTimeHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldCreateTime))
}

// CreateTimeEqualFold applies the EqualFold predicate on the "create_time" field.
func CreateTimeEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldCreateTime, v))
}

// CreateTimeContainsFold applies the ContainsFold predicate on the "create_time" field.
func CreateTimeContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldCreateTime, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldState, v))
}

// StateIsNil applies the IsNil predicate on the "state" field.
func StateIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldState))
}

// StateNotNil applies the NotNil predicate on the "state" field.
func StateNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldState))
}

// StatusMessageEQ applies the EQ predicate on the "status_message" field.
func StatusMessageEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldStatusMessage, v))
}

// StatusMessageNEQ applies the NEQ predicate on the "status_message" field.
func StatusMessageNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldStatusMessage, v))
}

// StatusMessageIn applies the In predicate on the "status_message" field.
func StatusMessageIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldStatusMessage, vs...))
}

// StatusMessageNotIn applies the NotIn predicate on the "status_message" field.
func StatusMessageNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldStatusMessage, vs...))
}

// StatusMessageGT applies the GT predicate on the "status_message" field.
func StatusMessageGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldStatusMessage, v))
}

// StatusMessageGTE applies the GTE predicate on the "status_message" field.
func StatusMessageGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldStatusMessage, v))
}

// StatusMessageLT applies the LT predicate on the "status_message" field.
func StatusMessageLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldStatusMessage, v))
}

// StatusMessageLTE applies the LTE predicate on the "status_message" field.
func StatusMessageLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldStatusMessage, v))
}

// StatusMessageContains applies the Contains predicate on the "status_message" field.
func StatusMessageContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldStatusMessage, v))
}

// StatusMessageHasPrefix applies the HasPrefix predicate on the "status_message" field.
func StatusMessageHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldStatusMessage, v))
}

// StatusMessageHasSuffix applies the HasSuffix predicate on the "status_message" field.
func StatusMessageHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldStatusMessage, v))
}

// StatusMessageIsNil applies the IsNil predicate on the "status_message" field.
func StatusMessageIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldStatusMessage))
}

// StatusMessageNotNil applies the NotNil predicate on the "status_message" field.
func StatusMessageNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldStatusMessage))
}

// StatusMessageEqualFold applies the EqualFold predicate on the "status_message" field.
func StatusMessageEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldStatusMessage, v))
}

// StatusMessageContainsFold applies the ContainsFold predicate on the "status_message" field.
func StatusMessageContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldStatusMessage, v))
}

// RedisConfigsJSONIsNil applies the IsNil predicate on the "redis_configs_json" field.
func RedisConfigsJSONIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldRedisConfigsJSON))
}

// RedisConfigsJSONNotNil applies the NotNil predicate on the "redis_configs_json" field.
func RedisConfigsJSONNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldRedisConfigsJSON))
}

// TierEQ applies the EQ predicate on the "tier" field.
func TierEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldTier, v))
}

// TierNEQ applies the NEQ predicate on the "tier" field.
func TierNEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldTier, v))
}

// TierIn applies the In predicate on the "tier" field.
func TierIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldTier, vs...))
}

// TierNotIn applies the NotIn predicate on the "tier" field.
func TierNotIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldTier, vs...))
}

// TierGT applies the GT predicate on the "tier" field.
func TierGT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldTier, v))
}

// TierGTE applies the GTE predicate on the "tier" field.
func TierGTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldTier, v))
}

// TierLT applies the LT predicate on the "tier" field.
func TierLT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldTier, v))
}

// TierLTE applies the LTE predicate on the "tier" field.
func TierLTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldTier, v))
}

// TierIsNil applies the IsNil predicate on the "tier" field.
func TierIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldTier))
}

// TierNotNil applies the NotNil predicate on the "tier" field.
func TierNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldTier))
}

// MemorySizeGBEQ applies the EQ predicate on the "memory_size_gb" field.
func MemorySizeGBEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldMemorySizeGB, v))
}

// MemorySizeGBNEQ applies the NEQ predicate on the "memory_size_gb" field.
func MemorySizeGBNEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldMemorySizeGB, v))
}

// MemorySizeGBIn applies the In predicate on the "memory_size_gb" field.
func MemorySizeGBIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldMemorySizeGB, vs...))
}

// MemorySizeGBNotIn applies the NotIn predicate on the "memory_size_gb" field.
func MemorySizeGBNotIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldMemorySizeGB, vs...))
}

// MemorySizeGBGT applies the GT predicate on the "memory_size_gb" field.
func MemorySizeGBGT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldMemorySizeGB, v))
}

// MemorySizeGBGTE applies the GTE predicate on the "memory_size_gb" field.
func MemorySizeGBGTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldMemorySizeGB, v))
}

// MemorySizeGBLT applies the LT predicate on the "memory_size_gb" field.
func MemorySizeGBLT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldMemorySizeGB, v))
}

// MemorySizeGBLTE applies the LTE predicate on the "memory_size_gb" field.
func MemorySizeGBLTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldMemorySizeGB, v))
}

// MemorySizeGBIsNil applies the IsNil predicate on the "memory_size_gb" field.
func MemorySizeGBIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldMemorySizeGB))
}

// MemorySizeGBNotNil applies the NotNil predicate on the "memory_size_gb" field.
func MemorySizeGBNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldMemorySizeGB))
}

// AuthorizedNetworkEQ applies the EQ predicate on the "authorized_network" field.
func AuthorizedNetworkEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldAuthorizedNetwork, v))
}

// AuthorizedNetworkNEQ applies the NEQ predicate on the "authorized_network" field.
func AuthorizedNetworkNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldAuthorizedNetwork, v))
}

// AuthorizedNetworkIn applies the In predicate on the "authorized_network" field.
func AuthorizedNetworkIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldAuthorizedNetwork, vs...))
}

// AuthorizedNetworkNotIn applies the NotIn predicate on the "authorized_network" field.
func AuthorizedNetworkNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldAuthorizedNetwork, vs...))
}

// AuthorizedNetworkGT applies the GT predicate on the "authorized_network" field.
func AuthorizedNetworkGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldAuthorizedNetwork, v))
}

// AuthorizedNetworkGTE applies the GTE predicate on the "authorized_network" field.
func AuthorizedNetworkGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldAuthorizedNetwork, v))
}

// AuthorizedNetworkLT applies the LT predicate on the "authorized_network" field.
func AuthorizedNetworkLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldAuthorizedNetwork, v))
}

// AuthorizedNetworkLTE applies the LTE predicate on the "authorized_network" field.
func AuthorizedNetworkLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldAuthorizedNetwork, v))
}

// AuthorizedNetworkContains applies the Contains predicate on the "authorized_network" field.
func AuthorizedNetworkContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldAuthorizedNetwork, v))
}

// AuthorizedNetworkHasPrefix applies the HasPrefix predicate on the "authorized_network" field.
func AuthorizedNetworkHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldAuthorizedNetwork, v))
}

// AuthorizedNetworkHasSuffix applies the HasSuffix predicate on the "authorized_network" field.
func AuthorizedNetworkHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldAuthorizedNetwork, v))
}

// AuthorizedNetworkIsNil applies the IsNil predicate on the "authorized_network" field.
func AuthorizedNetworkIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldAuthorizedNetwork))
}

// AuthorizedNetworkNotNil applies the NotNil predicate on the "authorized_network" field.
func AuthorizedNetworkNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldAuthorizedNetwork))
}

// AuthorizedNetworkEqualFold applies the EqualFold predicate on the "authorized_network" field.
func AuthorizedNetworkEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldAuthorizedNetwork, v))
}

// AuthorizedNetworkContainsFold applies the ContainsFold predicate on the "authorized_network" field.
func AuthorizedNetworkContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldAuthorizedNetwork, v))
}

// PersistenceIamIdentityEQ applies the EQ predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldPersistenceIamIdentity, v))
}

// PersistenceIamIdentityNEQ applies the NEQ predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldPersistenceIamIdentity, v))
}

// PersistenceIamIdentityIn applies the In predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldPersistenceIamIdentity, vs...))
}

// PersistenceIamIdentityNotIn applies the NotIn predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldPersistenceIamIdentity, vs...))
}

// PersistenceIamIdentityGT applies the GT predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldPersistenceIamIdentity, v))
}

// PersistenceIamIdentityGTE applies the GTE predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldPersistenceIamIdentity, v))
}

// PersistenceIamIdentityLT applies the LT predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldPersistenceIamIdentity, v))
}

// PersistenceIamIdentityLTE applies the LTE predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldPersistenceIamIdentity, v))
}

// PersistenceIamIdentityContains applies the Contains predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldPersistenceIamIdentity, v))
}

// PersistenceIamIdentityHasPrefix applies the HasPrefix predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldPersistenceIamIdentity, v))
}

// PersistenceIamIdentityHasSuffix applies the HasSuffix predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldPersistenceIamIdentity, v))
}

// PersistenceIamIdentityIsNil applies the IsNil predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldPersistenceIamIdentity))
}

// PersistenceIamIdentityNotNil applies the NotNil predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldPersistenceIamIdentity))
}

// PersistenceIamIdentityEqualFold applies the EqualFold predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldPersistenceIamIdentity, v))
}

// PersistenceIamIdentityContainsFold applies the ContainsFold predicate on the "persistence_iam_identity" field.
func PersistenceIamIdentityContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldPersistenceIamIdentity, v))
}

// ConnectModeEQ applies the EQ predicate on the "connect_mode" field.
func ConnectModeEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldConnectMode, v))
}

// ConnectModeNEQ applies the NEQ predicate on the "connect_mode" field.
func ConnectModeNEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldConnectMode, v))
}

// ConnectModeIn applies the In predicate on the "connect_mode" field.
func ConnectModeIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldConnectMode, vs...))
}

// ConnectModeNotIn applies the NotIn predicate on the "connect_mode" field.
func ConnectModeNotIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldConnectMode, vs...))
}

// ConnectModeGT applies the GT predicate on the "connect_mode" field.
func ConnectModeGT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldConnectMode, v))
}

// ConnectModeGTE applies the GTE predicate on the "connect_mode" field.
func ConnectModeGTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldConnectMode, v))
}

// ConnectModeLT applies the LT predicate on the "connect_mode" field.
func ConnectModeLT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldConnectMode, v))
}

// ConnectModeLTE applies the LTE predicate on the "connect_mode" field.
func ConnectModeLTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldConnectMode, v))
}

// ConnectModeIsNil applies the IsNil predicate on the "connect_mode" field.
func ConnectModeIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldConnectMode))
}

// ConnectModeNotNil applies the NotNil predicate on the "connect_mode" field.
func ConnectModeNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldConnectMode))
}

// AuthEnabledEQ applies the EQ predicate on the "auth_enabled" field.
func AuthEnabledEQ(v bool) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldAuthEnabled, v))
}

// AuthEnabledNEQ applies the NEQ predicate on the "auth_enabled" field.
func AuthEnabledNEQ(v bool) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldAuthEnabled, v))
}

// ServerCaCertsJSONIsNil applies the IsNil predicate on the "server_ca_certs_json" field.
func ServerCaCertsJSONIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldServerCaCertsJSON))
}

// ServerCaCertsJSONNotNil applies the NotNil predicate on the "server_ca_certs_json" field.
func ServerCaCertsJSONNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldServerCaCertsJSON))
}

// TransitEncryptionModeEQ applies the EQ predicate on the "transit_encryption_mode" field.
func TransitEncryptionModeEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldTransitEncryptionMode, v))
}

// TransitEncryptionModeNEQ applies the NEQ predicate on the "transit_encryption_mode" field.
func TransitEncryptionModeNEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldTransitEncryptionMode, v))
}

// TransitEncryptionModeIn applies the In predicate on the "transit_encryption_mode" field.
func TransitEncryptionModeIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldTransitEncryptionMode, vs...))
}

// TransitEncryptionModeNotIn applies the NotIn predicate on the "transit_encryption_mode" field.
func TransitEncryptionModeNotIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldTransitEncryptionMode, vs...))
}

// TransitEncryptionModeGT applies the GT predicate on the "transit_encryption_mode" field.
func TransitEncryptionModeGT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldTransitEncryptionMode, v))
}

// TransitEncryptionModeGTE applies the GTE predicate on the "transit_encryption_mode" field.
func TransitEncryptionModeGTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldTransitEncryptionMode, v))
}

// TransitEncryptionModeLT applies the LT predicate on the "transit_encryption_mode" field.
func TransitEncryptionModeLT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldTransitEncryptionMode, v))
}

// TransitEncryptionModeLTE applies the LTE predicate on the "transit_encryption_mode" field.
func TransitEncryptionModeLTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldTransitEncryptionMode, v))
}

// TransitEncryptionModeIsNil applies the IsNil predicate on the "transit_encryption_mode" field.
func TransitEncryptionModeIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldTransitEncryptionMode))
}

// TransitEncryptionModeNotNil applies the NotNil predicate on the "transit_encryption_mode" field.
func TransitEncryptionModeNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldTransitEncryptionMode))
}

// MaintenancePolicyJSONIsNil applies the IsNil predicate on the "maintenance_policy_json" field.
func MaintenancePolicyJSONIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldMaintenancePolicyJSON))
}

// MaintenancePolicyJSONNotNil applies the NotNil predicate on the "maintenance_policy_json" field.
func MaintenancePolicyJSONNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldMaintenancePolicyJSON))
}

// MaintenanceScheduleJSONIsNil applies the IsNil predicate on the "maintenance_schedule_json" field.
func MaintenanceScheduleJSONIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldMaintenanceScheduleJSON))
}

// MaintenanceScheduleJSONNotNil applies the NotNil predicate on the "maintenance_schedule_json" field.
func MaintenanceScheduleJSONNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldMaintenanceScheduleJSON))
}

// ReplicaCountEQ applies the EQ predicate on the "replica_count" field.
func ReplicaCountEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldReplicaCount, v))
}

// ReplicaCountNEQ applies the NEQ predicate on the "replica_count" field.
func ReplicaCountNEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldReplicaCount, v))
}

// ReplicaCountIn applies the In predicate on the "replica_count" field.
func ReplicaCountIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldReplicaCount, vs...))
}

// ReplicaCountNotIn applies the NotIn predicate on the "replica_count" field.
func ReplicaCountNotIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldReplicaCount, vs...))
}

// ReplicaCountGT applies the GT predicate on the "replica_count" field.
func ReplicaCountGT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldReplicaCount, v))
}

// ReplicaCountGTE applies the GTE predicate on the "replica_count" field.
func ReplicaCountGTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldReplicaCount, v))
}

// ReplicaCountLT applies the LT predicate on the "replica_count" field.
func ReplicaCountLT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldReplicaCount, v))
}

// ReplicaCountLTE applies the LTE predicate on the "replica_count" field.
func ReplicaCountLTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldReplicaCount, v))
}

// ReplicaCountIsNil applies the IsNil predicate on the "replica_count" field.
func ReplicaCountIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldReplicaCount))
}

// ReplicaCountNotNil applies the NotNil predicate on the "replica_count" field.
func ReplicaCountNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldReplicaCount))
}

// NodesJSONIsNil applies the IsNil predicate on the "nodes_json" field.
func NodesJSONIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldNodesJSON))
}

// NodesJSONNotNil applies the NotNil predicate on the "nodes_json" field.
func NodesJSONNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldNodesJSON))
}

// ReadEndpointEQ applies the EQ predicate on the "read_endpoint" field.
func ReadEndpointEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldReadEndpoint, v))
}

// ReadEndpointNEQ applies the NEQ predicate on the "read_endpoint" field.
func ReadEndpointNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldReadEndpoint, v))
}

// ReadEndpointIn applies the In predicate on the "read_endpoint" field.
func ReadEndpointIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldReadEndpoint, vs...))
}

// ReadEndpointNotIn applies the NotIn predicate on the "read_endpoint" field.
func ReadEndpointNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldReadEndpoint, vs...))
}

// ReadEndpointGT applies the GT predicate on the "read_endpoint" field.
func ReadEndpointGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldReadEndpoint, v))
}

// ReadEndpointGTE applies the GTE predicate on the "read_endpoint" field.
func ReadEndpointGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldReadEndpoint, v))
}

// ReadEndpointLT applies the LT predicate on the "read_endpoint" field.
func ReadEndpointLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldReadEndpoint, v))
}

// ReadEndpointLTE applies the LTE predicate on the "read_endpoint" field.
func ReadEndpointLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldReadEndpoint, v))
}

// ReadEndpointContains applies the Contains predicate on the "read_endpoint" field.
func ReadEndpointContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldReadEndpoint, v))
}

// ReadEndpointHasPrefix applies the HasPrefix predicate on the "read_endpoint" field.
func ReadEndpointHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldReadEndpoint, v))
}

// ReadEndpointHasSuffix applies the HasSuffix predicate on the "read_endpoint" field.
func ReadEndpointHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldReadEndpoint, v))
}

// ReadEndpointIsNil applies the IsNil predicate on the "read_endpoint" field.
func ReadEndpointIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldReadEndpoint))
}

// ReadEndpointNotNil applies the NotNil predicate on the "read_endpoint" field.
func ReadEndpointNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldReadEndpoint))
}

// ReadEndpointEqualFold applies the EqualFold predicate on the "read_endpoint" field.
func ReadEndpointEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldReadEndpoint, v))
}

// ReadEndpointContainsFold applies the ContainsFold predicate on the "read_endpoint" field.
func ReadEndpointContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldReadEndpoint, v))
}

// ReadEndpointPortEQ applies the EQ predicate on the "read_endpoint_port" field.
func ReadEndpointPortEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldReadEndpointPort, v))
}

// ReadEndpointPortNEQ applies the NEQ predicate on the "read_endpoint_port" field.
func ReadEndpointPortNEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldReadEndpointPort, v))
}

// ReadEndpointPortIn applies the In predicate on the "read_endpoint_port" field.
func ReadEndpointPortIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldReadEndpointPort, vs...))
}

// ReadEndpointPortNotIn applies the NotIn predicate on the "read_endpoint_port" field.
func ReadEndpointPortNotIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldReadEndpointPort, vs...))
}

// ReadEndpointPortGT applies the GT predicate on the "read_endpoint_port" field.
func ReadEndpointPortGT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldReadEndpointPort, v))
}

// ReadEndpointPortGTE applies the GTE predicate on the "read_endpoint_port" field.
func ReadEndpointPortGTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldReadEndpointPort, v))
}

// ReadEndpointPortLT applies the LT predicate on the "read_endpoint_port" field.
func ReadEndpointPortLT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldReadEndpointPort, v))
}

// ReadEndpointPortLTE applies the LTE predicate on the "read_endpoint_port" field.
func ReadEndpointPortLTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldReadEndpointPort, v))
}

// ReadEndpointPortIsNil applies the IsNil predicate on the "read_endpoint_port" field.
func ReadEndpointPortIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldReadEndpointPort))
}

// ReadEndpointPortNotNil applies the NotNil predicate on the "read_endpoint_port" field.
func ReadEndpointPortNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldReadEndpointPort))
}

// ReadReplicasModeEQ applies the EQ predicate on the "read_replicas_mode" field.
func ReadReplicasModeEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldReadReplicasMode, v))
}

// ReadReplicasModeNEQ applies the NEQ predicate on the "read_replicas_mode" field.
func ReadReplicasModeNEQ(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldReadReplicasMode, v))
}

// ReadReplicasModeIn applies the In predicate on the "read_replicas_mode" field.
func ReadReplicasModeIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldReadReplicasMode, vs...))
}

// ReadReplicasModeNotIn applies the NotIn predicate on the "read_replicas_mode" field.
func ReadReplicasModeNotIn(vs ...int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldReadReplicasMode, vs...))
}

// ReadReplicasModeGT applies the GT predicate on the "read_replicas_mode" field.
func ReadReplicasModeGT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldReadReplicasMode, v))
}

// ReadReplicasModeGTE applies the GTE predicate on the "read_replicas_mode" field.
func ReadReplicasModeGTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldReadReplicasMode, v))
}

// ReadReplicasModeLT applies the LT predicate on the "read_replicas_mode" field.
func ReadReplicasModeLT(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldReadReplicasMode, v))
}

// ReadReplicasModeLTE applies the LTE predicate on the "read_replicas_mode" field.
func ReadReplicasModeLTE(v int32) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldReadReplicasMode, v))
}

// ReadReplicasModeIsNil applies the IsNil predicate on the "read_replicas_mode" field.
func ReadReplicasModeIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldReadReplicasMode))
}

// ReadReplicasModeNotNil applies the NotNil predicate on the "read_replicas_mode" field.
func ReadReplicasModeNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldReadReplicasMode))
}

// CustomerManagedKeyEQ applies the EQ predicate on the "customer_managed_key" field.
func CustomerManagedKeyEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldCustomerManagedKey, v))
}

// CustomerManagedKeyNEQ applies the NEQ predicate on the "customer_managed_key" field.
func CustomerManagedKeyNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldCustomerManagedKey, v))
}

// CustomerManagedKeyIn applies the In predicate on the "customer_managed_key" field.
func CustomerManagedKeyIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldCustomerManagedKey, vs...))
}

// CustomerManagedKeyNotIn applies the NotIn predicate on the "customer_managed_key" field.
func CustomerManagedKeyNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldCustomerManagedKey, vs...))
}

// CustomerManagedKeyGT applies the GT predicate on the "customer_managed_key" field.
func CustomerManagedKeyGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldCustomerManagedKey, v))
}

// CustomerManagedKeyGTE applies the GTE predicate on the "customer_managed_key" field.
func CustomerManagedKeyGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldCustomerManagedKey, v))
}

// CustomerManagedKeyLT applies the LT predicate on the "customer_managed_key" field.
func CustomerManagedKeyLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldCustomerManagedKey, v))
}

// CustomerManagedKeyLTE applies the LTE predicate on the "customer_managed_key" field.
func CustomerManagedKeyLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldCustomerManagedKey, v))
}

// CustomerManagedKeyContains applies the Contains predicate on the "customer_managed_key" field.
func CustomerManagedKeyContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldCustomerManagedKey, v))
}

// CustomerManagedKeyHasPrefix applies the HasPrefix predicate on the "customer_managed_key" field.
func CustomerManagedKeyHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldCustomerManagedKey, v))
}

// CustomerManagedKeyHasSuffix applies the HasSuffix predicate on the "customer_managed_key" field.
func CustomerManagedKeyHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldCustomerManagedKey, v))
}

// CustomerManagedKeyIsNil applies the IsNil predicate on the "customer_managed_key" field.
func CustomerManagedKeyIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldCustomerManagedKey))
}

// CustomerManagedKeyNotNil applies the NotNil predicate on the "customer_managed_key" field.
func CustomerManagedKeyNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldCustomerManagedKey))
}

// CustomerManagedKeyEqualFold applies the EqualFold predicate on the "customer_managed_key" field.
func CustomerManagedKeyEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldCustomerManagedKey, v))
}

// CustomerManagedKeyContainsFold applies the ContainsFold predicate on the "customer_managed_key" field.
func CustomerManagedKeyContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldCustomerManagedKey, v))
}

// PersistenceConfigJSONIsNil applies the IsNil predicate on the "persistence_config_json" field.
func PersistenceConfigJSONIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldPersistenceConfigJSON))
}

// PersistenceConfigJSONNotNil applies the NotNil predicate on the "persistence_config_json" field.
func PersistenceConfigJSONNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldPersistenceConfigJSON))
}

// SuspensionReasonsJSONIsNil applies the IsNil predicate on the "suspension_reasons_json" field.
func SuspensionReasonsJSONIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldSuspensionReasonsJSON))
}

// SuspensionReasonsJSONNotNil applies the NotNil predicate on the "suspension_reasons_json" field.
func SuspensionReasonsJSONNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldSuspensionReasonsJSON))
}

// MaintenanceVersionEQ applies the EQ predicate on the "maintenance_version" field.
func MaintenanceVersionEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldMaintenanceVersion, v))
}

// MaintenanceVersionNEQ applies the NEQ predicate on the "maintenance_version" field.
func MaintenanceVersionNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldMaintenanceVersion, v))
}

// MaintenanceVersionIn applies the In predicate on the "maintenance_version" field.
func MaintenanceVersionIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldMaintenanceVersion, vs...))
}

// MaintenanceVersionNotIn applies the NotIn predicate on the "maintenance_version" field.
func MaintenanceVersionNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldMaintenanceVersion, vs...))
}

// MaintenanceVersionGT applies the GT predicate on the "maintenance_version" field.
func MaintenanceVersionGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldMaintenanceVersion, v))
}

// MaintenanceVersionGTE applies the GTE predicate on the "maintenance_version" field.
func MaintenanceVersionGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldMaintenanceVersion, v))
}

// MaintenanceVersionLT applies the LT predicate on the "maintenance_version" field.
func MaintenanceVersionLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldMaintenanceVersion, v))
}

// MaintenanceVersionLTE applies the LTE predicate on the "maintenance_version" field.
func MaintenanceVersionLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldMaintenanceVersion, v))
}

// MaintenanceVersionContains applies the Contains predicate on the "maintenance_version" field.
func MaintenanceVersionContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldMaintenanceVersion, v))
}

// MaintenanceVersionHasPrefix applies the HasPrefix predicate on the "maintenance_version" field.
func MaintenanceVersionHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldMaintenanceVersion, v))
}

// MaintenanceVersionHasSuffix applies the HasSuffix predicate on the "maintenance_version" field.
func MaintenanceVersionHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldMaintenanceVersion, v))
}

// MaintenanceVersionIsNil applies the IsNil predicate on the "maintenance_version" field.
func MaintenanceVersionIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldMaintenanceVersion))
}

// MaintenanceVersionNotNil applies the NotNil predicate on the "maintenance_version" field.
func MaintenanceVersionNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldMaintenanceVersion))
}

// MaintenanceVersionEqualFold applies the EqualFold predicate on the "maintenance_version" field.
func MaintenanceVersionEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldMaintenanceVersion, v))
}

// MaintenanceVersionContainsFold applies the ContainsFold predicate on the "maintenance_version" field.
func MaintenanceVersionContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldMaintenanceVersion, v))
}

// AvailableMaintenanceVersionsJSONIsNil applies the IsNil predicate on the "available_maintenance_versions_json" field.
func AvailableMaintenanceVersionsJSONIsNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIsNull(FieldAvailableMaintenanceVersionsJSON))
}

// AvailableMaintenanceVersionsJSONNotNil applies the NotNil predicate on the "available_maintenance_versions_json" field.
func AvailableMaintenanceVersionsJSONNotNil() predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotNull(FieldAvailableMaintenanceVersionsJSON))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.FieldContainsFold(FieldProjectID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BronzeGCPRedisInstance) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BronzeGCPRedisInstance) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BronzeGCPRedisInstance) predicate.BronzeGCPRedisInstance {
	return predicate.BronzeGCPRedisInstance(sql.NotPredicates(p))
}
