-- Add new schema named "silver"
CREATE SCHEMA IF NOT EXISTS "silver";
-- Create "k8s_node_normalized" table
CREATE TABLE "silver"."k8s_node_normalized" (
  "resource_id" character varying NOT NULL,
  "provider" character varying NOT NULL,
  "is_base" boolean NOT NULL,
  "bronze_table" character varying NOT NULL,
  "bronze_resource_id" character varying NOT NULL,
  "node_name" character varying NULL,
  "cluster_name" character varying NULL,
  "node_pool" character varying NULL,
  "status" character varying NOT NULL,
  "provisioning" character varying NULL,
  "cloud_project" character varying NULL,
  "cloud_zone" character varying NULL,
  "cloud_machine_type" character varying NULL,
  "internal_ip" character varying NULL,
  "external_ip" character varying NULL,
  "merge_keys_json" jsonb NOT NULL,
  "collected_at" timestamptz NOT NULL,
  "first_collected_at" timestamptz NOT NULL,
  "normalized_at" timestamptz NOT NULL,
  PRIMARY KEY ("resource_id")
);
-- Create index "silverk8snodenormalized_provider" to table: "k8s_node_normalized"
CREATE INDEX "silverk8snodenormalized_provider" ON "silver"."k8s_node_normalized" ("provider");
-- Create index "silverk8snodenormalized_provider_bronze_resource_id" to table: "k8s_node_normalized"
CREATE UNIQUE INDEX "silverk8snodenormalized_provider_bronze_resource_id" ON "silver"."k8s_node_normalized" ("provider", "bronze_resource_id");
-- Create "k8s_nodes" table
CREATE TABLE "silver"."k8s_nodes" (
  "resource_id" character varying NOT NULL,
  "collected_at" timestamptz NOT NULL,
  "first_collected_at" timestamptz NOT NULL,
  "normalized_at" timestamptz NOT NULL,
  "node_name" character varying NOT NULL,
  "cluster_name" character varying NOT NULL,
  "node_pool" character varying NOT NULL,
  "status" character varying NOT NULL,
  "provisioning" character varying NULL,
  "cloud_project" character varying NULL,
  "cloud_zone" character varying NULL,
  "cloud_machine_type" character varying NULL,
  "internal_ip" character varying NULL,
  "external_ip" character varying NULL,
  PRIMARY KEY ("resource_id")
);
-- Create index "silverk8snode_cluster_name" to table: "k8s_nodes"
CREATE INDEX "silverk8snode_cluster_name" ON "silver"."k8s_nodes" ("cluster_name");
-- Create index "silverk8snode_collected_at" to table: "k8s_nodes"
CREATE INDEX "silverk8snode_collected_at" ON "silver"."k8s_nodes" ("collected_at");
-- Create "k8s_node_bronze_links" table
CREATE TABLE "silver"."k8s_node_bronze_links" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "provider" character varying NOT NULL,
  "bronze_table" character varying NOT NULL,
  "bronze_resource_id" character varying NOT NULL,
  "silver_k8s_node_bronze_links" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "k8s_node_bronze_links_k8s_nodes_bronze_links" FOREIGN KEY ("silver_k8s_node_bronze_links") REFERENCES "silver"."k8s_nodes" ("resource_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
