// Code generated by ent, DO NOT EDIT.

package compute

import (
	"context"
	"errors"
	"fmt"
	"time"

	"danny.vn/hotpot/pkg/storage/ent/greennode/compute/bronzehistorygreennodecomputesshkey"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BronzeHistoryGreenNodeComputeSSHKeyCreate is the builder for creating a BronzeHistoryGreenNodeComputeSSHKey entity.
type BronzeHistoryGreenNodeComputeSSHKeyCreate struct {
	config
	mutation *BronzeHistoryGreenNodeComputeSSHKeyMutation
	hooks    []Hook
}

// SetValidFrom sets the "valid_from" field.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetValidFrom(v time.Time) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	_c.mutation.SetValidFrom(v)
	return _c
}

// SetValidTo sets the "valid_to" field.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetValidTo(v time.Time) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	_c.mutation.SetValidTo(v)
	return _c
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetNillableValidTo(v *time.Time) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	if v != nil {
		_c.SetValidTo(*v)
	}
	return _c
}

// SetCollectedAt sets the "collected_at" field.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetCollectedAt(v time.Time) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	_c.mutation.SetCollectedAt(v)
	return _c
}

// SetFirstCollectedAt sets the "first_collected_at" field.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetFirstCollectedAt(v time.Time) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	_c.mutation.SetFirstCollectedAt(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetResourceID(v string) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetName(v string) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCreatedAtAPI sets the "created_at_api" field.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetCreatedAtAPI(v string) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	_c.mutation.SetCreatedAtAPI(v)
	return _c
}

// SetNillableCreatedAtAPI sets the "created_at_api" field if the given value is not nil.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetNillableCreatedAtAPI(v *string) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	if v != nil {
		_c.SetCreatedAtAPI(*v)
	}
	return _c
}

// SetPubKey sets the "pub_key" field.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetPubKey(v string) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	_c.mutation.SetPubKey(v)
	return _c
}

// SetNillablePubKey sets the "pub_key" field if the given value is not nil.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetNillablePubKey(v *string) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	if v != nil {
		_c.SetPubKey(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetStatus(v string) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetNillableStatus(v *string) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetRegion(v string) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetProjectID(v string) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SetID(v uint) *BronzeHistoryGreenNodeComputeSSHKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BronzeHistoryGreenNodeComputeSSHKeyMutation object of the builder.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) Mutation() *BronzeHistoryGreenNodeComputeSSHKeyMutation {
	return _c.mutation
}

// Save creates the BronzeHistoryGreenNodeComputeSSHKey in the database.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) Save(ctx context.Context) (*BronzeHistoryGreenNodeComputeSSHKey, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) SaveX(ctx context.Context) *BronzeHistoryGreenNodeComputeSSHKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) check() error {
	if _, ok := _c.mutation.ValidFrom(); !ok {
		return &ValidationError{Name: "valid_from", err: errors.New(`compute: missing required field "BronzeHistoryGreenNodeComputeSSHKey.valid_from"`)}
	}
	if _, ok := _c.mutation.CollectedAt(); !ok {
		return &ValidationError{Name: "collected_at", err: errors.New(`compute: missing required field "BronzeHistoryGreenNodeComputeSSHKey.collected_at"`)}
	}
	if _, ok := _c.mutation.FirstCollectedAt(); !ok {
		return &ValidationError{Name: "first_collected_at", err: errors.New(`compute: missing required field "BronzeHistoryGreenNodeComputeSSHKey.first_collected_at"`)}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`compute: missing required field "BronzeHistoryGreenNodeComputeSSHKey.resource_id"`)}
	}
	if v, ok := _c.mutation.ResourceID(); ok {
		if err := bronzehistorygreennodecomputesshkey.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`compute: validator failed for field "BronzeHistoryGreenNodeComputeSSHKey.resource_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`compute: missing required field "BronzeHistoryGreenNodeComputeSSHKey.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := bronzehistorygreennodecomputesshkey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`compute: validator failed for field "BronzeHistoryGreenNodeComputeSSHKey.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`compute: missing required field "BronzeHistoryGreenNodeComputeSSHKey.region"`)}
	}
	if v, ok := _c.mutation.Region(); ok {
		if err := bronzehistorygreennodecomputesshkey.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`compute: validator failed for field "BronzeHistoryGreenNodeComputeSSHKey.region": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`compute: missing required field "BronzeHistoryGreenNodeComputeSSHKey.project_id"`)}
	}
	if v, ok := _c.mutation.ProjectID(); ok {
		if err := bronzehistorygreennodecomputesshkey.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`compute: validator failed for field "BronzeHistoryGreenNodeComputeSSHKey.project_id": %w`, err)}
		}
	}
	return nil
}

func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) sqlSave(ctx context.Context) (*BronzeHistoryGreenNodeComputeSSHKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreate) createSpec() (*BronzeHistoryGreenNodeComputeSSHKey, *sqlgraph.CreateSpec) {
	var (
		_node = &BronzeHistoryGreenNodeComputeSSHKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bronzehistorygreennodecomputesshkey.Table, sqlgraph.NewFieldSpec(bronzehistorygreennodecomputesshkey.FieldID, field.TypeUint))
	)
	_spec.Schema = _c.schemaConfig.BronzeHistoryGreenNodeComputeSSHKey
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ValidFrom(); ok {
		_spec.SetField(bronzehistorygreennodecomputesshkey.FieldValidFrom, field.TypeTime, value)
		_node.ValidFrom = value
	}
	if value, ok := _c.mutation.ValidTo(); ok {
		_spec.SetField(bronzehistorygreennodecomputesshkey.FieldValidTo, field.TypeTime, value)
		_node.ValidTo = &value
	}
	if value, ok := _c.mutation.CollectedAt(); ok {
		_spec.SetField(bronzehistorygreennodecomputesshkey.FieldCollectedAt, field.TypeTime, value)
		_node.CollectedAt = value
	}
	if value, ok := _c.mutation.FirstCollectedAt(); ok {
		_spec.SetField(bronzehistorygreennodecomputesshkey.FieldFirstCollectedAt, field.TypeTime, value)
		_node.FirstCollectedAt = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(bronzehistorygreennodecomputesshkey.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(bronzehistorygreennodecomputesshkey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.CreatedAtAPI(); ok {
		_spec.SetField(bronzehistorygreennodecomputesshkey.FieldCreatedAtAPI, field.TypeString, value)
		_node.CreatedAtAPI = value
	}
	if value, ok := _c.mutation.PubKey(); ok {
		_spec.SetField(bronzehistorygreennodecomputesshkey.FieldPubKey, field.TypeString, value)
		_node.PubKey = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(bronzehistorygreennodecomputesshkey.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(bronzehistorygreennodecomputesshkey.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(bronzehistorygreennodecomputesshkey.FieldProjectID, field.TypeString, value)
		_node.ProjectID = value
	}
	return _node, _spec
}

// BronzeHistoryGreenNodeComputeSSHKeyCreateBulk is the builder for creating many BronzeHistoryGreenNodeComputeSSHKey entities in bulk.
type BronzeHistoryGreenNodeComputeSSHKeyCreateBulk struct {
	config
	err      error
	builders []*BronzeHistoryGreenNodeComputeSSHKeyCreate
}

// Save creates the BronzeHistoryGreenNodeComputeSSHKey entities in the database.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreateBulk) Save(ctx context.Context) ([]*BronzeHistoryGreenNodeComputeSSHKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BronzeHistoryGreenNodeComputeSSHKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BronzeHistoryGreenNodeComputeSSHKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreateBulk) SaveX(ctx context.Context) []*BronzeHistoryGreenNodeComputeSSHKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BronzeHistoryGreenNodeComputeSSHKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
