// Code generated by ent, DO NOT EDIT.

package s1

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dannyota/hotpot/pkg/storage/ent/s1/bronzehistorys1networkdiscovery"
	"github.com/dannyota/hotpot/pkg/storage/ent/s1/internal"
	"github.com/dannyota/hotpot/pkg/storage/ent/s1/predicate"
)

// BronzeHistoryS1NetworkDiscoveryQuery is the builder for querying BronzeHistoryS1NetworkDiscovery entities.
type BronzeHistoryS1NetworkDiscoveryQuery struct {
	config
	ctx        *QueryContext
	order      []bronzehistorys1networkdiscovery.OrderOption
	inters     []Interceptor
	predicates []predicate.BronzeHistoryS1NetworkDiscovery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BronzeHistoryS1NetworkDiscoveryQuery builder.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) Where(ps ...predicate.BronzeHistoryS1NetworkDiscovery) *BronzeHistoryS1NetworkDiscoveryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) Limit(limit int) *BronzeHistoryS1NetworkDiscoveryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) Offset(offset int) *BronzeHistoryS1NetworkDiscoveryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) Unique(unique bool) *BronzeHistoryS1NetworkDiscoveryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) Order(o ...bronzehistorys1networkdiscovery.OrderOption) *BronzeHistoryS1NetworkDiscoveryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first BronzeHistoryS1NetworkDiscovery entity from the query.
// Returns a *NotFoundError when no BronzeHistoryS1NetworkDiscovery was found.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) First(ctx context.Context) (*BronzeHistoryS1NetworkDiscovery, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bronzehistorys1networkdiscovery.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) FirstX(ctx context.Context) *BronzeHistoryS1NetworkDiscovery {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BronzeHistoryS1NetworkDiscovery ID from the query.
// Returns a *NotFoundError when no BronzeHistoryS1NetworkDiscovery ID was found.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) FirstID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bronzehistorys1networkdiscovery.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) FirstIDX(ctx context.Context) uint {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BronzeHistoryS1NetworkDiscovery entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BronzeHistoryS1NetworkDiscovery entity is found.
// Returns a *NotFoundError when no BronzeHistoryS1NetworkDiscovery entities are found.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) Only(ctx context.Context) (*BronzeHistoryS1NetworkDiscovery, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bronzehistorys1networkdiscovery.Label}
	default:
		return nil, &NotSingularError{bronzehistorys1networkdiscovery.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) OnlyX(ctx context.Context) *BronzeHistoryS1NetworkDiscovery {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BronzeHistoryS1NetworkDiscovery ID in the query.
// Returns a *NotSingularError when more than one BronzeHistoryS1NetworkDiscovery ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) OnlyID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bronzehistorys1networkdiscovery.Label}
	default:
		err = &NotSingularError{bronzehistorys1networkdiscovery.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) OnlyIDX(ctx context.Context) uint {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BronzeHistoryS1NetworkDiscoveries.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) All(ctx context.Context) ([]*BronzeHistoryS1NetworkDiscovery, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BronzeHistoryS1NetworkDiscovery, *BronzeHistoryS1NetworkDiscoveryQuery]()
	return withInterceptors[[]*BronzeHistoryS1NetworkDiscovery](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) AllX(ctx context.Context) []*BronzeHistoryS1NetworkDiscovery {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BronzeHistoryS1NetworkDiscovery IDs.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) IDs(ctx context.Context) (ids []uint, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(bronzehistorys1networkdiscovery.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) IDsX(ctx context.Context) []uint {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BronzeHistoryS1NetworkDiscoveryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("s1: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BronzeHistoryS1NetworkDiscoveryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) Clone() *BronzeHistoryS1NetworkDiscoveryQuery {
	if _q == nil {
		return nil
	}
	return &BronzeHistoryS1NetworkDiscoveryQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]bronzehistorys1networkdiscovery.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.BronzeHistoryS1NetworkDiscovery{}, _q.predicates...),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ValidFrom time.Time `json:"valid_from,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BronzeHistoryS1NetworkDiscovery.Query().
//		GroupBy(bronzehistorys1networkdiscovery.FieldValidFrom).
//		Aggregate(s1.Count()).
//		Scan(ctx, &v)
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) GroupBy(field string, fields ...string) *BronzeHistoryS1NetworkDiscoveryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BronzeHistoryS1NetworkDiscoveryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = bronzehistorys1networkdiscovery.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ValidFrom time.Time `json:"valid_from,omitempty"`
//	}
//
//	client.BronzeHistoryS1NetworkDiscovery.Query().
//		Select(bronzehistorys1networkdiscovery.FieldValidFrom).
//		Scan(ctx, &v)
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) Select(fields ...string) *BronzeHistoryS1NetworkDiscoverySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BronzeHistoryS1NetworkDiscoverySelect{BronzeHistoryS1NetworkDiscoveryQuery: _q}
	sbuild.label = bronzehistorys1networkdiscovery.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BronzeHistoryS1NetworkDiscoverySelect configured with the given aggregations.
func (_q *BronzeHistoryS1NetworkDiscoveryQuery) Aggregate(fns ...AggregateFunc) *BronzeHistoryS1NetworkDiscoverySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BronzeHistoryS1NetworkDiscoveryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("s1: uninitialized interceptor (forgotten import s1/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !bronzehistorys1networkdiscovery.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("s1: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BronzeHistoryS1NetworkDiscoveryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BronzeHistoryS1NetworkDiscovery, error) {
	var (
		nodes = []*BronzeHistoryS1NetworkDiscovery{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BronzeHistoryS1NetworkDiscovery).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BronzeHistoryS1NetworkDiscovery{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.BronzeHistoryS1NetworkDiscovery
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *BronzeHistoryS1NetworkDiscoveryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.BronzeHistoryS1NetworkDiscovery
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BronzeHistoryS1NetworkDiscoveryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(bronzehistorys1networkdiscovery.Table, bronzehistorys1networkdiscovery.Columns, sqlgraph.NewFieldSpec(bronzehistorys1networkdiscovery.FieldID, field.TypeUint))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bronzehistorys1networkdiscovery.FieldID)
		for i := range fields {
			if fields[i] != bronzehistorys1networkdiscovery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BronzeHistoryS1NetworkDiscoveryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(bronzehistorys1networkdiscovery.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = bronzehistorys1networkdiscovery.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.BronzeHistoryS1NetworkDiscovery)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BronzeHistoryS1NetworkDiscoveryGroupBy is the group-by builder for BronzeHistoryS1NetworkDiscovery entities.
type BronzeHistoryS1NetworkDiscoveryGroupBy struct {
	selector
	build *BronzeHistoryS1NetworkDiscoveryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BronzeHistoryS1NetworkDiscoveryGroupBy) Aggregate(fns ...AggregateFunc) *BronzeHistoryS1NetworkDiscoveryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BronzeHistoryS1NetworkDiscoveryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BronzeHistoryS1NetworkDiscoveryQuery, *BronzeHistoryS1NetworkDiscoveryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BronzeHistoryS1NetworkDiscoveryGroupBy) sqlScan(ctx context.Context, root *BronzeHistoryS1NetworkDiscoveryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BronzeHistoryS1NetworkDiscoverySelect is the builder for selecting fields of BronzeHistoryS1NetworkDiscovery entities.
type BronzeHistoryS1NetworkDiscoverySelect struct {
	*BronzeHistoryS1NetworkDiscoveryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BronzeHistoryS1NetworkDiscoverySelect) Aggregate(fns ...AggregateFunc) *BronzeHistoryS1NetworkDiscoverySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BronzeHistoryS1NetworkDiscoverySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BronzeHistoryS1NetworkDiscoveryQuery, *BronzeHistoryS1NetworkDiscoverySelect](ctx, _s.BronzeHistoryS1NetworkDiscoveryQuery, _s, _s.inters, v)
}

func (_s *BronzeHistoryS1NetworkDiscoverySelect) sqlScan(ctx context.Context, root *BronzeHistoryS1NetworkDiscoveryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
