name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run '...'
        2. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., v1.0.0 or commit hash
