// Code generated by entcgen. DO NOT EDIT.
package bigquery

// DefaultSchemaConfig returns the schema config mapping each type to its PG schema.
func DefaultSchemaConfig() SchemaConfig {
	return SchemaConfig{
		BronzeGCPBigQueryDataset:        "bronze",
		BronzeGCPBigQueryTable:          "bronze",
		BronzeHistoryGCPBigQueryDataset: "bronze_history",
		BronzeHistoryGCPBigQueryTable:   "bronze_history",
	}
}
