// Code generated by ent, DO NOT EDIT.

package bronzedodatabasefirewallrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dannyota/hotpot/pkg/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldContainsFold(FieldID, id))
}

// CollectedAt applies equality check predicate on the "collected_at" field. It's identical to CollectedAtEQ.
func CollectedAt(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldCollectedAt, v))
}

// FirstCollectedAt applies equality check predicate on the "first_collected_at" field. It's identical to FirstCollectedAtEQ.
func FirstCollectedAt(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldFirstCollectedAt, v))
}

// ClusterID applies equality check predicate on the "cluster_id" field. It's identical to ClusterIDEQ.
func ClusterID(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldClusterID, v))
}

// UUID applies equality check predicate on the "uuid" field. It's identical to UUIDEQ.
func UUID(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldUUID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldType, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldValue, v))
}

// APICreatedAt applies equality check predicate on the "api_created_at" field. It's identical to APICreatedAtEQ.
func APICreatedAt(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldAPICreatedAt, v))
}

// CollectedAtEQ applies the EQ predicate on the "collected_at" field.
func CollectedAtEQ(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldCollectedAt, v))
}

// CollectedAtNEQ applies the NEQ predicate on the "collected_at" field.
func CollectedAtNEQ(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNEQ(FieldCollectedAt, v))
}

// CollectedAtIn applies the In predicate on the "collected_at" field.
func CollectedAtIn(vs ...time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldIn(FieldCollectedAt, vs...))
}

// CollectedAtNotIn applies the NotIn predicate on the "collected_at" field.
func CollectedAtNotIn(vs ...time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNotIn(FieldCollectedAt, vs...))
}

// CollectedAtGT applies the GT predicate on the "collected_at" field.
func CollectedAtGT(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGT(FieldCollectedAt, v))
}

// CollectedAtGTE applies the GTE predicate on the "collected_at" field.
func CollectedAtGTE(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGTE(FieldCollectedAt, v))
}

// CollectedAtLT applies the LT predicate on the "collected_at" field.
func CollectedAtLT(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLT(FieldCollectedAt, v))
}

// CollectedAtLTE applies the LTE predicate on the "collected_at" field.
func CollectedAtLTE(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLTE(FieldCollectedAt, v))
}

// FirstCollectedAtEQ applies the EQ predicate on the "first_collected_at" field.
func FirstCollectedAtEQ(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldFirstCollectedAt, v))
}

// FirstCollectedAtNEQ applies the NEQ predicate on the "first_collected_at" field.
func FirstCollectedAtNEQ(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNEQ(FieldFirstCollectedAt, v))
}

// FirstCollectedAtIn applies the In predicate on the "first_collected_at" field.
func FirstCollectedAtIn(vs ...time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldIn(FieldFirstCollectedAt, vs...))
}

// FirstCollectedAtNotIn applies the NotIn predicate on the "first_collected_at" field.
func FirstCollectedAtNotIn(vs ...time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNotIn(FieldFirstCollectedAt, vs...))
}

// FirstCollectedAtGT applies the GT predicate on the "first_collected_at" field.
func FirstCollectedAtGT(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGT(FieldFirstCollectedAt, v))
}

// FirstCollectedAtGTE applies the GTE predicate on the "first_collected_at" field.
func FirstCollectedAtGTE(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGTE(FieldFirstCollectedAt, v))
}

// FirstCollectedAtLT applies the LT predicate on the "first_collected_at" field.
func FirstCollectedAtLT(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLT(FieldFirstCollectedAt, v))
}

// FirstCollectedAtLTE applies the LTE predicate on the "first_collected_at" field.
func FirstCollectedAtLTE(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLTE(FieldFirstCollectedAt, v))
}

// ClusterIDEQ applies the EQ predicate on the "cluster_id" field.
func ClusterIDEQ(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldClusterID, v))
}

// ClusterIDNEQ applies the NEQ predicate on the "cluster_id" field.
func ClusterIDNEQ(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNEQ(FieldClusterID, v))
}

// ClusterIDIn applies the In predicate on the "cluster_id" field.
func ClusterIDIn(vs ...string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldIn(FieldClusterID, vs...))
}

// ClusterIDNotIn applies the NotIn predicate on the "cluster_id" field.
func ClusterIDNotIn(vs ...string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNotIn(FieldClusterID, vs...))
}

// ClusterIDGT applies the GT predicate on the "cluster_id" field.
func ClusterIDGT(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGT(FieldClusterID, v))
}

// ClusterIDGTE applies the GTE predicate on the "cluster_id" field.
func ClusterIDGTE(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGTE(FieldClusterID, v))
}

// ClusterIDLT applies the LT predicate on the "cluster_id" field.
func ClusterIDLT(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLT(FieldClusterID, v))
}

// ClusterIDLTE applies the LTE predicate on the "cluster_id" field.
func ClusterIDLTE(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLTE(FieldClusterID, v))
}

// ClusterIDContains applies the Contains predicate on the "cluster_id" field.
func ClusterIDContains(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldContains(FieldClusterID, v))
}

// ClusterIDHasPrefix applies the HasPrefix predicate on the "cluster_id" field.
func ClusterIDHasPrefix(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldHasPrefix(FieldClusterID, v))
}

// ClusterIDHasSuffix applies the HasSuffix predicate on the "cluster_id" field.
func ClusterIDHasSuffix(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldHasSuffix(FieldClusterID, v))
}

// ClusterIDEqualFold applies the EqualFold predicate on the "cluster_id" field.
func ClusterIDEqualFold(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEqualFold(FieldClusterID, v))
}

// ClusterIDContainsFold applies the ContainsFold predicate on the "cluster_id" field.
func ClusterIDContainsFold(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldContainsFold(FieldClusterID, v))
}

// UUIDEQ applies the EQ predicate on the "uuid" field.
func UUIDEQ(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldUUID, v))
}

// UUIDNEQ applies the NEQ predicate on the "uuid" field.
func UUIDNEQ(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNEQ(FieldUUID, v))
}

// UUIDIn applies the In predicate on the "uuid" field.
func UUIDIn(vs ...string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldIn(FieldUUID, vs...))
}

// UUIDNotIn applies the NotIn predicate on the "uuid" field.
func UUIDNotIn(vs ...string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNotIn(FieldUUID, vs...))
}

// UUIDGT applies the GT predicate on the "uuid" field.
func UUIDGT(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGT(FieldUUID, v))
}

// UUIDGTE applies the GTE predicate on the "uuid" field.
func UUIDGTE(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGTE(FieldUUID, v))
}

// UUIDLT applies the LT predicate on the "uuid" field.
func UUIDLT(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLT(FieldUUID, v))
}

// UUIDLTE applies the LTE predicate on the "uuid" field.
func UUIDLTE(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLTE(FieldUUID, v))
}

// UUIDContains applies the Contains predicate on the "uuid" field.
func UUIDContains(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldContains(FieldUUID, v))
}

// UUIDHasPrefix applies the HasPrefix predicate on the "uuid" field.
func UUIDHasPrefix(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldHasPrefix(FieldUUID, v))
}

// UUIDHasSuffix applies the HasSuffix predicate on the "uuid" field.
func UUIDHasSuffix(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldHasSuffix(FieldUUID, v))
}

// UUIDEqualFold applies the EqualFold predicate on the "uuid" field.
func UUIDEqualFold(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEqualFold(FieldUUID, v))
}

// UUIDContainsFold applies the ContainsFold predicate on the "uuid" field.
func UUIDContainsFold(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldContainsFold(FieldUUID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldHasSuffix(FieldType, v))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNotNull(FieldType))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldContainsFold(FieldType, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldHasSuffix(FieldValue, v))
}

// ValueIsNil applies the IsNil predicate on the "value" field.
func ValueIsNil() predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldIsNull(FieldValue))
}

// ValueNotNil applies the NotNil predicate on the "value" field.
func ValueNotNil() predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNotNull(FieldValue))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldContainsFold(FieldValue, v))
}

// APICreatedAtEQ applies the EQ predicate on the "api_created_at" field.
func APICreatedAtEQ(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldEQ(FieldAPICreatedAt, v))
}

// APICreatedAtNEQ applies the NEQ predicate on the "api_created_at" field.
func APICreatedAtNEQ(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNEQ(FieldAPICreatedAt, v))
}

// APICreatedAtIn applies the In predicate on the "api_created_at" field.
func APICreatedAtIn(vs ...time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldIn(FieldAPICreatedAt, vs...))
}

// APICreatedAtNotIn applies the NotIn predicate on the "api_created_at" field.
func APICreatedAtNotIn(vs ...time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNotIn(FieldAPICreatedAt, vs...))
}

// APICreatedAtGT applies the GT predicate on the "api_created_at" field.
func APICreatedAtGT(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGT(FieldAPICreatedAt, v))
}

// APICreatedAtGTE applies the GTE predicate on the "api_created_at" field.
func APICreatedAtGTE(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldGTE(FieldAPICreatedAt, v))
}

// APICreatedAtLT applies the LT predicate on the "api_created_at" field.
func APICreatedAtLT(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLT(FieldAPICreatedAt, v))
}

// APICreatedAtLTE applies the LTE predicate on the "api_created_at" field.
func APICreatedAtLTE(v time.Time) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldLTE(FieldAPICreatedAt, v))
}

// APICreatedAtIsNil applies the IsNil predicate on the "api_created_at" field.
func APICreatedAtIsNil() predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldIsNull(FieldAPICreatedAt))
}

// APICreatedAtNotNil applies the NotNil predicate on the "api_created_at" field.
func APICreatedAtNotNil() predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.FieldNotNull(FieldAPICreatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BronzeDODatabaseFirewallRule) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BronzeDODatabaseFirewallRule) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BronzeDODatabaseFirewallRule) predicate.BronzeDODatabaseFirewallRule {
	return predicate.BronzeDODatabaseFirewallRule(sql.NotPredicates(p))
}
