// Code generated by ent, DO NOT EDIT.

package k8snode

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"danny.vn/hotpot/pkg/storage/ent/k8snode/internal"
	"danny.vn/hotpot/pkg/storage/ent/k8snode/inventoryk8snodenormalized"
	"danny.vn/hotpot/pkg/storage/ent/k8snode/predicate"
)

// InventoryK8sNodeNormalizedUpdate is the builder for updating InventoryK8sNodeNormalized entities.
type InventoryK8sNodeNormalizedUpdate struct {
	config
	hooks    []Hook
	mutation *InventoryK8sNodeNormalizedMutation
}

// Where appends a list predicates to the InventoryK8sNodeNormalizedUpdate builder.
func (_u *InventoryK8sNodeNormalizedUpdate) Where(ps ...predicate.InventoryK8sNodeNormalized) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetProvider(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableProvider(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetIsBase sets the "is_base" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetIsBase(v bool) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetIsBase(v)
	return _u
}

// SetNillableIsBase sets the "is_base" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableIsBase(v *bool) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetIsBase(*v)
	}
	return _u
}

// SetBronzeTable sets the "bronze_table" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetBronzeTable(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetBronzeTable(v)
	return _u
}

// SetNillableBronzeTable sets the "bronze_table" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableBronzeTable(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetBronzeTable(*v)
	}
	return _u
}

// SetBronzeResourceID sets the "bronze_resource_id" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetBronzeResourceID(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetBronzeResourceID(v)
	return _u
}

// SetNillableBronzeResourceID sets the "bronze_resource_id" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableBronzeResourceID(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetBronzeResourceID(*v)
	}
	return _u
}

// SetNodeName sets the "node_name" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNodeName(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetNodeName(v)
	return _u
}

// SetNillableNodeName sets the "node_name" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableNodeName(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetNodeName(*v)
	}
	return _u
}

// ClearNodeName clears the value of the "node_name" field.
func (_u *InventoryK8sNodeNormalizedUpdate) ClearNodeName() *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.ClearNodeName()
	return _u
}

// SetClusterName sets the "cluster_name" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetClusterName(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetClusterName(v)
	return _u
}

// SetNillableClusterName sets the "cluster_name" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableClusterName(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetClusterName(*v)
	}
	return _u
}

// ClearClusterName clears the value of the "cluster_name" field.
func (_u *InventoryK8sNodeNormalizedUpdate) ClearClusterName() *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.ClearClusterName()
	return _u
}

// SetNodePool sets the "node_pool" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNodePool(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetNodePool(v)
	return _u
}

// SetNillableNodePool sets the "node_pool" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableNodePool(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetNodePool(*v)
	}
	return _u
}

// ClearNodePool clears the value of the "node_pool" field.
func (_u *InventoryK8sNodeNormalizedUpdate) ClearNodePool() *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.ClearNodePool()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetStatus(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableStatus(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProvisioning sets the "provisioning" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetProvisioning(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetProvisioning(v)
	return _u
}

// SetNillableProvisioning sets the "provisioning" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableProvisioning(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetProvisioning(*v)
	}
	return _u
}

// ClearProvisioning clears the value of the "provisioning" field.
func (_u *InventoryK8sNodeNormalizedUpdate) ClearProvisioning() *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.ClearProvisioning()
	return _u
}

// SetCloudProject sets the "cloud_project" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetCloudProject(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetCloudProject(v)
	return _u
}

// SetNillableCloudProject sets the "cloud_project" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableCloudProject(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetCloudProject(*v)
	}
	return _u
}

// ClearCloudProject clears the value of the "cloud_project" field.
func (_u *InventoryK8sNodeNormalizedUpdate) ClearCloudProject() *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.ClearCloudProject()
	return _u
}

// SetCloudZone sets the "cloud_zone" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetCloudZone(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetCloudZone(v)
	return _u
}

// SetNillableCloudZone sets the "cloud_zone" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableCloudZone(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetCloudZone(*v)
	}
	return _u
}

// ClearCloudZone clears the value of the "cloud_zone" field.
func (_u *InventoryK8sNodeNormalizedUpdate) ClearCloudZone() *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.ClearCloudZone()
	return _u
}

// SetCloudMachineType sets the "cloud_machine_type" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetCloudMachineType(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetCloudMachineType(v)
	return _u
}

// SetNillableCloudMachineType sets the "cloud_machine_type" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableCloudMachineType(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetCloudMachineType(*v)
	}
	return _u
}

// ClearCloudMachineType clears the value of the "cloud_machine_type" field.
func (_u *InventoryK8sNodeNormalizedUpdate) ClearCloudMachineType() *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.ClearCloudMachineType()
	return _u
}

// SetInternalIP sets the "internal_ip" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetInternalIP(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetInternalIP(v)
	return _u
}

// SetNillableInternalIP sets the "internal_ip" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableInternalIP(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetInternalIP(*v)
	}
	return _u
}

// ClearInternalIP clears the value of the "internal_ip" field.
func (_u *InventoryK8sNodeNormalizedUpdate) ClearInternalIP() *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.ClearInternalIP()
	return _u
}

// SetExternalIP sets the "external_ip" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetExternalIP(v string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetExternalIP(v)
	return _u
}

// SetNillableExternalIP sets the "external_ip" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableExternalIP(v *string) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetExternalIP(*v)
	}
	return _u
}

// ClearExternalIP clears the value of the "external_ip" field.
func (_u *InventoryK8sNodeNormalizedUpdate) ClearExternalIP() *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.ClearExternalIP()
	return _u
}

// SetMergeKeysJSON sets the "merge_keys_json" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetMergeKeysJSON(v map[string][]string) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetMergeKeysJSON(v)
	return _u
}

// SetCollectedAt sets the "collected_at" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetCollectedAt(v time.Time) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetCollectedAt(v)
	return _u
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableCollectedAt(v *time.Time) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetCollectedAt(*v)
	}
	return _u
}

// SetFirstCollectedAt sets the "first_collected_at" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetFirstCollectedAt(v time.Time) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetFirstCollectedAt(v)
	return _u
}

// SetNillableFirstCollectedAt sets the "first_collected_at" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableFirstCollectedAt(v *time.Time) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetFirstCollectedAt(*v)
	}
	return _u
}

// SetNormalizedAt sets the "normalized_at" field.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNormalizedAt(v time.Time) *InventoryK8sNodeNormalizedUpdate {
	_u.mutation.SetNormalizedAt(v)
	return _u
}

// SetNillableNormalizedAt sets the "normalized_at" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdate) SetNillableNormalizedAt(v *time.Time) *InventoryK8sNodeNormalizedUpdate {
	if v != nil {
		_u.SetNormalizedAt(*v)
	}
	return _u
}

// Mutation returns the InventoryK8sNodeNormalizedMutation object of the builder.
func (_u *InventoryK8sNodeNormalizedUpdate) Mutation() *InventoryK8sNodeNormalizedMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InventoryK8sNodeNormalizedUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InventoryK8sNodeNormalizedUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InventoryK8sNodeNormalizedUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InventoryK8sNodeNormalizedUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InventoryK8sNodeNormalizedUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := inventoryk8snodenormalized.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`k8snode: validator failed for field "InventoryK8sNodeNormalized.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BronzeTable(); ok {
		if err := inventoryk8snodenormalized.BronzeTableValidator(v); err != nil {
			return &ValidationError{Name: "bronze_table", err: fmt.Errorf(`k8snode: validator failed for field "InventoryK8sNodeNormalized.bronze_table": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BronzeResourceID(); ok {
		if err := inventoryk8snodenormalized.BronzeResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "bronze_resource_id", err: fmt.Errorf(`k8snode: validator failed for field "InventoryK8sNodeNormalized.bronze_resource_id": %w`, err)}
		}
	}
	return nil
}

func (_u *InventoryK8sNodeNormalizedUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inventoryk8snodenormalized.Table, inventoryk8snodenormalized.Columns, sqlgraph.NewFieldSpec(inventoryk8snodenormalized.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsBase(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldIsBase, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BronzeTable(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldBronzeTable, field.TypeString, value)
	}
	if value, ok := _u.mutation.BronzeResourceID(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldBronzeResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeName(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldNodeName, field.TypeString, value)
	}
	if _u.mutation.NodeNameCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldNodeName, field.TypeString)
	}
	if value, ok := _u.mutation.ClusterName(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldClusterName, field.TypeString, value)
	}
	if _u.mutation.ClusterNameCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldClusterName, field.TypeString)
	}
	if value, ok := _u.mutation.NodePool(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldNodePool, field.TypeString, value)
	}
	if _u.mutation.NodePoolCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldNodePool, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provisioning(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldProvisioning, field.TypeString, value)
	}
	if _u.mutation.ProvisioningCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldProvisioning, field.TypeString)
	}
	if value, ok := _u.mutation.CloudProject(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldCloudProject, field.TypeString, value)
	}
	if _u.mutation.CloudProjectCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldCloudProject, field.TypeString)
	}
	if value, ok := _u.mutation.CloudZone(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldCloudZone, field.TypeString, value)
	}
	if _u.mutation.CloudZoneCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldCloudZone, field.TypeString)
	}
	if value, ok := _u.mutation.CloudMachineType(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldCloudMachineType, field.TypeString, value)
	}
	if _u.mutation.CloudMachineTypeCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldCloudMachineType, field.TypeString)
	}
	if value, ok := _u.mutation.InternalIP(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldInternalIP, field.TypeString, value)
	}
	if _u.mutation.InternalIPCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldInternalIP, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalIP(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldExternalIP, field.TypeString, value)
	}
	if _u.mutation.ExternalIPCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldExternalIP, field.TypeString)
	}
	if value, ok := _u.mutation.MergeKeysJSON(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldMergeKeysJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CollectedAt(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldCollectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FirstCollectedAt(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldFirstCollectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NormalizedAt(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldNormalizedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.InventoryK8sNodeNormalized
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inventoryk8snodenormalized.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InventoryK8sNodeNormalizedUpdateOne is the builder for updating a single InventoryK8sNodeNormalized entity.
type InventoryK8sNodeNormalizedUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InventoryK8sNodeNormalizedMutation
}

// SetProvider sets the "provider" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetProvider(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableProvider(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetIsBase sets the "is_base" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetIsBase(v bool) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetIsBase(v)
	return _u
}

// SetNillableIsBase sets the "is_base" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableIsBase(v *bool) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetIsBase(*v)
	}
	return _u
}

// SetBronzeTable sets the "bronze_table" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetBronzeTable(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetBronzeTable(v)
	return _u
}

// SetNillableBronzeTable sets the "bronze_table" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableBronzeTable(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetBronzeTable(*v)
	}
	return _u
}

// SetBronzeResourceID sets the "bronze_resource_id" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetBronzeResourceID(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetBronzeResourceID(v)
	return _u
}

// SetNillableBronzeResourceID sets the "bronze_resource_id" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableBronzeResourceID(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetBronzeResourceID(*v)
	}
	return _u
}

// SetNodeName sets the "node_name" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNodeName(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetNodeName(v)
	return _u
}

// SetNillableNodeName sets the "node_name" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableNodeName(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetNodeName(*v)
	}
	return _u
}

// ClearNodeName clears the value of the "node_name" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) ClearNodeName() *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.ClearNodeName()
	return _u
}

// SetClusterName sets the "cluster_name" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetClusterName(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetClusterName(v)
	return _u
}

// SetNillableClusterName sets the "cluster_name" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableClusterName(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetClusterName(*v)
	}
	return _u
}

// ClearClusterName clears the value of the "cluster_name" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) ClearClusterName() *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.ClearClusterName()
	return _u
}

// SetNodePool sets the "node_pool" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNodePool(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetNodePool(v)
	return _u
}

// SetNillableNodePool sets the "node_pool" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableNodePool(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetNodePool(*v)
	}
	return _u
}

// ClearNodePool clears the value of the "node_pool" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) ClearNodePool() *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.ClearNodePool()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetStatus(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableStatus(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProvisioning sets the "provisioning" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetProvisioning(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetProvisioning(v)
	return _u
}

// SetNillableProvisioning sets the "provisioning" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableProvisioning(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetProvisioning(*v)
	}
	return _u
}

// ClearProvisioning clears the value of the "provisioning" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) ClearProvisioning() *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.ClearProvisioning()
	return _u
}

// SetCloudProject sets the "cloud_project" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetCloudProject(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetCloudProject(v)
	return _u
}

// SetNillableCloudProject sets the "cloud_project" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableCloudProject(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetCloudProject(*v)
	}
	return _u
}

// ClearCloudProject clears the value of the "cloud_project" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) ClearCloudProject() *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.ClearCloudProject()
	return _u
}

// SetCloudZone sets the "cloud_zone" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetCloudZone(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetCloudZone(v)
	return _u
}

// SetNillableCloudZone sets the "cloud_zone" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableCloudZone(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetCloudZone(*v)
	}
	return _u
}

// ClearCloudZone clears the value of the "cloud_zone" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) ClearCloudZone() *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.ClearCloudZone()
	return _u
}

// SetCloudMachineType sets the "cloud_machine_type" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetCloudMachineType(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetCloudMachineType(v)
	return _u
}

// SetNillableCloudMachineType sets the "cloud_machine_type" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableCloudMachineType(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetCloudMachineType(*v)
	}
	return _u
}

// ClearCloudMachineType clears the value of the "cloud_machine_type" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) ClearCloudMachineType() *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.ClearCloudMachineType()
	return _u
}

// SetInternalIP sets the "internal_ip" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetInternalIP(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetInternalIP(v)
	return _u
}

// SetNillableInternalIP sets the "internal_ip" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableInternalIP(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetInternalIP(*v)
	}
	return _u
}

// ClearInternalIP clears the value of the "internal_ip" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) ClearInternalIP() *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.ClearInternalIP()
	return _u
}

// SetExternalIP sets the "external_ip" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetExternalIP(v string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetExternalIP(v)
	return _u
}

// SetNillableExternalIP sets the "external_ip" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableExternalIP(v *string) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetExternalIP(*v)
	}
	return _u
}

// ClearExternalIP clears the value of the "external_ip" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) ClearExternalIP() *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.ClearExternalIP()
	return _u
}

// SetMergeKeysJSON sets the "merge_keys_json" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetMergeKeysJSON(v map[string][]string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetMergeKeysJSON(v)
	return _u
}

// SetCollectedAt sets the "collected_at" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetCollectedAt(v time.Time) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetCollectedAt(v)
	return _u
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableCollectedAt(v *time.Time) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetCollectedAt(*v)
	}
	return _u
}

// SetFirstCollectedAt sets the "first_collected_at" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetFirstCollectedAt(v time.Time) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetFirstCollectedAt(v)
	return _u
}

// SetNillableFirstCollectedAt sets the "first_collected_at" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableFirstCollectedAt(v *time.Time) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetFirstCollectedAt(*v)
	}
	return _u
}

// SetNormalizedAt sets the "normalized_at" field.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNormalizedAt(v time.Time) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.SetNormalizedAt(v)
	return _u
}

// SetNillableNormalizedAt sets the "normalized_at" field if the given value is not nil.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SetNillableNormalizedAt(v *time.Time) *InventoryK8sNodeNormalizedUpdateOne {
	if v != nil {
		_u.SetNormalizedAt(*v)
	}
	return _u
}

// Mutation returns the InventoryK8sNodeNormalizedMutation object of the builder.
func (_u *InventoryK8sNodeNormalizedUpdateOne) Mutation() *InventoryK8sNodeNormalizedMutation {
	return _u.mutation
}

// Where appends a list predicates to the InventoryK8sNodeNormalizedUpdate builder.
func (_u *InventoryK8sNodeNormalizedUpdateOne) Where(ps ...predicate.InventoryK8sNodeNormalized) *InventoryK8sNodeNormalizedUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InventoryK8sNodeNormalizedUpdateOne) Select(field string, fields ...string) *InventoryK8sNodeNormalizedUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InventoryK8sNodeNormalized entity.
func (_u *InventoryK8sNodeNormalizedUpdateOne) Save(ctx context.Context) (*InventoryK8sNodeNormalized, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InventoryK8sNodeNormalizedUpdateOne) SaveX(ctx context.Context) *InventoryK8sNodeNormalized {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InventoryK8sNodeNormalizedUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InventoryK8sNodeNormalizedUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InventoryK8sNodeNormalizedUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := inventoryk8snodenormalized.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`k8snode: validator failed for field "InventoryK8sNodeNormalized.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BronzeTable(); ok {
		if err := inventoryk8snodenormalized.BronzeTableValidator(v); err != nil {
			return &ValidationError{Name: "bronze_table", err: fmt.Errorf(`k8snode: validator failed for field "InventoryK8sNodeNormalized.bronze_table": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BronzeResourceID(); ok {
		if err := inventoryk8snodenormalized.BronzeResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "bronze_resource_id", err: fmt.Errorf(`k8snode: validator failed for field "InventoryK8sNodeNormalized.bronze_resource_id": %w`, err)}
		}
	}
	return nil
}

func (_u *InventoryK8sNodeNormalizedUpdateOne) sqlSave(ctx context.Context) (_node *InventoryK8sNodeNormalized, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inventoryk8snodenormalized.Table, inventoryk8snodenormalized.Columns, sqlgraph.NewFieldSpec(inventoryk8snodenormalized.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`k8snode: missing "InventoryK8sNodeNormalized.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, inventoryk8snodenormalized.FieldID)
		for _, f := range fields {
			if !inventoryk8snodenormalized.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("k8snode: invalid field %q for query", f)}
			}
			if f != inventoryk8snodenormalized.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsBase(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldIsBase, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BronzeTable(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldBronzeTable, field.TypeString, value)
	}
	if value, ok := _u.mutation.BronzeResourceID(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldBronzeResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeName(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldNodeName, field.TypeString, value)
	}
	if _u.mutation.NodeNameCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldNodeName, field.TypeString)
	}
	if value, ok := _u.mutation.ClusterName(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldClusterName, field.TypeString, value)
	}
	if _u.mutation.ClusterNameCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldClusterName, field.TypeString)
	}
	if value, ok := _u.mutation.NodePool(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldNodePool, field.TypeString, value)
	}
	if _u.mutation.NodePoolCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldNodePool, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provisioning(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldProvisioning, field.TypeString, value)
	}
	if _u.mutation.ProvisioningCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldProvisioning, field.TypeString)
	}
	if value, ok := _u.mutation.CloudProject(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldCloudProject, field.TypeString, value)
	}
	if _u.mutation.CloudProjectCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldCloudProject, field.TypeString)
	}
	if value, ok := _u.mutation.CloudZone(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldCloudZone, field.TypeString, value)
	}
	if _u.mutation.CloudZoneCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldCloudZone, field.TypeString)
	}
	if value, ok := _u.mutation.CloudMachineType(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldCloudMachineType, field.TypeString, value)
	}
	if _u.mutation.CloudMachineTypeCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldCloudMachineType, field.TypeString)
	}
	if value, ok := _u.mutation.InternalIP(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldInternalIP, field.TypeString, value)
	}
	if _u.mutation.InternalIPCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldInternalIP, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalIP(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldExternalIP, field.TypeString, value)
	}
	if _u.mutation.ExternalIPCleared() {
		_spec.ClearField(inventoryk8snodenormalized.FieldExternalIP, field.TypeString)
	}
	if value, ok := _u.mutation.MergeKeysJSON(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldMergeKeysJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CollectedAt(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldCollectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FirstCollectedAt(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldFirstCollectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NormalizedAt(); ok {
		_spec.SetField(inventoryk8snodenormalized.FieldNormalizedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = _u.schemaConfig.InventoryK8sNodeNormalized
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &InventoryK8sNodeNormalized{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inventoryk8snodenormalized.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
