// Code generated by entcgen. DO NOT EDIT.
package apiendpoint

// DefaultSchemaConfig returns the schema config mapping each type to its PG schema.
func DefaultSchemaConfig() SchemaConfig {
	return SchemaConfig{
		InventoryApiEndpoint:           "silver",
		InventoryApiEndpointBronzeLink: "silver",
	}
}
