// Code generated by ent, DO NOT EDIT.

package bronzehistorygcpcomputeprojectmetadataitem

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the bronzehistorygcpcomputeprojectmetadataitem type in the database.
	Label = "bronze_history_gcp_compute_project_metadata_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHistoryID holds the string denoting the history_id field in the database.
	FieldHistoryID = "history_id"
	// FieldMetadataHistoryID holds the string denoting the metadata_history_id field in the database.
	FieldMetadataHistoryID = "metadata_history_id"
	// FieldValidFrom holds the string denoting the valid_from field in the database.
	FieldValidFrom = "valid_from"
	// FieldValidTo holds the string denoting the valid_to field in the database.
	FieldValidTo = "valid_to"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// Table holds the table name of the bronzehistorygcpcomputeprojectmetadataitem in the database.
	Table = "gcp_compute_project_metadata_items_history"
)

// Columns holds all SQL columns for bronzehistorygcpcomputeprojectmetadataitem fields.
var Columns = []string{
	FieldID,
	FieldHistoryID,
	FieldMetadataHistoryID,
	FieldValidFrom,
	FieldValidTo,
	FieldKey,
	FieldValue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
)

// OrderOption defines the ordering options for the BronzeHistoryGCPComputeProjectMetadataItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHistoryID orders the results by the history_id field.
func ByHistoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHistoryID, opts...).ToFunc()
}

// ByMetadataHistoryID orders the results by the metadata_history_id field.
func ByMetadataHistoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataHistoryID, opts...).ToFunc()
}

// ByValidFrom orders the results by the valid_from field.
func ByValidFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidFrom, opts...).ToFunc()
}

// ByValidTo orders the results by the valid_to field.
func ByValidTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidTo, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}
