// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dannyota/hotpot/pkg/storage/ent/bronzehistorygcpcontainerclustercondition"
)

// BronzeHistoryGCPContainerClusterCondition is the model entity for the BronzeHistoryGCPContainerClusterCondition schema.
type BronzeHistoryGCPContainerClusterCondition struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// HistoryID holds the value of the "history_id" field.
	HistoryID uint `json:"history_id,omitempty"`
	// Links to parent BronzeHistoryGCPContainerCluster
	ClusterHistoryID uint `json:"cluster_history_id,omitempty"`
	// ValidFrom holds the value of the "valid_from" field.
	ValidFrom time.Time `json:"valid_from,omitempty"`
	// ValidTo holds the value of the "valid_to" field.
	ValidTo *time.Time `json:"valid_to,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// CanonicalCode holds the value of the "canonical_code" field.
	CanonicalCode string `json:"canonical_code,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BronzeHistoryGCPContainerClusterCondition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bronzehistorygcpcontainerclustercondition.FieldID, bronzehistorygcpcontainerclustercondition.FieldHistoryID, bronzehistorygcpcontainerclustercondition.FieldClusterHistoryID:
			values[i] = new(sql.NullInt64)
		case bronzehistorygcpcontainerclustercondition.FieldCode, bronzehistorygcpcontainerclustercondition.FieldMessage, bronzehistorygcpcontainerclustercondition.FieldCanonicalCode:
			values[i] = new(sql.NullString)
		case bronzehistorygcpcontainerclustercondition.FieldValidFrom, bronzehistorygcpcontainerclustercondition.FieldValidTo:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BronzeHistoryGCPContainerClusterCondition fields.
func (_m *BronzeHistoryGCPContainerClusterCondition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bronzehistorygcpcontainerclustercondition.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case bronzehistorygcpcontainerclustercondition.FieldHistoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field history_id", values[i])
			} else if value.Valid {
				_m.HistoryID = uint(value.Int64)
			}
		case bronzehistorygcpcontainerclustercondition.FieldClusterHistoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cluster_history_id", values[i])
			} else if value.Valid {
				_m.ClusterHistoryID = uint(value.Int64)
			}
		case bronzehistorygcpcontainerclustercondition.FieldValidFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_from", values[i])
			} else if value.Valid {
				_m.ValidFrom = value.Time
			}
		case bronzehistorygcpcontainerclustercondition.FieldValidTo:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_to", values[i])
			} else if value.Valid {
				_m.ValidTo = new(time.Time)
				*_m.ValidTo = value.Time
			}
		case bronzehistorygcpcontainerclustercondition.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case bronzehistorygcpcontainerclustercondition.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case bronzehistorygcpcontainerclustercondition.FieldCanonicalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field canonical_code", values[i])
			} else if value.Valid {
				_m.CanonicalCode = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BronzeHistoryGCPContainerClusterCondition.
// This includes values selected through modifiers, order, etc.
func (_m *BronzeHistoryGCPContainerClusterCondition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BronzeHistoryGCPContainerClusterCondition.
// Note that you need to call BronzeHistoryGCPContainerClusterCondition.Unwrap() before calling this method if this BronzeHistoryGCPContainerClusterCondition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BronzeHistoryGCPContainerClusterCondition) Update() *BronzeHistoryGCPContainerClusterConditionUpdateOne {
	return NewBronzeHistoryGCPContainerClusterConditionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BronzeHistoryGCPContainerClusterCondition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BronzeHistoryGCPContainerClusterCondition) Unwrap() *BronzeHistoryGCPContainerClusterCondition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BronzeHistoryGCPContainerClusterCondition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BronzeHistoryGCPContainerClusterCondition) String() string {
	var builder strings.Builder
	builder.WriteString("BronzeHistoryGCPContainerClusterCondition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("history_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HistoryID))
	builder.WriteString(", ")
	builder.WriteString("cluster_history_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClusterHistoryID))
	builder.WriteString(", ")
	builder.WriteString("valid_from=")
	builder.WriteString(_m.ValidFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ValidTo; v != nil {
		builder.WriteString("valid_to=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("canonical_code=")
	builder.WriteString(_m.CanonicalCode)
	builder.WriteByte(')')
	return builder.String()
}

// BronzeHistoryGCPContainerClusterConditions is a parsable slice of BronzeHistoryGCPContainerClusterCondition.
type BronzeHistoryGCPContainerClusterConditions []*BronzeHistoryGCPContainerClusterCondition
