// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dannyota/hotpot/pkg/storage/ent/bronzehistorygcpcomputesubnetwork"
)

// BronzeHistoryGCPComputeSubnetwork is the model entity for the BronzeHistoryGCPComputeSubnetwork schema.
type BronzeHistoryGCPComputeSubnetwork struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Start of validity period
	ValidFrom time.Time `json:"valid_from,omitempty"`
	// End of validity period (null = current)
	ValidTo *time.Time `json:"valid_to,omitempty"`
	// Timestamp when this snapshot was collected
	CollectedAt time.Time `json:"collected_at,omitempty"`
	// Timestamp when this asset was first collected
	FirstCollectedAt time.Time `json:"first_collected_at,omitempty"`
	// HistoryID holds the value of the "history_id" field.
	HistoryID uint `json:"history_id,omitempty"`
	// Link to bronze subnetwork by resource_id
	ResourceID string `json:"resource_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// SelfLink holds the value of the "self_link" field.
	SelfLink string `json:"self_link,omitempty"`
	// CreationTimestamp holds the value of the "creation_timestamp" field.
	CreationTimestamp string `json:"creation_timestamp,omitempty"`
	// Network holds the value of the "network" field.
	Network string `json:"network,omitempty"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// IPCidrRange holds the value of the "ip_cidr_range" field.
	IPCidrRange string `json:"ip_cidr_range,omitempty"`
	// GatewayAddress holds the value of the "gateway_address" field.
	GatewayAddress string `json:"gateway_address,omitempty"`
	// Purpose holds the value of the "purpose" field.
	Purpose string `json:"purpose,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// PrivateIPGoogleAccess holds the value of the "private_ip_google_access" field.
	PrivateIPGoogleAccess bool `json:"private_ip_google_access,omitempty"`
	// PrivateIpv6GoogleAccess holds the value of the "private_ipv6_google_access" field.
	PrivateIpv6GoogleAccess string `json:"private_ipv6_google_access,omitempty"`
	// StackType holds the value of the "stack_type" field.
	StackType string `json:"stack_type,omitempty"`
	// Ipv6AccessType holds the value of the "ipv6_access_type" field.
	Ipv6AccessType string `json:"ipv6_access_type,omitempty"`
	// InternalIpv6Prefix holds the value of the "internal_ipv6_prefix" field.
	InternalIpv6Prefix string `json:"internal_ipv6_prefix,omitempty"`
	// ExternalIpv6Prefix holds the value of the "external_ipv6_prefix" field.
	ExternalIpv6Prefix string `json:"external_ipv6_prefix,omitempty"`
	// LogConfigJSON holds the value of the "log_config_json" field.
	LogConfigJSON json.RawMessage `json:"log_config_json,omitempty"`
	// Fingerprint holds the value of the "fingerprint" field.
	Fingerprint string `json:"fingerprint,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID    string `json:"project_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BronzeHistoryGCPComputeSubnetwork) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bronzehistorygcpcomputesubnetwork.FieldLogConfigJSON:
			values[i] = new([]byte)
		case bronzehistorygcpcomputesubnetwork.FieldPrivateIPGoogleAccess:
			values[i] = new(sql.NullBool)
		case bronzehistorygcpcomputesubnetwork.FieldID, bronzehistorygcpcomputesubnetwork.FieldHistoryID:
			values[i] = new(sql.NullInt64)
		case bronzehistorygcpcomputesubnetwork.FieldResourceID, bronzehistorygcpcomputesubnetwork.FieldName, bronzehistorygcpcomputesubnetwork.FieldDescription, bronzehistorygcpcomputesubnetwork.FieldSelfLink, bronzehistorygcpcomputesubnetwork.FieldCreationTimestamp, bronzehistorygcpcomputesubnetwork.FieldNetwork, bronzehistorygcpcomputesubnetwork.FieldRegion, bronzehistorygcpcomputesubnetwork.FieldIPCidrRange, bronzehistorygcpcomputesubnetwork.FieldGatewayAddress, bronzehistorygcpcomputesubnetwork.FieldPurpose, bronzehistorygcpcomputesubnetwork.FieldRole, bronzehistorygcpcomputesubnetwork.FieldPrivateIpv6GoogleAccess, bronzehistorygcpcomputesubnetwork.FieldStackType, bronzehistorygcpcomputesubnetwork.FieldIpv6AccessType, bronzehistorygcpcomputesubnetwork.FieldInternalIpv6Prefix, bronzehistorygcpcomputesubnetwork.FieldExternalIpv6Prefix, bronzehistorygcpcomputesubnetwork.FieldFingerprint, bronzehistorygcpcomputesubnetwork.FieldProjectID:
			values[i] = new(sql.NullString)
		case bronzehistorygcpcomputesubnetwork.FieldValidFrom, bronzehistorygcpcomputesubnetwork.FieldValidTo, bronzehistorygcpcomputesubnetwork.FieldCollectedAt, bronzehistorygcpcomputesubnetwork.FieldFirstCollectedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BronzeHistoryGCPComputeSubnetwork fields.
func (_m *BronzeHistoryGCPComputeSubnetwork) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bronzehistorygcpcomputesubnetwork.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case bronzehistorygcpcomputesubnetwork.FieldValidFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_from", values[i])
			} else if value.Valid {
				_m.ValidFrom = value.Time
			}
		case bronzehistorygcpcomputesubnetwork.FieldValidTo:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_to", values[i])
			} else if value.Valid {
				_m.ValidTo = new(time.Time)
				*_m.ValidTo = value.Time
			}
		case bronzehistorygcpcomputesubnetwork.FieldCollectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field collected_at", values[i])
			} else if value.Valid {
				_m.CollectedAt = value.Time
			}
		case bronzehistorygcpcomputesubnetwork.FieldFirstCollectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_collected_at", values[i])
			} else if value.Valid {
				_m.FirstCollectedAt = value.Time
			}
		case bronzehistorygcpcomputesubnetwork.FieldHistoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field history_id", values[i])
			} else if value.Valid {
				_m.HistoryID = uint(value.Int64)
			}
		case bronzehistorygcpcomputesubnetwork.FieldResourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				_m.ResourceID = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldSelfLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field self_link", values[i])
			} else if value.Valid {
				_m.SelfLink = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldCreationTimestamp:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creation_timestamp", values[i])
			} else if value.Valid {
				_m.CreationTimestamp = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldNetwork:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network", values[i])
			} else if value.Valid {
				_m.Network = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldIPCidrRange:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_cidr_range", values[i])
			} else if value.Valid {
				_m.IPCidrRange = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldGatewayAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_address", values[i])
			} else if value.Valid {
				_m.GatewayAddress = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldPurpose:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field purpose", values[i])
			} else if value.Valid {
				_m.Purpose = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldPrivateIPGoogleAccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field private_ip_google_access", values[i])
			} else if value.Valid {
				_m.PrivateIPGoogleAccess = value.Bool
			}
		case bronzehistorygcpcomputesubnetwork.FieldPrivateIpv6GoogleAccess:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field private_ipv6_google_access", values[i])
			} else if value.Valid {
				_m.PrivateIpv6GoogleAccess = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldStackType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stack_type", values[i])
			} else if value.Valid {
				_m.StackType = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldIpv6AccessType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ipv6_access_type", values[i])
			} else if value.Valid {
				_m.Ipv6AccessType = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldInternalIpv6Prefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field internal_ipv6_prefix", values[i])
			} else if value.Valid {
				_m.InternalIpv6Prefix = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldExternalIpv6Prefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_ipv6_prefix", values[i])
			} else if value.Valid {
				_m.ExternalIpv6Prefix = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldLogConfigJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field log_config_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.LogConfigJSON); err != nil {
					return fmt.Errorf("unmarshal field log_config_json: %w", err)
				}
			}
		case bronzehistorygcpcomputesubnetwork.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				_m.Fingerprint = value.String
			}
		case bronzehistorygcpcomputesubnetwork.FieldProjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BronzeHistoryGCPComputeSubnetwork.
// This includes values selected through modifiers, order, etc.
func (_m *BronzeHistoryGCPComputeSubnetwork) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BronzeHistoryGCPComputeSubnetwork.
// Note that you need to call BronzeHistoryGCPComputeSubnetwork.Unwrap() before calling this method if this BronzeHistoryGCPComputeSubnetwork
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BronzeHistoryGCPComputeSubnetwork) Update() *BronzeHistoryGCPComputeSubnetworkUpdateOne {
	return NewBronzeHistoryGCPComputeSubnetworkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BronzeHistoryGCPComputeSubnetwork entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BronzeHistoryGCPComputeSubnetwork) Unwrap() *BronzeHistoryGCPComputeSubnetwork {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BronzeHistoryGCPComputeSubnetwork is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BronzeHistoryGCPComputeSubnetwork) String() string {
	var builder strings.Builder
	builder.WriteString("BronzeHistoryGCPComputeSubnetwork(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("valid_from=")
	builder.WriteString(_m.ValidFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ValidTo; v != nil {
		builder.WriteString("valid_to=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("collected_at=")
	builder.WriteString(_m.CollectedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("first_collected_at=")
	builder.WriteString(_m.FirstCollectedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("history_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HistoryID))
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(_m.ResourceID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("self_link=")
	builder.WriteString(_m.SelfLink)
	builder.WriteString(", ")
	builder.WriteString("creation_timestamp=")
	builder.WriteString(_m.CreationTimestamp)
	builder.WriteString(", ")
	builder.WriteString("network=")
	builder.WriteString(_m.Network)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("ip_cidr_range=")
	builder.WriteString(_m.IPCidrRange)
	builder.WriteString(", ")
	builder.WriteString("gateway_address=")
	builder.WriteString(_m.GatewayAddress)
	builder.WriteString(", ")
	builder.WriteString("purpose=")
	builder.WriteString(_m.Purpose)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("private_ip_google_access=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrivateIPGoogleAccess))
	builder.WriteString(", ")
	builder.WriteString("private_ipv6_google_access=")
	builder.WriteString(_m.PrivateIpv6GoogleAccess)
	builder.WriteString(", ")
	builder.WriteString("stack_type=")
	builder.WriteString(_m.StackType)
	builder.WriteString(", ")
	builder.WriteString("ipv6_access_type=")
	builder.WriteString(_m.Ipv6AccessType)
	builder.WriteString(", ")
	builder.WriteString("internal_ipv6_prefix=")
	builder.WriteString(_m.InternalIpv6Prefix)
	builder.WriteString(", ")
	builder.WriteString("external_ipv6_prefix=")
	builder.WriteString(_m.ExternalIpv6Prefix)
	builder.WriteString(", ")
	builder.WriteString("log_config_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.LogConfigJSON))
	builder.WriteString(", ")
	builder.WriteString("fingerprint=")
	builder.WriteString(_m.Fingerprint)
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(_m.ProjectID)
	builder.WriteByte(')')
	return builder.String()
}

// BronzeHistoryGCPComputeSubnetworks is a parsable slice of BronzeHistoryGCPComputeSubnetwork.
type BronzeHistoryGCPComputeSubnetworks []*BronzeHistoryGCPComputeSubnetwork
