// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dannyota/hotpot/pkg/storage/ent/bronzeawsec2instancetag"
	"github.com/dannyota/hotpot/pkg/storage/ent/internal"
	"github.com/dannyota/hotpot/pkg/storage/ent/predicate"
)

// BronzeAWSEC2InstanceTagDelete is the builder for deleting a BronzeAWSEC2InstanceTag entity.
type BronzeAWSEC2InstanceTagDelete struct {
	config
	hooks    []Hook
	mutation *BronzeAWSEC2InstanceTagMutation
}

// Where appends a list predicates to the BronzeAWSEC2InstanceTagDelete builder.
func (_d *BronzeAWSEC2InstanceTagDelete) Where(ps ...predicate.BronzeAWSEC2InstanceTag) *BronzeAWSEC2InstanceTagDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BronzeAWSEC2InstanceTagDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BronzeAWSEC2InstanceTagDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BronzeAWSEC2InstanceTagDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bronzeawsec2instancetag.Table, sqlgraph.NewFieldSpec(bronzeawsec2instancetag.FieldID, field.TypeInt))
	_spec.Node.Schema = _d.schemaConfig.BronzeAWSEC2InstanceTag
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BronzeAWSEC2InstanceTagDeleteOne is the builder for deleting a single BronzeAWSEC2InstanceTag entity.
type BronzeAWSEC2InstanceTagDeleteOne struct {
	_d *BronzeAWSEC2InstanceTagDelete
}

// Where appends a list predicates to the BronzeAWSEC2InstanceTagDelete builder.
func (_d *BronzeAWSEC2InstanceTagDeleteOne) Where(ps ...predicate.BronzeAWSEC2InstanceTag) *BronzeAWSEC2InstanceTagDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BronzeAWSEC2InstanceTagDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bronzeawsec2instancetag.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BronzeAWSEC2InstanceTagDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
