// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dannyota/hotpot/pkg/storage/ent/bronzegcpcomputerouter"
)

// BronzeGCPComputeRouter is the model entity for the BronzeGCPComputeRouter schema.
type BronzeGCPComputeRouter struct {
	config `json:"-"`
	// ID of the ent.
	// GCP API ID, used as primary key for linking
	ID string `json:"id,omitempty"`
	// CollectedAt holds the value of the "collected_at" field.
	CollectedAt time.Time `json:"collected_at,omitempty"`
	// FirstCollectedAt holds the value of the "first_collected_at" field.
	FirstCollectedAt time.Time `json:"first_collected_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// SelfLink holds the value of the "self_link" field.
	SelfLink string `json:"self_link,omitempty"`
	// CreationTimestamp holds the value of the "creation_timestamp" field.
	CreationTimestamp string `json:"creation_timestamp,omitempty"`
	// Network URL this router belongs to
	Network string `json:"network,omitempty"`
	// Region URL
	Region string `json:"region,omitempty"`
	// BGP autonomous system number
	BgpAsn int `json:"bgp_asn,omitempty"`
	// DEFAULT or CUSTOM
	BgpAdvertiseMode string `json:"bgp_advertise_mode,omitempty"`
	// BgpAdvertisedGroupsJSON holds the value of the "bgp_advertised_groups_json" field.
	BgpAdvertisedGroupsJSON json.RawMessage `json:"bgp_advertised_groups_json,omitempty"`
	// BgpAdvertisedIPRangesJSON holds the value of the "bgp_advertised_ip_ranges_json" field.
	BgpAdvertisedIPRangesJSON json.RawMessage `json:"bgp_advertised_ip_ranges_json,omitempty"`
	// BGP keepalive interval in seconds
	BgpKeepaliveInterval int `json:"bgp_keepalive_interval,omitempty"`
	// BgpPeersJSON holds the value of the "bgp_peers_json" field.
	BgpPeersJSON json.RawMessage `json:"bgp_peers_json,omitempty"`
	// InterfacesJSON holds the value of the "interfaces_json" field.
	InterfacesJSON json.RawMessage `json:"interfaces_json,omitempty"`
	// NatsJSON holds the value of the "nats_json" field.
	NatsJSON json.RawMessage `json:"nats_json,omitempty"`
	// EncryptedInterconnectRouter holds the value of the "encrypted_interconnect_router" field.
	EncryptedInterconnectRouter bool `json:"encrypted_interconnect_router,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID    string `json:"project_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BronzeGCPComputeRouter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bronzegcpcomputerouter.FieldBgpAdvertisedGroupsJSON, bronzegcpcomputerouter.FieldBgpAdvertisedIPRangesJSON, bronzegcpcomputerouter.FieldBgpPeersJSON, bronzegcpcomputerouter.FieldInterfacesJSON, bronzegcpcomputerouter.FieldNatsJSON:
			values[i] = new([]byte)
		case bronzegcpcomputerouter.FieldEncryptedInterconnectRouter:
			values[i] = new(sql.NullBool)
		case bronzegcpcomputerouter.FieldBgpAsn, bronzegcpcomputerouter.FieldBgpKeepaliveInterval:
			values[i] = new(sql.NullInt64)
		case bronzegcpcomputerouter.FieldID, bronzegcpcomputerouter.FieldName, bronzegcpcomputerouter.FieldDescription, bronzegcpcomputerouter.FieldSelfLink, bronzegcpcomputerouter.FieldCreationTimestamp, bronzegcpcomputerouter.FieldNetwork, bronzegcpcomputerouter.FieldRegion, bronzegcpcomputerouter.FieldBgpAdvertiseMode, bronzegcpcomputerouter.FieldProjectID:
			values[i] = new(sql.NullString)
		case bronzegcpcomputerouter.FieldCollectedAt, bronzegcpcomputerouter.FieldFirstCollectedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BronzeGCPComputeRouter fields.
func (_m *BronzeGCPComputeRouter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bronzegcpcomputerouter.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case bronzegcpcomputerouter.FieldCollectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field collected_at", values[i])
			} else if value.Valid {
				_m.CollectedAt = value.Time
			}
		case bronzegcpcomputerouter.FieldFirstCollectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_collected_at", values[i])
			} else if value.Valid {
				_m.FirstCollectedAt = value.Time
			}
		case bronzegcpcomputerouter.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case bronzegcpcomputerouter.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case bronzegcpcomputerouter.FieldSelfLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field self_link", values[i])
			} else if value.Valid {
				_m.SelfLink = value.String
			}
		case bronzegcpcomputerouter.FieldCreationTimestamp:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creation_timestamp", values[i])
			} else if value.Valid {
				_m.CreationTimestamp = value.String
			}
		case bronzegcpcomputerouter.FieldNetwork:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network", values[i])
			} else if value.Valid {
				_m.Network = value.String
			}
		case bronzegcpcomputerouter.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case bronzegcpcomputerouter.FieldBgpAsn:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bgp_asn", values[i])
			} else if value.Valid {
				_m.BgpAsn = int(value.Int64)
			}
		case bronzegcpcomputerouter.FieldBgpAdvertiseMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bgp_advertise_mode", values[i])
			} else if value.Valid {
				_m.BgpAdvertiseMode = value.String
			}
		case bronzegcpcomputerouter.FieldBgpAdvertisedGroupsJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field bgp_advertised_groups_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BgpAdvertisedGroupsJSON); err != nil {
					return fmt.Errorf("unmarshal field bgp_advertised_groups_json: %w", err)
				}
			}
		case bronzegcpcomputerouter.FieldBgpAdvertisedIPRangesJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field bgp_advertised_ip_ranges_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BgpAdvertisedIPRangesJSON); err != nil {
					return fmt.Errorf("unmarshal field bgp_advertised_ip_ranges_json: %w", err)
				}
			}
		case bronzegcpcomputerouter.FieldBgpKeepaliveInterval:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bgp_keepalive_interval", values[i])
			} else if value.Valid {
				_m.BgpKeepaliveInterval = int(value.Int64)
			}
		case bronzegcpcomputerouter.FieldBgpPeersJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field bgp_peers_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BgpPeersJSON); err != nil {
					return fmt.Errorf("unmarshal field bgp_peers_json: %w", err)
				}
			}
		case bronzegcpcomputerouter.FieldInterfacesJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field interfaces_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.InterfacesJSON); err != nil {
					return fmt.Errorf("unmarshal field interfaces_json: %w", err)
				}
			}
		case bronzegcpcomputerouter.FieldNatsJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field nats_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NatsJSON); err != nil {
					return fmt.Errorf("unmarshal field nats_json: %w", err)
				}
			}
		case bronzegcpcomputerouter.FieldEncryptedInterconnectRouter:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_interconnect_router", values[i])
			} else if value.Valid {
				_m.EncryptedInterconnectRouter = value.Bool
			}
		case bronzegcpcomputerouter.FieldProjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BronzeGCPComputeRouter.
// This includes values selected through modifiers, order, etc.
func (_m *BronzeGCPComputeRouter) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BronzeGCPComputeRouter.
// Note that you need to call BronzeGCPComputeRouter.Unwrap() before calling this method if this BronzeGCPComputeRouter
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BronzeGCPComputeRouter) Update() *BronzeGCPComputeRouterUpdateOne {
	return NewBronzeGCPComputeRouterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BronzeGCPComputeRouter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BronzeGCPComputeRouter) Unwrap() *BronzeGCPComputeRouter {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BronzeGCPComputeRouter is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BronzeGCPComputeRouter) String() string {
	var builder strings.Builder
	builder.WriteString("BronzeGCPComputeRouter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("collected_at=")
	builder.WriteString(_m.CollectedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("first_collected_at=")
	builder.WriteString(_m.FirstCollectedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("self_link=")
	builder.WriteString(_m.SelfLink)
	builder.WriteString(", ")
	builder.WriteString("creation_timestamp=")
	builder.WriteString(_m.CreationTimestamp)
	builder.WriteString(", ")
	builder.WriteString("network=")
	builder.WriteString(_m.Network)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("bgp_asn=")
	builder.WriteString(fmt.Sprintf("%v", _m.BgpAsn))
	builder.WriteString(", ")
	builder.WriteString("bgp_advertise_mode=")
	builder.WriteString(_m.BgpAdvertiseMode)
	builder.WriteString(", ")
	builder.WriteString("bgp_advertised_groups_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.BgpAdvertisedGroupsJSON))
	builder.WriteString(", ")
	builder.WriteString("bgp_advertised_ip_ranges_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.BgpAdvertisedIPRangesJSON))
	builder.WriteString(", ")
	builder.WriteString("bgp_keepalive_interval=")
	builder.WriteString(fmt.Sprintf("%v", _m.BgpKeepaliveInterval))
	builder.WriteString(", ")
	builder.WriteString("bgp_peers_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.BgpPeersJSON))
	builder.WriteString(", ")
	builder.WriteString("interfaces_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.InterfacesJSON))
	builder.WriteString(", ")
	builder.WriteString("nats_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.NatsJSON))
	builder.WriteString(", ")
	builder.WriteString("encrypted_interconnect_router=")
	builder.WriteString(fmt.Sprintf("%v", _m.EncryptedInterconnectRouter))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(_m.ProjectID)
	builder.WriteByte(')')
	return builder.String()
}

// BronzeGCPComputeRouters is a parsable slice of BronzeGCPComputeRouter.
type BronzeGCPComputeRouters []*BronzeGCPComputeRouter
