// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dannyota/hotpot/pkg/storage/ent/bronzegcpaccesscontextmanageraccesslevel"
	"github.com/dannyota/hotpot/pkg/storage/ent/bronzegcpaccesscontextmanageraccesspolicy"
	"github.com/dannyota/hotpot/pkg/storage/ent/bronzegcpaccesscontextmanagerserviceperimeter"
	"github.com/dannyota/hotpot/pkg/storage/ent/internal"
	"github.com/dannyota/hotpot/pkg/storage/ent/predicate"
)

// BronzeGCPAccessContextManagerAccessPolicyQuery is the builder for querying BronzeGCPAccessContextManagerAccessPolicy entities.
type BronzeGCPAccessContextManagerAccessPolicyQuery struct {
	config
	ctx                   *QueryContext
	order                 []bronzegcpaccesscontextmanageraccesspolicy.OrderOption
	inters                []Interceptor
	predicates            []predicate.BronzeGCPAccessContextManagerAccessPolicy
	withAccessLevels      *BronzeGCPAccessContextManagerAccessLevelQuery
	withServicePerimeters *BronzeGCPAccessContextManagerServicePerimeterQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BronzeGCPAccessContextManagerAccessPolicyQuery builder.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) Where(ps ...predicate.BronzeGCPAccessContextManagerAccessPolicy) *BronzeGCPAccessContextManagerAccessPolicyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) Limit(limit int) *BronzeGCPAccessContextManagerAccessPolicyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) Offset(offset int) *BronzeGCPAccessContextManagerAccessPolicyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) Unique(unique bool) *BronzeGCPAccessContextManagerAccessPolicyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) Order(o ...bronzegcpaccesscontextmanageraccesspolicy.OrderOption) *BronzeGCPAccessContextManagerAccessPolicyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAccessLevels chains the current query on the "access_levels" edge.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) QueryAccessLevels() *BronzeGCPAccessContextManagerAccessLevelQuery {
	query := (&BronzeGCPAccessContextManagerAccessLevelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bronzegcpaccesscontextmanageraccesspolicy.Table, bronzegcpaccesscontextmanageraccesspolicy.FieldID, selector),
			sqlgraph.To(bronzegcpaccesscontextmanageraccesslevel.Table, bronzegcpaccesscontextmanageraccesslevel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bronzegcpaccesscontextmanageraccesspolicy.AccessLevelsTable, bronzegcpaccesscontextmanageraccesspolicy.AccessLevelsColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.BronzeGCPAccessContextManagerAccessLevel
		step.Edge.Schema = schemaConfig.BronzeGCPAccessContextManagerAccessLevel
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryServicePerimeters chains the current query on the "service_perimeters" edge.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) QueryServicePerimeters() *BronzeGCPAccessContextManagerServicePerimeterQuery {
	query := (&BronzeGCPAccessContextManagerServicePerimeterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bronzegcpaccesscontextmanageraccesspolicy.Table, bronzegcpaccesscontextmanageraccesspolicy.FieldID, selector),
			sqlgraph.To(bronzegcpaccesscontextmanagerserviceperimeter.Table, bronzegcpaccesscontextmanagerserviceperimeter.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bronzegcpaccesscontextmanageraccesspolicy.ServicePerimetersTable, bronzegcpaccesscontextmanageraccesspolicy.ServicePerimetersColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.BronzeGCPAccessContextManagerServicePerimeter
		step.Edge.Schema = schemaConfig.BronzeGCPAccessContextManagerServicePerimeter
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BronzeGCPAccessContextManagerAccessPolicy entity from the query.
// Returns a *NotFoundError when no BronzeGCPAccessContextManagerAccessPolicy was found.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) First(ctx context.Context) (*BronzeGCPAccessContextManagerAccessPolicy, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bronzegcpaccesscontextmanageraccesspolicy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) FirstX(ctx context.Context) *BronzeGCPAccessContextManagerAccessPolicy {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BronzeGCPAccessContextManagerAccessPolicy ID from the query.
// Returns a *NotFoundError when no BronzeGCPAccessContextManagerAccessPolicy ID was found.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bronzegcpaccesscontextmanageraccesspolicy.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BronzeGCPAccessContextManagerAccessPolicy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BronzeGCPAccessContextManagerAccessPolicy entity is found.
// Returns a *NotFoundError when no BronzeGCPAccessContextManagerAccessPolicy entities are found.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) Only(ctx context.Context) (*BronzeGCPAccessContextManagerAccessPolicy, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bronzegcpaccesscontextmanageraccesspolicy.Label}
	default:
		return nil, &NotSingularError{bronzegcpaccesscontextmanageraccesspolicy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) OnlyX(ctx context.Context) *BronzeGCPAccessContextManagerAccessPolicy {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BronzeGCPAccessContextManagerAccessPolicy ID in the query.
// Returns a *NotSingularError when more than one BronzeGCPAccessContextManagerAccessPolicy ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bronzegcpaccesscontextmanageraccesspolicy.Label}
	default:
		err = &NotSingularError{bronzegcpaccesscontextmanageraccesspolicy.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BronzeGCPAccessContextManagerAccessPolicies.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) All(ctx context.Context) ([]*BronzeGCPAccessContextManagerAccessPolicy, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BronzeGCPAccessContextManagerAccessPolicy, *BronzeGCPAccessContextManagerAccessPolicyQuery]()
	return withInterceptors[[]*BronzeGCPAccessContextManagerAccessPolicy](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) AllX(ctx context.Context) []*BronzeGCPAccessContextManagerAccessPolicy {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BronzeGCPAccessContextManagerAccessPolicy IDs.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(bronzegcpaccesscontextmanageraccesspolicy.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BronzeGCPAccessContextManagerAccessPolicyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BronzeGCPAccessContextManagerAccessPolicyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) Clone() *BronzeGCPAccessContextManagerAccessPolicyQuery {
	if _q == nil {
		return nil
	}
	return &BronzeGCPAccessContextManagerAccessPolicyQuery{
		config:                _q.config,
		ctx:                   _q.ctx.Clone(),
		order:                 append([]bronzegcpaccesscontextmanageraccesspolicy.OrderOption{}, _q.order...),
		inters:                append([]Interceptor{}, _q.inters...),
		predicates:            append([]predicate.BronzeGCPAccessContextManagerAccessPolicy{}, _q.predicates...),
		withAccessLevels:      _q.withAccessLevels.Clone(),
		withServicePerimeters: _q.withServicePerimeters.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAccessLevels tells the query-builder to eager-load the nodes that are connected to
// the "access_levels" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) WithAccessLevels(opts ...func(*BronzeGCPAccessContextManagerAccessLevelQuery)) *BronzeGCPAccessContextManagerAccessPolicyQuery {
	query := (&BronzeGCPAccessContextManagerAccessLevelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAccessLevels = query
	return _q
}

// WithServicePerimeters tells the query-builder to eager-load the nodes that are connected to
// the "service_perimeters" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) WithServicePerimeters(opts ...func(*BronzeGCPAccessContextManagerServicePerimeterQuery)) *BronzeGCPAccessContextManagerAccessPolicyQuery {
	query := (&BronzeGCPAccessContextManagerServicePerimeterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withServicePerimeters = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CollectedAt time.Time `json:"collected_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BronzeGCPAccessContextManagerAccessPolicy.Query().
//		GroupBy(bronzegcpaccesscontextmanageraccesspolicy.FieldCollectedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) GroupBy(field string, fields ...string) *BronzeGCPAccessContextManagerAccessPolicyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BronzeGCPAccessContextManagerAccessPolicyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = bronzegcpaccesscontextmanageraccesspolicy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CollectedAt time.Time `json:"collected_at,omitempty"`
//	}
//
//	client.BronzeGCPAccessContextManagerAccessPolicy.Query().
//		Select(bronzegcpaccesscontextmanageraccesspolicy.FieldCollectedAt).
//		Scan(ctx, &v)
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) Select(fields ...string) *BronzeGCPAccessContextManagerAccessPolicySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BronzeGCPAccessContextManagerAccessPolicySelect{BronzeGCPAccessContextManagerAccessPolicyQuery: _q}
	sbuild.label = bronzegcpaccesscontextmanageraccesspolicy.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BronzeGCPAccessContextManagerAccessPolicySelect configured with the given aggregations.
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) Aggregate(fns ...AggregateFunc) *BronzeGCPAccessContextManagerAccessPolicySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !bronzegcpaccesscontextmanageraccesspolicy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BronzeGCPAccessContextManagerAccessPolicy, error) {
	var (
		nodes       = []*BronzeGCPAccessContextManagerAccessPolicy{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withAccessLevels != nil,
			_q.withServicePerimeters != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BronzeGCPAccessContextManagerAccessPolicy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BronzeGCPAccessContextManagerAccessPolicy{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.BronzeGCPAccessContextManagerAccessPolicy
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAccessLevels; query != nil {
		if err := _q.loadAccessLevels(ctx, query, nodes,
			func(n *BronzeGCPAccessContextManagerAccessPolicy) {
				n.Edges.AccessLevels = []*BronzeGCPAccessContextManagerAccessLevel{}
			},
			func(n *BronzeGCPAccessContextManagerAccessPolicy, e *BronzeGCPAccessContextManagerAccessLevel) {
				n.Edges.AccessLevels = append(n.Edges.AccessLevels, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withServicePerimeters; query != nil {
		if err := _q.loadServicePerimeters(ctx, query, nodes,
			func(n *BronzeGCPAccessContextManagerAccessPolicy) {
				n.Edges.ServicePerimeters = []*BronzeGCPAccessContextManagerServicePerimeter{}
			},
			func(n *BronzeGCPAccessContextManagerAccessPolicy, e *BronzeGCPAccessContextManagerServicePerimeter) {
				n.Edges.ServicePerimeters = append(n.Edges.ServicePerimeters, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) loadAccessLevels(ctx context.Context, query *BronzeGCPAccessContextManagerAccessLevelQuery, nodes []*BronzeGCPAccessContextManagerAccessPolicy, init func(*BronzeGCPAccessContextManagerAccessPolicy), assign func(*BronzeGCPAccessContextManagerAccessPolicy, *BronzeGCPAccessContextManagerAccessLevel)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*BronzeGCPAccessContextManagerAccessPolicy)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.BronzeGCPAccessContextManagerAccessLevel(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(bronzegcpaccesscontextmanageraccesspolicy.AccessLevelsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.bronze_gcp_access_context_manager_access_policy_access_levels
		if fk == nil {
			return fmt.Errorf(`foreign-key "bronze_gcp_access_context_manager_access_policy_access_levels" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "bronze_gcp_access_context_manager_access_policy_access_levels" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) loadServicePerimeters(ctx context.Context, query *BronzeGCPAccessContextManagerServicePerimeterQuery, nodes []*BronzeGCPAccessContextManagerAccessPolicy, init func(*BronzeGCPAccessContextManagerAccessPolicy), assign func(*BronzeGCPAccessContextManagerAccessPolicy, *BronzeGCPAccessContextManagerServicePerimeter)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*BronzeGCPAccessContextManagerAccessPolicy)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.BronzeGCPAccessContextManagerServicePerimeter(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(bronzegcpaccesscontextmanageraccesspolicy.ServicePerimetersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.bronze_gcp_access_context_manager_access_policy_service_perimeters
		if fk == nil {
			return fmt.Errorf(`foreign-key "bronze_gcp_access_context_manager_access_policy_service_perimeters" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "bronze_gcp_access_context_manager_access_policy_service_perimeters" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.BronzeGCPAccessContextManagerAccessPolicy
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(bronzegcpaccesscontextmanageraccesspolicy.Table, bronzegcpaccesscontextmanageraccesspolicy.Columns, sqlgraph.NewFieldSpec(bronzegcpaccesscontextmanageraccesspolicy.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bronzegcpaccesscontextmanageraccesspolicy.FieldID)
		for i := range fields {
			if fields[i] != bronzegcpaccesscontextmanageraccesspolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BronzeGCPAccessContextManagerAccessPolicyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(bronzegcpaccesscontextmanageraccesspolicy.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = bronzegcpaccesscontextmanageraccesspolicy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.BronzeGCPAccessContextManagerAccessPolicy)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BronzeGCPAccessContextManagerAccessPolicyGroupBy is the group-by builder for BronzeGCPAccessContextManagerAccessPolicy entities.
type BronzeGCPAccessContextManagerAccessPolicyGroupBy struct {
	selector
	build *BronzeGCPAccessContextManagerAccessPolicyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BronzeGCPAccessContextManagerAccessPolicyGroupBy) Aggregate(fns ...AggregateFunc) *BronzeGCPAccessContextManagerAccessPolicyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BronzeGCPAccessContextManagerAccessPolicyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BronzeGCPAccessContextManagerAccessPolicyQuery, *BronzeGCPAccessContextManagerAccessPolicyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BronzeGCPAccessContextManagerAccessPolicyGroupBy) sqlScan(ctx context.Context, root *BronzeGCPAccessContextManagerAccessPolicyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BronzeGCPAccessContextManagerAccessPolicySelect is the builder for selecting fields of BronzeGCPAccessContextManagerAccessPolicy entities.
type BronzeGCPAccessContextManagerAccessPolicySelect struct {
	*BronzeGCPAccessContextManagerAccessPolicyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BronzeGCPAccessContextManagerAccessPolicySelect) Aggregate(fns ...AggregateFunc) *BronzeGCPAccessContextManagerAccessPolicySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BronzeGCPAccessContextManagerAccessPolicySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BronzeGCPAccessContextManagerAccessPolicyQuery, *BronzeGCPAccessContextManagerAccessPolicySelect](ctx, _s.BronzeGCPAccessContextManagerAccessPolicyQuery, _s, _s.inters, v)
}

func (_s *BronzeGCPAccessContextManagerAccessPolicySelect) sqlScan(ctx context.Context, root *BronzeGCPAccessContextManagerAccessPolicyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
