// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dannyota/hotpot/pkg/storage/ent/bronzedodatabasebackup"
	"github.com/dannyota/hotpot/pkg/storage/ent/internal"
	"github.com/dannyota/hotpot/pkg/storage/ent/predicate"
)

// BronzeDODatabaseBackupUpdate is the builder for updating BronzeDODatabaseBackup entities.
type BronzeDODatabaseBackupUpdate struct {
	config
	hooks    []Hook
	mutation *BronzeDODatabaseBackupMutation
}

// Where appends a list predicates to the BronzeDODatabaseBackupUpdate builder.
func (_u *BronzeDODatabaseBackupUpdate) Where(ps ...predicate.BronzeDODatabaseBackup) *BronzeDODatabaseBackupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCollectedAt sets the "collected_at" field.
func (_u *BronzeDODatabaseBackupUpdate) SetCollectedAt(v time.Time) *BronzeDODatabaseBackupUpdate {
	_u.mutation.SetCollectedAt(v)
	return _u
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_u *BronzeDODatabaseBackupUpdate) SetNillableCollectedAt(v *time.Time) *BronzeDODatabaseBackupUpdate {
	if v != nil {
		_u.SetCollectedAt(*v)
	}
	return _u
}

// SetClusterID sets the "cluster_id" field.
func (_u *BronzeDODatabaseBackupUpdate) SetClusterID(v string) *BronzeDODatabaseBackupUpdate {
	_u.mutation.SetClusterID(v)
	return _u
}

// SetNillableClusterID sets the "cluster_id" field if the given value is not nil.
func (_u *BronzeDODatabaseBackupUpdate) SetNillableClusterID(v *string) *BronzeDODatabaseBackupUpdate {
	if v != nil {
		_u.SetClusterID(*v)
	}
	return _u
}

// SetSizeGigabytes sets the "size_gigabytes" field.
func (_u *BronzeDODatabaseBackupUpdate) SetSizeGigabytes(v float64) *BronzeDODatabaseBackupUpdate {
	_u.mutation.ResetSizeGigabytes()
	_u.mutation.SetSizeGigabytes(v)
	return _u
}

// SetNillableSizeGigabytes sets the "size_gigabytes" field if the given value is not nil.
func (_u *BronzeDODatabaseBackupUpdate) SetNillableSizeGigabytes(v *float64) *BronzeDODatabaseBackupUpdate {
	if v != nil {
		_u.SetSizeGigabytes(*v)
	}
	return _u
}

// AddSizeGigabytes adds value to the "size_gigabytes" field.
func (_u *BronzeDODatabaseBackupUpdate) AddSizeGigabytes(v float64) *BronzeDODatabaseBackupUpdate {
	_u.mutation.AddSizeGigabytes(v)
	return _u
}

// SetAPICreatedAt sets the "api_created_at" field.
func (_u *BronzeDODatabaseBackupUpdate) SetAPICreatedAt(v time.Time) *BronzeDODatabaseBackupUpdate {
	_u.mutation.SetAPICreatedAt(v)
	return _u
}

// SetNillableAPICreatedAt sets the "api_created_at" field if the given value is not nil.
func (_u *BronzeDODatabaseBackupUpdate) SetNillableAPICreatedAt(v *time.Time) *BronzeDODatabaseBackupUpdate {
	if v != nil {
		_u.SetAPICreatedAt(*v)
	}
	return _u
}

// ClearAPICreatedAt clears the value of the "api_created_at" field.
func (_u *BronzeDODatabaseBackupUpdate) ClearAPICreatedAt() *BronzeDODatabaseBackupUpdate {
	_u.mutation.ClearAPICreatedAt()
	return _u
}

// Mutation returns the BronzeDODatabaseBackupMutation object of the builder.
func (_u *BronzeDODatabaseBackupUpdate) Mutation() *BronzeDODatabaseBackupMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BronzeDODatabaseBackupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BronzeDODatabaseBackupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BronzeDODatabaseBackupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BronzeDODatabaseBackupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BronzeDODatabaseBackupUpdate) check() error {
	if v, ok := _u.mutation.ClusterID(); ok {
		if err := bronzedodatabasebackup.ClusterIDValidator(v); err != nil {
			return &ValidationError{Name: "cluster_id", err: fmt.Errorf(`ent: validator failed for field "BronzeDODatabaseBackup.cluster_id": %w`, err)}
		}
	}
	return nil
}

func (_u *BronzeDODatabaseBackupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bronzedodatabasebackup.Table, bronzedodatabasebackup.Columns, sqlgraph.NewFieldSpec(bronzedodatabasebackup.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CollectedAt(); ok {
		_spec.SetField(bronzedodatabasebackup.FieldCollectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClusterID(); ok {
		_spec.SetField(bronzedodatabasebackup.FieldClusterID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeGigabytes(); ok {
		_spec.SetField(bronzedodatabasebackup.FieldSizeGigabytes, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSizeGigabytes(); ok {
		_spec.AddField(bronzedodatabasebackup.FieldSizeGigabytes, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.APICreatedAt(); ok {
		_spec.SetField(bronzedodatabasebackup.FieldAPICreatedAt, field.TypeTime, value)
	}
	if _u.mutation.APICreatedAtCleared() {
		_spec.ClearField(bronzedodatabasebackup.FieldAPICreatedAt, field.TypeTime)
	}
	_spec.Node.Schema = _u.schemaConfig.BronzeDODatabaseBackup
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bronzedodatabasebackup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BronzeDODatabaseBackupUpdateOne is the builder for updating a single BronzeDODatabaseBackup entity.
type BronzeDODatabaseBackupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BronzeDODatabaseBackupMutation
}

// SetCollectedAt sets the "collected_at" field.
func (_u *BronzeDODatabaseBackupUpdateOne) SetCollectedAt(v time.Time) *BronzeDODatabaseBackupUpdateOne {
	_u.mutation.SetCollectedAt(v)
	return _u
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_u *BronzeDODatabaseBackupUpdateOne) SetNillableCollectedAt(v *time.Time) *BronzeDODatabaseBackupUpdateOne {
	if v != nil {
		_u.SetCollectedAt(*v)
	}
	return _u
}

// SetClusterID sets the "cluster_id" field.
func (_u *BronzeDODatabaseBackupUpdateOne) SetClusterID(v string) *BronzeDODatabaseBackupUpdateOne {
	_u.mutation.SetClusterID(v)
	return _u
}

// SetNillableClusterID sets the "cluster_id" field if the given value is not nil.
func (_u *BronzeDODatabaseBackupUpdateOne) SetNillableClusterID(v *string) *BronzeDODatabaseBackupUpdateOne {
	if v != nil {
		_u.SetClusterID(*v)
	}
	return _u
}

// SetSizeGigabytes sets the "size_gigabytes" field.
func (_u *BronzeDODatabaseBackupUpdateOne) SetSizeGigabytes(v float64) *BronzeDODatabaseBackupUpdateOne {
	_u.mutation.ResetSizeGigabytes()
	_u.mutation.SetSizeGigabytes(v)
	return _u
}

// SetNillableSizeGigabytes sets the "size_gigabytes" field if the given value is not nil.
func (_u *BronzeDODatabaseBackupUpdateOne) SetNillableSizeGigabytes(v *float64) *BronzeDODatabaseBackupUpdateOne {
	if v != nil {
		_u.SetSizeGigabytes(*v)
	}
	return _u
}

// AddSizeGigabytes adds value to the "size_gigabytes" field.
func (_u *BronzeDODatabaseBackupUpdateOne) AddSizeGigabytes(v float64) *BronzeDODatabaseBackupUpdateOne {
	_u.mutation.AddSizeGigabytes(v)
	return _u
}

// SetAPICreatedAt sets the "api_created_at" field.
func (_u *BronzeDODatabaseBackupUpdateOne) SetAPICreatedAt(v time.Time) *BronzeDODatabaseBackupUpdateOne {
	_u.mutation.SetAPICreatedAt(v)
	return _u
}

// SetNillableAPICreatedAt sets the "api_created_at" field if the given value is not nil.
func (_u *BronzeDODatabaseBackupUpdateOne) SetNillableAPICreatedAt(v *time.Time) *BronzeDODatabaseBackupUpdateOne {
	if v != nil {
		_u.SetAPICreatedAt(*v)
	}
	return _u
}

// ClearAPICreatedAt clears the value of the "api_created_at" field.
func (_u *BronzeDODatabaseBackupUpdateOne) ClearAPICreatedAt() *BronzeDODatabaseBackupUpdateOne {
	_u.mutation.ClearAPICreatedAt()
	return _u
}

// Mutation returns the BronzeDODatabaseBackupMutation object of the builder.
func (_u *BronzeDODatabaseBackupUpdateOne) Mutation() *BronzeDODatabaseBackupMutation {
	return _u.mutation
}

// Where appends a list predicates to the BronzeDODatabaseBackupUpdate builder.
func (_u *BronzeDODatabaseBackupUpdateOne) Where(ps ...predicate.BronzeDODatabaseBackup) *BronzeDODatabaseBackupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BronzeDODatabaseBackupUpdateOne) Select(field string, fields ...string) *BronzeDODatabaseBackupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BronzeDODatabaseBackup entity.
func (_u *BronzeDODatabaseBackupUpdateOne) Save(ctx context.Context) (*BronzeDODatabaseBackup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BronzeDODatabaseBackupUpdateOne) SaveX(ctx context.Context) *BronzeDODatabaseBackup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BronzeDODatabaseBackupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BronzeDODatabaseBackupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BronzeDODatabaseBackupUpdateOne) check() error {
	if v, ok := _u.mutation.ClusterID(); ok {
		if err := bronzedodatabasebackup.ClusterIDValidator(v); err != nil {
			return &ValidationError{Name: "cluster_id", err: fmt.Errorf(`ent: validator failed for field "BronzeDODatabaseBackup.cluster_id": %w`, err)}
		}
	}
	return nil
}

func (_u *BronzeDODatabaseBackupUpdateOne) sqlSave(ctx context.Context) (_node *BronzeDODatabaseBackup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bronzedodatabasebackup.Table, bronzedodatabasebackup.Columns, sqlgraph.NewFieldSpec(bronzedodatabasebackup.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BronzeDODatabaseBackup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bronzedodatabasebackup.FieldID)
		for _, f := range fields {
			if !bronzedodatabasebackup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bronzedodatabasebackup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CollectedAt(); ok {
		_spec.SetField(bronzedodatabasebackup.FieldCollectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClusterID(); ok {
		_spec.SetField(bronzedodatabasebackup.FieldClusterID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeGigabytes(); ok {
		_spec.SetField(bronzedodatabasebackup.FieldSizeGigabytes, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSizeGigabytes(); ok {
		_spec.AddField(bronzedodatabasebackup.FieldSizeGigabytes, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.APICreatedAt(); ok {
		_spec.SetField(bronzedodatabasebackup.FieldAPICreatedAt, field.TypeTime, value)
	}
	if _u.mutation.APICreatedAtCleared() {
		_spec.ClearField(bronzedodatabasebackup.FieldAPICreatedAt, field.TypeTime)
	}
	_spec.Node.Schema = _u.schemaConfig.BronzeDODatabaseBackup
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &BronzeDODatabaseBackup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bronzedodatabasebackup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
