// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dannyota/hotpot/pkg/storage/ent/bronzehistorygcpdnsmanagedzonelabel"
)

// BronzeHistoryGCPDNSManagedZoneLabelCreate is the builder for creating a BronzeHistoryGCPDNSManagedZoneLabel entity.
type BronzeHistoryGCPDNSManagedZoneLabelCreate struct {
	config
	mutation *BronzeHistoryGCPDNSManagedZoneLabelMutation
	hooks    []Hook
}

// SetHistoryID sets the "history_id" field.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) SetHistoryID(v uint) *BronzeHistoryGCPDNSManagedZoneLabelCreate {
	_c.mutation.SetHistoryID(v)
	return _c
}

// SetManagedZoneHistoryID sets the "managed_zone_history_id" field.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) SetManagedZoneHistoryID(v uint) *BronzeHistoryGCPDNSManagedZoneLabelCreate {
	_c.mutation.SetManagedZoneHistoryID(v)
	return _c
}

// SetValidFrom sets the "valid_from" field.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) SetValidFrom(v time.Time) *BronzeHistoryGCPDNSManagedZoneLabelCreate {
	_c.mutation.SetValidFrom(v)
	return _c
}

// SetValidTo sets the "valid_to" field.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) SetValidTo(v time.Time) *BronzeHistoryGCPDNSManagedZoneLabelCreate {
	_c.mutation.SetValidTo(v)
	return _c
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) SetNillableValidTo(v *time.Time) *BronzeHistoryGCPDNSManagedZoneLabelCreate {
	if v != nil {
		_c.SetValidTo(*v)
	}
	return _c
}

// SetKey sets the "key" field.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) SetKey(v string) *BronzeHistoryGCPDNSManagedZoneLabelCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) SetValue(v string) *BronzeHistoryGCPDNSManagedZoneLabelCreate {
	_c.mutation.SetValue(v)
	return _c
}

// Mutation returns the BronzeHistoryGCPDNSManagedZoneLabelMutation object of the builder.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) Mutation() *BronzeHistoryGCPDNSManagedZoneLabelMutation {
	return _c.mutation
}

// Save creates the BronzeHistoryGCPDNSManagedZoneLabel in the database.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) Save(ctx context.Context) (*BronzeHistoryGCPDNSManagedZoneLabel, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) SaveX(ctx context.Context) *BronzeHistoryGCPDNSManagedZoneLabel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) check() error {
	if _, ok := _c.mutation.HistoryID(); !ok {
		return &ValidationError{Name: "history_id", err: errors.New(`ent: missing required field "BronzeHistoryGCPDNSManagedZoneLabel.history_id"`)}
	}
	if _, ok := _c.mutation.ManagedZoneHistoryID(); !ok {
		return &ValidationError{Name: "managed_zone_history_id", err: errors.New(`ent: missing required field "BronzeHistoryGCPDNSManagedZoneLabel.managed_zone_history_id"`)}
	}
	if _, ok := _c.mutation.ValidFrom(); !ok {
		return &ValidationError{Name: "valid_from", err: errors.New(`ent: missing required field "BronzeHistoryGCPDNSManagedZoneLabel.valid_from"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "BronzeHistoryGCPDNSManagedZoneLabel.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := bronzehistorygcpdnsmanagedzonelabel.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "BronzeHistoryGCPDNSManagedZoneLabel.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "BronzeHistoryGCPDNSManagedZoneLabel.value"`)}
	}
	return nil
}

func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) sqlSave(ctx context.Context) (*BronzeHistoryGCPDNSManagedZoneLabel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreate) createSpec() (*BronzeHistoryGCPDNSManagedZoneLabel, *sqlgraph.CreateSpec) {
	var (
		_node = &BronzeHistoryGCPDNSManagedZoneLabel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bronzehistorygcpdnsmanagedzonelabel.Table, sqlgraph.NewFieldSpec(bronzehistorygcpdnsmanagedzonelabel.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.BronzeHistoryGCPDNSManagedZoneLabel
	if value, ok := _c.mutation.HistoryID(); ok {
		_spec.SetField(bronzehistorygcpdnsmanagedzonelabel.FieldHistoryID, field.TypeUint, value)
		_node.HistoryID = value
	}
	if value, ok := _c.mutation.ManagedZoneHistoryID(); ok {
		_spec.SetField(bronzehistorygcpdnsmanagedzonelabel.FieldManagedZoneHistoryID, field.TypeUint, value)
		_node.ManagedZoneHistoryID = value
	}
	if value, ok := _c.mutation.ValidFrom(); ok {
		_spec.SetField(bronzehistorygcpdnsmanagedzonelabel.FieldValidFrom, field.TypeTime, value)
		_node.ValidFrom = value
	}
	if value, ok := _c.mutation.ValidTo(); ok {
		_spec.SetField(bronzehistorygcpdnsmanagedzonelabel.FieldValidTo, field.TypeTime, value)
		_node.ValidTo = &value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(bronzehistorygcpdnsmanagedzonelabel.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(bronzehistorygcpdnsmanagedzonelabel.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	return _node, _spec
}

// BronzeHistoryGCPDNSManagedZoneLabelCreateBulk is the builder for creating many BronzeHistoryGCPDNSManagedZoneLabel entities in bulk.
type BronzeHistoryGCPDNSManagedZoneLabelCreateBulk struct {
	config
	err      error
	builders []*BronzeHistoryGCPDNSManagedZoneLabelCreate
}

// Save creates the BronzeHistoryGCPDNSManagedZoneLabel entities in the database.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreateBulk) Save(ctx context.Context) ([]*BronzeHistoryGCPDNSManagedZoneLabel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BronzeHistoryGCPDNSManagedZoneLabel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BronzeHistoryGCPDNSManagedZoneLabelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreateBulk) SaveX(ctx context.Context) []*BronzeHistoryGCPDNSManagedZoneLabel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BronzeHistoryGCPDNSManagedZoneLabelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
