// Code generated by ent, DO NOT EDIT.

package network

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dannyota/hotpot/pkg/storage/ent/greennode/network/bronzehistorygreennodenetworkroutetableroute"
)

// BronzeHistoryGreenNodeNetworkRouteTableRouteCreate is the builder for creating a BronzeHistoryGreenNodeNetworkRouteTableRoute entity.
type BronzeHistoryGreenNodeNetworkRouteTableRouteCreate struct {
	config
	mutation *BronzeHistoryGreenNodeNetworkRouteTableRouteMutation
	hooks    []Hook
}

// SetRouteTableHistoryID sets the "route_table_history_id" field.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetRouteTableHistoryID(v uint) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	_c.mutation.SetRouteTableHistoryID(v)
	return _c
}

// SetValidFrom sets the "valid_from" field.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetValidFrom(v time.Time) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	_c.mutation.SetValidFrom(v)
	return _c
}

// SetValidTo sets the "valid_to" field.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetValidTo(v time.Time) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	_c.mutation.SetValidTo(v)
	return _c
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetNillableValidTo(v *time.Time) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	if v != nil {
		_c.SetValidTo(*v)
	}
	return _c
}

// SetRouteID sets the "route_id" field.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetRouteID(v string) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	_c.mutation.SetRouteID(v)
	return _c
}

// SetRouteTableID sets the "route_table_id" field.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetRouteTableID(v string) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	_c.mutation.SetRouteTableID(v)
	return _c
}

// SetNillableRouteTableID sets the "route_table_id" field if the given value is not nil.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetNillableRouteTableID(v *string) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	if v != nil {
		_c.SetRouteTableID(*v)
	}
	return _c
}

// SetRoutingType sets the "routing_type" field.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetRoutingType(v string) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	_c.mutation.SetRoutingType(v)
	return _c
}

// SetNillableRoutingType sets the "routing_type" field if the given value is not nil.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetNillableRoutingType(v *string) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	if v != nil {
		_c.SetRoutingType(*v)
	}
	return _c
}

// SetDestinationCidrBlock sets the "destination_cidr_block" field.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetDestinationCidrBlock(v string) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	_c.mutation.SetDestinationCidrBlock(v)
	return _c
}

// SetNillableDestinationCidrBlock sets the "destination_cidr_block" field if the given value is not nil.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetNillableDestinationCidrBlock(v *string) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	if v != nil {
		_c.SetDestinationCidrBlock(*v)
	}
	return _c
}

// SetTarget sets the "target" field.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetTarget(v string) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetNillableTarget(v *string) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	if v != nil {
		_c.SetTarget(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetStatus(v string) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetNillableStatus(v *string) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SetID(v uint) *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BronzeHistoryGreenNodeNetworkRouteTableRouteMutation object of the builder.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) Mutation() *BronzeHistoryGreenNodeNetworkRouteTableRouteMutation {
	return _c.mutation
}

// Save creates the BronzeHistoryGreenNodeNetworkRouteTableRoute in the database.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) Save(ctx context.Context) (*BronzeHistoryGreenNodeNetworkRouteTableRoute, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) SaveX(ctx context.Context) *BronzeHistoryGreenNodeNetworkRouteTableRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) check() error {
	if _, ok := _c.mutation.RouteTableHistoryID(); !ok {
		return &ValidationError{Name: "route_table_history_id", err: errors.New(`network: missing required field "BronzeHistoryGreenNodeNetworkRouteTableRoute.route_table_history_id"`)}
	}
	if _, ok := _c.mutation.ValidFrom(); !ok {
		return &ValidationError{Name: "valid_from", err: errors.New(`network: missing required field "BronzeHistoryGreenNodeNetworkRouteTableRoute.valid_from"`)}
	}
	if _, ok := _c.mutation.RouteID(); !ok {
		return &ValidationError{Name: "route_id", err: errors.New(`network: missing required field "BronzeHistoryGreenNodeNetworkRouteTableRoute.route_id"`)}
	}
	if v, ok := _c.mutation.RouteID(); ok {
		if err := bronzehistorygreennodenetworkroutetableroute.RouteIDValidator(v); err != nil {
			return &ValidationError{Name: "route_id", err: fmt.Errorf(`network: validator failed for field "BronzeHistoryGreenNodeNetworkRouteTableRoute.route_id": %w`, err)}
		}
	}
	return nil
}

func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) sqlSave(ctx context.Context) (*BronzeHistoryGreenNodeNetworkRouteTableRoute, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreate) createSpec() (*BronzeHistoryGreenNodeNetworkRouteTableRoute, *sqlgraph.CreateSpec) {
	var (
		_node = &BronzeHistoryGreenNodeNetworkRouteTableRoute{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bronzehistorygreennodenetworkroutetableroute.Table, sqlgraph.NewFieldSpec(bronzehistorygreennodenetworkroutetableroute.FieldID, field.TypeUint))
	)
	_spec.Schema = _c.schemaConfig.BronzeHistoryGreenNodeNetworkRouteTableRoute
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RouteTableHistoryID(); ok {
		_spec.SetField(bronzehistorygreennodenetworkroutetableroute.FieldRouteTableHistoryID, field.TypeUint, value)
		_node.RouteTableHistoryID = value
	}
	if value, ok := _c.mutation.ValidFrom(); ok {
		_spec.SetField(bronzehistorygreennodenetworkroutetableroute.FieldValidFrom, field.TypeTime, value)
		_node.ValidFrom = value
	}
	if value, ok := _c.mutation.ValidTo(); ok {
		_spec.SetField(bronzehistorygreennodenetworkroutetableroute.FieldValidTo, field.TypeTime, value)
		_node.ValidTo = &value
	}
	if value, ok := _c.mutation.RouteID(); ok {
		_spec.SetField(bronzehistorygreennodenetworkroutetableroute.FieldRouteID, field.TypeString, value)
		_node.RouteID = value
	}
	if value, ok := _c.mutation.RouteTableID(); ok {
		_spec.SetField(bronzehistorygreennodenetworkroutetableroute.FieldRouteTableID, field.TypeString, value)
		_node.RouteTableID = value
	}
	if value, ok := _c.mutation.RoutingType(); ok {
		_spec.SetField(bronzehistorygreennodenetworkroutetableroute.FieldRoutingType, field.TypeString, value)
		_node.RoutingType = value
	}
	if value, ok := _c.mutation.DestinationCidrBlock(); ok {
		_spec.SetField(bronzehistorygreennodenetworkroutetableroute.FieldDestinationCidrBlock, field.TypeString, value)
		_node.DestinationCidrBlock = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(bronzehistorygreennodenetworkroutetableroute.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(bronzehistorygreennodenetworkroutetableroute.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	return _node, _spec
}

// BronzeHistoryGreenNodeNetworkRouteTableRouteCreateBulk is the builder for creating many BronzeHistoryGreenNodeNetworkRouteTableRoute entities in bulk.
type BronzeHistoryGreenNodeNetworkRouteTableRouteCreateBulk struct {
	config
	err      error
	builders []*BronzeHistoryGreenNodeNetworkRouteTableRouteCreate
}

// Save creates the BronzeHistoryGreenNodeNetworkRouteTableRoute entities in the database.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreateBulk) Save(ctx context.Context) ([]*BronzeHistoryGreenNodeNetworkRouteTableRoute, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BronzeHistoryGreenNodeNetworkRouteTableRoute, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BronzeHistoryGreenNodeNetworkRouteTableRouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreateBulk) SaveX(ctx context.Context) []*BronzeHistoryGreenNodeNetworkRouteTableRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BronzeHistoryGreenNodeNetworkRouteTableRouteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
