// Code generated by ent, DO NOT EDIT.

package network

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"danny.vn/hotpot/pkg/storage/ent/greennode/network/bronzehistorygreennodenetworkendpoint"
	"danny.vn/hotpot/pkg/storage/ent/greennode/network/internal"
	"danny.vn/hotpot/pkg/storage/ent/greennode/network/predicate"
)

// BronzeHistoryGreenNodeNetworkEndpointDelete is the builder for deleting a BronzeHistoryGreenNodeNetworkEndpoint entity.
type BronzeHistoryGreenNodeNetworkEndpointDelete struct {
	config
	hooks    []Hook
	mutation *BronzeHistoryGreenNodeNetworkEndpointMutation
}

// Where appends a list predicates to the BronzeHistoryGreenNodeNetworkEndpointDelete builder.
func (_d *BronzeHistoryGreenNodeNetworkEndpointDelete) Where(ps ...predicate.BronzeHistoryGreenNodeNetworkEndpoint) *BronzeHistoryGreenNodeNetworkEndpointDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BronzeHistoryGreenNodeNetworkEndpointDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BronzeHistoryGreenNodeNetworkEndpointDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BronzeHistoryGreenNodeNetworkEndpointDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bronzehistorygreennodenetworkendpoint.Table, sqlgraph.NewFieldSpec(bronzehistorygreennodenetworkendpoint.FieldID, field.TypeUint))
	_spec.Node.Schema = _d.schemaConfig.BronzeHistoryGreenNodeNetworkEndpoint
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BronzeHistoryGreenNodeNetworkEndpointDeleteOne is the builder for deleting a single BronzeHistoryGreenNodeNetworkEndpoint entity.
type BronzeHistoryGreenNodeNetworkEndpointDeleteOne struct {
	_d *BronzeHistoryGreenNodeNetworkEndpointDelete
}

// Where appends a list predicates to the BronzeHistoryGreenNodeNetworkEndpointDelete builder.
func (_d *BronzeHistoryGreenNodeNetworkEndpointDeleteOne) Where(ps ...predicate.BronzeHistoryGreenNodeNetworkEndpoint) *BronzeHistoryGreenNodeNetworkEndpointDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BronzeHistoryGreenNodeNetworkEndpointDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bronzehistorygreennodenetworkendpoint.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BronzeHistoryGreenNodeNetworkEndpointDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
