// Code generated by ent, DO NOT EDIT.

package bronzehistorygcpspannerdatabase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dannyota/hotpot/pkg/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldID, id))
}

// ValidFrom applies equality check predicate on the "valid_from" field. It's identical to ValidFromEQ.
func ValidFrom(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldValidFrom, v))
}

// ValidTo applies equality check predicate on the "valid_to" field. It's identical to ValidToEQ.
func ValidTo(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldValidTo, v))
}

// CollectedAt applies equality check predicate on the "collected_at" field. It's identical to CollectedAtEQ.
func CollectedAt(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldCollectedAt, v))
}

// FirstCollectedAt applies equality check predicate on the "first_collected_at" field. It's identical to FirstCollectedAtEQ.
func FirstCollectedAt(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldFirstCollectedAt, v))
}

// HistoryID applies equality check predicate on the "history_id" field. It's identical to HistoryIDEQ.
func HistoryID(v uint) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldHistoryID, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldResourceID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldName, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldState, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldCreateTime, v))
}

// VersionRetentionPeriod applies equality check predicate on the "version_retention_period" field. It's identical to VersionRetentionPeriodEQ.
func VersionRetentionPeriod(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldVersionRetentionPeriod, v))
}

// EarliestVersionTime applies equality check predicate on the "earliest_version_time" field. It's identical to EarliestVersionTimeEQ.
func EarliestVersionTime(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldEarliestVersionTime, v))
}

// DefaultLeader applies equality check predicate on the "default_leader" field. It's identical to DefaultLeaderEQ.
func DefaultLeader(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldDefaultLeader, v))
}

// DatabaseDialect applies equality check predicate on the "database_dialect" field. It's identical to DatabaseDialectEQ.
func DatabaseDialect(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldDatabaseDialect, v))
}

// EnableDropProtection applies equality check predicate on the "enable_drop_protection" field. It's identical to EnableDropProtectionEQ.
func EnableDropProtection(v bool) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldEnableDropProtection, v))
}

// Reconciling applies equality check predicate on the "reconciling" field. It's identical to ReconcilingEQ.
func Reconciling(v bool) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldReconciling, v))
}

// InstanceName applies equality check predicate on the "instance_name" field. It's identical to InstanceNameEQ.
func InstanceName(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldInstanceName, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldProjectID, v))
}

// ValidFromEQ applies the EQ predicate on the "valid_from" field.
func ValidFromEQ(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldValidFrom, v))
}

// ValidFromNEQ applies the NEQ predicate on the "valid_from" field.
func ValidFromNEQ(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldValidFrom, v))
}

// ValidFromIn applies the In predicate on the "valid_from" field.
func ValidFromIn(vs ...time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldValidFrom, vs...))
}

// ValidFromNotIn applies the NotIn predicate on the "valid_from" field.
func ValidFromNotIn(vs ...time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldValidFrom, vs...))
}

// ValidFromGT applies the GT predicate on the "valid_from" field.
func ValidFromGT(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldValidFrom, v))
}

// ValidFromGTE applies the GTE predicate on the "valid_from" field.
func ValidFromGTE(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldValidFrom, v))
}

// ValidFromLT applies the LT predicate on the "valid_from" field.
func ValidFromLT(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldValidFrom, v))
}

// ValidFromLTE applies the LTE predicate on the "valid_from" field.
func ValidFromLTE(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldValidFrom, v))
}

// ValidToEQ applies the EQ predicate on the "valid_to" field.
func ValidToEQ(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldValidTo, v))
}

// ValidToNEQ applies the NEQ predicate on the "valid_to" field.
func ValidToNEQ(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldValidTo, v))
}

// ValidToIn applies the In predicate on the "valid_to" field.
func ValidToIn(vs ...time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldValidTo, vs...))
}

// ValidToNotIn applies the NotIn predicate on the "valid_to" field.
func ValidToNotIn(vs ...time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldValidTo, vs...))
}

// ValidToGT applies the GT predicate on the "valid_to" field.
func ValidToGT(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldValidTo, v))
}

// ValidToGTE applies the GTE predicate on the "valid_to" field.
func ValidToGTE(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldValidTo, v))
}

// ValidToLT applies the LT predicate on the "valid_to" field.
func ValidToLT(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldValidTo, v))
}

// ValidToLTE applies the LTE predicate on the "valid_to" field.
func ValidToLTE(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldValidTo, v))
}

// ValidToIsNil applies the IsNil predicate on the "valid_to" field.
func ValidToIsNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIsNull(FieldValidTo))
}

// ValidToNotNil applies the NotNil predicate on the "valid_to" field.
func ValidToNotNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotNull(FieldValidTo))
}

// CollectedAtEQ applies the EQ predicate on the "collected_at" field.
func CollectedAtEQ(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldCollectedAt, v))
}

// CollectedAtNEQ applies the NEQ predicate on the "collected_at" field.
func CollectedAtNEQ(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldCollectedAt, v))
}

// CollectedAtIn applies the In predicate on the "collected_at" field.
func CollectedAtIn(vs ...time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldCollectedAt, vs...))
}

// CollectedAtNotIn applies the NotIn predicate on the "collected_at" field.
func CollectedAtNotIn(vs ...time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldCollectedAt, vs...))
}

// CollectedAtGT applies the GT predicate on the "collected_at" field.
func CollectedAtGT(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldCollectedAt, v))
}

// CollectedAtGTE applies the GTE predicate on the "collected_at" field.
func CollectedAtGTE(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldCollectedAt, v))
}

// CollectedAtLT applies the LT predicate on the "collected_at" field.
func CollectedAtLT(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldCollectedAt, v))
}

// CollectedAtLTE applies the LTE predicate on the "collected_at" field.
func CollectedAtLTE(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldCollectedAt, v))
}

// FirstCollectedAtEQ applies the EQ predicate on the "first_collected_at" field.
func FirstCollectedAtEQ(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldFirstCollectedAt, v))
}

// FirstCollectedAtNEQ applies the NEQ predicate on the "first_collected_at" field.
func FirstCollectedAtNEQ(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldFirstCollectedAt, v))
}

// FirstCollectedAtIn applies the In predicate on the "first_collected_at" field.
func FirstCollectedAtIn(vs ...time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldFirstCollectedAt, vs...))
}

// FirstCollectedAtNotIn applies the NotIn predicate on the "first_collected_at" field.
func FirstCollectedAtNotIn(vs ...time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldFirstCollectedAt, vs...))
}

// FirstCollectedAtGT applies the GT predicate on the "first_collected_at" field.
func FirstCollectedAtGT(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldFirstCollectedAt, v))
}

// FirstCollectedAtGTE applies the GTE predicate on the "first_collected_at" field.
func FirstCollectedAtGTE(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldFirstCollectedAt, v))
}

// FirstCollectedAtLT applies the LT predicate on the "first_collected_at" field.
func FirstCollectedAtLT(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldFirstCollectedAt, v))
}

// FirstCollectedAtLTE applies the LTE predicate on the "first_collected_at" field.
func FirstCollectedAtLTE(v time.Time) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldFirstCollectedAt, v))
}

// HistoryIDEQ applies the EQ predicate on the "history_id" field.
func HistoryIDEQ(v uint) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldHistoryID, v))
}

// HistoryIDNEQ applies the NEQ predicate on the "history_id" field.
func HistoryIDNEQ(v uint) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldHistoryID, v))
}

// HistoryIDIn applies the In predicate on the "history_id" field.
func HistoryIDIn(vs ...uint) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldHistoryID, vs...))
}

// HistoryIDNotIn applies the NotIn predicate on the "history_id" field.
func HistoryIDNotIn(vs ...uint) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldHistoryID, vs...))
}

// HistoryIDGT applies the GT predicate on the "history_id" field.
func HistoryIDGT(v uint) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldHistoryID, v))
}

// HistoryIDGTE applies the GTE predicate on the "history_id" field.
func HistoryIDGTE(v uint) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldHistoryID, v))
}

// HistoryIDLT applies the LT predicate on the "history_id" field.
func HistoryIDLT(v uint) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldHistoryID, v))
}

// HistoryIDLTE applies the LTE predicate on the "history_id" field.
func HistoryIDLTE(v uint) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldHistoryID, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldResourceID, v))
}

// ResourceIDContains applies the Contains predicate on the "resource_id" field.
func ResourceIDContains(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContains(FieldResourceID, v))
}

// ResourceIDHasPrefix applies the HasPrefix predicate on the "resource_id" field.
func ResourceIDHasPrefix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasPrefix(FieldResourceID, v))
}

// ResourceIDHasSuffix applies the HasSuffix predicate on the "resource_id" field.
func ResourceIDHasSuffix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasSuffix(FieldResourceID, v))
}

// ResourceIDEqualFold applies the EqualFold predicate on the "resource_id" field.
func ResourceIDEqualFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEqualFold(FieldResourceID, v))
}

// ResourceIDContainsFold applies the ContainsFold predicate on the "resource_id" field.
func ResourceIDContainsFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContainsFold(FieldResourceID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContainsFold(FieldName, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldState, v))
}

// StateIsNil applies the IsNil predicate on the "state" field.
func StateIsNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIsNull(FieldState))
}

// StateNotNil applies the NotNil predicate on the "state" field.
func StateNotNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotNull(FieldState))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeContains applies the Contains predicate on the "create_time" field.
func CreateTimeContains(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContains(FieldCreateTime, v))
}

// CreateTimeHasPrefix applies the HasPrefix predicate on the "create_time" field.
func CreateTimeHasPrefix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasPrefix(FieldCreateTime, v))
}

// CreateTimeHasSuffix applies the HasSuffix predicate on the "create_time" field.
func CreateTimeHasSuffix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasSuffix(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotNull(FieldCreateTime))
}

// CreateTimeEqualFold applies the EqualFold predicate on the "create_time" field.
func CreateTimeEqualFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEqualFold(FieldCreateTime, v))
}

// CreateTimeContainsFold applies the ContainsFold predicate on the "create_time" field.
func CreateTimeContainsFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContainsFold(FieldCreateTime, v))
}

// RestoreInfoJSONIsNil applies the IsNil predicate on the "restore_info_json" field.
func RestoreInfoJSONIsNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIsNull(FieldRestoreInfoJSON))
}

// RestoreInfoJSONNotNil applies the NotNil predicate on the "restore_info_json" field.
func RestoreInfoJSONNotNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotNull(FieldRestoreInfoJSON))
}

// EncryptionConfigJSONIsNil applies the IsNil predicate on the "encryption_config_json" field.
func EncryptionConfigJSONIsNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIsNull(FieldEncryptionConfigJSON))
}

// EncryptionConfigJSONNotNil applies the NotNil predicate on the "encryption_config_json" field.
func EncryptionConfigJSONNotNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotNull(FieldEncryptionConfigJSON))
}

// EncryptionInfoJSONIsNil applies the IsNil predicate on the "encryption_info_json" field.
func EncryptionInfoJSONIsNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIsNull(FieldEncryptionInfoJSON))
}

// EncryptionInfoJSONNotNil applies the NotNil predicate on the "encryption_info_json" field.
func EncryptionInfoJSONNotNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotNull(FieldEncryptionInfoJSON))
}

// VersionRetentionPeriodEQ applies the EQ predicate on the "version_retention_period" field.
func VersionRetentionPeriodEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldVersionRetentionPeriod, v))
}

// VersionRetentionPeriodNEQ applies the NEQ predicate on the "version_retention_period" field.
func VersionRetentionPeriodNEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldVersionRetentionPeriod, v))
}

// VersionRetentionPeriodIn applies the In predicate on the "version_retention_period" field.
func VersionRetentionPeriodIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldVersionRetentionPeriod, vs...))
}

// VersionRetentionPeriodNotIn applies the NotIn predicate on the "version_retention_period" field.
func VersionRetentionPeriodNotIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldVersionRetentionPeriod, vs...))
}

// VersionRetentionPeriodGT applies the GT predicate on the "version_retention_period" field.
func VersionRetentionPeriodGT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldVersionRetentionPeriod, v))
}

// VersionRetentionPeriodGTE applies the GTE predicate on the "version_retention_period" field.
func VersionRetentionPeriodGTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldVersionRetentionPeriod, v))
}

// VersionRetentionPeriodLT applies the LT predicate on the "version_retention_period" field.
func VersionRetentionPeriodLT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldVersionRetentionPeriod, v))
}

// VersionRetentionPeriodLTE applies the LTE predicate on the "version_retention_period" field.
func VersionRetentionPeriodLTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldVersionRetentionPeriod, v))
}

// VersionRetentionPeriodContains applies the Contains predicate on the "version_retention_period" field.
func VersionRetentionPeriodContains(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContains(FieldVersionRetentionPeriod, v))
}

// VersionRetentionPeriodHasPrefix applies the HasPrefix predicate on the "version_retention_period" field.
func VersionRetentionPeriodHasPrefix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasPrefix(FieldVersionRetentionPeriod, v))
}

// VersionRetentionPeriodHasSuffix applies the HasSuffix predicate on the "version_retention_period" field.
func VersionRetentionPeriodHasSuffix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasSuffix(FieldVersionRetentionPeriod, v))
}

// VersionRetentionPeriodIsNil applies the IsNil predicate on the "version_retention_period" field.
func VersionRetentionPeriodIsNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIsNull(FieldVersionRetentionPeriod))
}

// VersionRetentionPeriodNotNil applies the NotNil predicate on the "version_retention_period" field.
func VersionRetentionPeriodNotNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotNull(FieldVersionRetentionPeriod))
}

// VersionRetentionPeriodEqualFold applies the EqualFold predicate on the "version_retention_period" field.
func VersionRetentionPeriodEqualFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEqualFold(FieldVersionRetentionPeriod, v))
}

// VersionRetentionPeriodContainsFold applies the ContainsFold predicate on the "version_retention_period" field.
func VersionRetentionPeriodContainsFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContainsFold(FieldVersionRetentionPeriod, v))
}

// EarliestVersionTimeEQ applies the EQ predicate on the "earliest_version_time" field.
func EarliestVersionTimeEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldEarliestVersionTime, v))
}

// EarliestVersionTimeNEQ applies the NEQ predicate on the "earliest_version_time" field.
func EarliestVersionTimeNEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldEarliestVersionTime, v))
}

// EarliestVersionTimeIn applies the In predicate on the "earliest_version_time" field.
func EarliestVersionTimeIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldEarliestVersionTime, vs...))
}

// EarliestVersionTimeNotIn applies the NotIn predicate on the "earliest_version_time" field.
func EarliestVersionTimeNotIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldEarliestVersionTime, vs...))
}

// EarliestVersionTimeGT applies the GT predicate on the "earliest_version_time" field.
func EarliestVersionTimeGT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldEarliestVersionTime, v))
}

// EarliestVersionTimeGTE applies the GTE predicate on the "earliest_version_time" field.
func EarliestVersionTimeGTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldEarliestVersionTime, v))
}

// EarliestVersionTimeLT applies the LT predicate on the "earliest_version_time" field.
func EarliestVersionTimeLT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldEarliestVersionTime, v))
}

// EarliestVersionTimeLTE applies the LTE predicate on the "earliest_version_time" field.
func EarliestVersionTimeLTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldEarliestVersionTime, v))
}

// EarliestVersionTimeContains applies the Contains predicate on the "earliest_version_time" field.
func EarliestVersionTimeContains(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContains(FieldEarliestVersionTime, v))
}

// EarliestVersionTimeHasPrefix applies the HasPrefix predicate on the "earliest_version_time" field.
func EarliestVersionTimeHasPrefix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasPrefix(FieldEarliestVersionTime, v))
}

// EarliestVersionTimeHasSuffix applies the HasSuffix predicate on the "earliest_version_time" field.
func EarliestVersionTimeHasSuffix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasSuffix(FieldEarliestVersionTime, v))
}

// EarliestVersionTimeIsNil applies the IsNil predicate on the "earliest_version_time" field.
func EarliestVersionTimeIsNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIsNull(FieldEarliestVersionTime))
}

// EarliestVersionTimeNotNil applies the NotNil predicate on the "earliest_version_time" field.
func EarliestVersionTimeNotNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotNull(FieldEarliestVersionTime))
}

// EarliestVersionTimeEqualFold applies the EqualFold predicate on the "earliest_version_time" field.
func EarliestVersionTimeEqualFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEqualFold(FieldEarliestVersionTime, v))
}

// EarliestVersionTimeContainsFold applies the ContainsFold predicate on the "earliest_version_time" field.
func EarliestVersionTimeContainsFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContainsFold(FieldEarliestVersionTime, v))
}

// DefaultLeaderEQ applies the EQ predicate on the "default_leader" field.
func DefaultLeaderEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldDefaultLeader, v))
}

// DefaultLeaderNEQ applies the NEQ predicate on the "default_leader" field.
func DefaultLeaderNEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldDefaultLeader, v))
}

// DefaultLeaderIn applies the In predicate on the "default_leader" field.
func DefaultLeaderIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldDefaultLeader, vs...))
}

// DefaultLeaderNotIn applies the NotIn predicate on the "default_leader" field.
func DefaultLeaderNotIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldDefaultLeader, vs...))
}

// DefaultLeaderGT applies the GT predicate on the "default_leader" field.
func DefaultLeaderGT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldDefaultLeader, v))
}

// DefaultLeaderGTE applies the GTE predicate on the "default_leader" field.
func DefaultLeaderGTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldDefaultLeader, v))
}

// DefaultLeaderLT applies the LT predicate on the "default_leader" field.
func DefaultLeaderLT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldDefaultLeader, v))
}

// DefaultLeaderLTE applies the LTE predicate on the "default_leader" field.
func DefaultLeaderLTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldDefaultLeader, v))
}

// DefaultLeaderContains applies the Contains predicate on the "default_leader" field.
func DefaultLeaderContains(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContains(FieldDefaultLeader, v))
}

// DefaultLeaderHasPrefix applies the HasPrefix predicate on the "default_leader" field.
func DefaultLeaderHasPrefix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasPrefix(FieldDefaultLeader, v))
}

// DefaultLeaderHasSuffix applies the HasSuffix predicate on the "default_leader" field.
func DefaultLeaderHasSuffix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasSuffix(FieldDefaultLeader, v))
}

// DefaultLeaderIsNil applies the IsNil predicate on the "default_leader" field.
func DefaultLeaderIsNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIsNull(FieldDefaultLeader))
}

// DefaultLeaderNotNil applies the NotNil predicate on the "default_leader" field.
func DefaultLeaderNotNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotNull(FieldDefaultLeader))
}

// DefaultLeaderEqualFold applies the EqualFold predicate on the "default_leader" field.
func DefaultLeaderEqualFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEqualFold(FieldDefaultLeader, v))
}

// DefaultLeaderContainsFold applies the ContainsFold predicate on the "default_leader" field.
func DefaultLeaderContainsFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContainsFold(FieldDefaultLeader, v))
}

// DatabaseDialectEQ applies the EQ predicate on the "database_dialect" field.
func DatabaseDialectEQ(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldDatabaseDialect, v))
}

// DatabaseDialectNEQ applies the NEQ predicate on the "database_dialect" field.
func DatabaseDialectNEQ(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldDatabaseDialect, v))
}

// DatabaseDialectIn applies the In predicate on the "database_dialect" field.
func DatabaseDialectIn(vs ...int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldDatabaseDialect, vs...))
}

// DatabaseDialectNotIn applies the NotIn predicate on the "database_dialect" field.
func DatabaseDialectNotIn(vs ...int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldDatabaseDialect, vs...))
}

// DatabaseDialectGT applies the GT predicate on the "database_dialect" field.
func DatabaseDialectGT(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldDatabaseDialect, v))
}

// DatabaseDialectGTE applies the GTE predicate on the "database_dialect" field.
func DatabaseDialectGTE(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldDatabaseDialect, v))
}

// DatabaseDialectLT applies the LT predicate on the "database_dialect" field.
func DatabaseDialectLT(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldDatabaseDialect, v))
}

// DatabaseDialectLTE applies the LTE predicate on the "database_dialect" field.
func DatabaseDialectLTE(v int) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldDatabaseDialect, v))
}

// DatabaseDialectIsNil applies the IsNil predicate on the "database_dialect" field.
func DatabaseDialectIsNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIsNull(FieldDatabaseDialect))
}

// DatabaseDialectNotNil applies the NotNil predicate on the "database_dialect" field.
func DatabaseDialectNotNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotNull(FieldDatabaseDialect))
}

// EnableDropProtectionEQ applies the EQ predicate on the "enable_drop_protection" field.
func EnableDropProtectionEQ(v bool) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldEnableDropProtection, v))
}

// EnableDropProtectionNEQ applies the NEQ predicate on the "enable_drop_protection" field.
func EnableDropProtectionNEQ(v bool) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldEnableDropProtection, v))
}

// ReconcilingEQ applies the EQ predicate on the "reconciling" field.
func ReconcilingEQ(v bool) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldReconciling, v))
}

// ReconcilingNEQ applies the NEQ predicate on the "reconciling" field.
func ReconcilingNEQ(v bool) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldReconciling, v))
}

// InstanceNameEQ applies the EQ predicate on the "instance_name" field.
func InstanceNameEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldInstanceName, v))
}

// InstanceNameNEQ applies the NEQ predicate on the "instance_name" field.
func InstanceNameNEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldInstanceName, v))
}

// InstanceNameIn applies the In predicate on the "instance_name" field.
func InstanceNameIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldInstanceName, vs...))
}

// InstanceNameNotIn applies the NotIn predicate on the "instance_name" field.
func InstanceNameNotIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldInstanceName, vs...))
}

// InstanceNameGT applies the GT predicate on the "instance_name" field.
func InstanceNameGT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldInstanceName, v))
}

// InstanceNameGTE applies the GTE predicate on the "instance_name" field.
func InstanceNameGTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldInstanceName, v))
}

// InstanceNameLT applies the LT predicate on the "instance_name" field.
func InstanceNameLT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldInstanceName, v))
}

// InstanceNameLTE applies the LTE predicate on the "instance_name" field.
func InstanceNameLTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldInstanceName, v))
}

// InstanceNameContains applies the Contains predicate on the "instance_name" field.
func InstanceNameContains(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContains(FieldInstanceName, v))
}

// InstanceNameHasPrefix applies the HasPrefix predicate on the "instance_name" field.
func InstanceNameHasPrefix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasPrefix(FieldInstanceName, v))
}

// InstanceNameHasSuffix applies the HasSuffix predicate on the "instance_name" field.
func InstanceNameHasSuffix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasSuffix(FieldInstanceName, v))
}

// InstanceNameIsNil applies the IsNil predicate on the "instance_name" field.
func InstanceNameIsNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIsNull(FieldInstanceName))
}

// InstanceNameNotNil applies the NotNil predicate on the "instance_name" field.
func InstanceNameNotNil() predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotNull(FieldInstanceName))
}

// InstanceNameEqualFold applies the EqualFold predicate on the "instance_name" field.
func InstanceNameEqualFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEqualFold(FieldInstanceName, v))
}

// InstanceNameContainsFold applies the ContainsFold predicate on the "instance_name" field.
func InstanceNameContainsFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContainsFold(FieldInstanceName, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.FieldContainsFold(FieldProjectID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BronzeHistoryGCPSpannerDatabase) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BronzeHistoryGCPSpannerDatabase) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BronzeHistoryGCPSpannerDatabase) predicate.BronzeHistoryGCPSpannerDatabase {
	return predicate.BronzeHistoryGCPSpannerDatabase(sql.NotPredicates(p))
}
