// Code generated by ent, DO NOT EDIT.

package bronzehistorygcpmonitoringalertpolicy

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the bronzehistorygcpmonitoringalertpolicy type in the database.
	Label = "bronze_history_gcp_monitoring_alert_policy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldValidFrom holds the string denoting the valid_from field in the database.
	FieldValidFrom = "valid_from"
	// FieldValidTo holds the string denoting the valid_to field in the database.
	FieldValidTo = "valid_to"
	// FieldCollectedAt holds the string denoting the collected_at field in the database.
	FieldCollectedAt = "collected_at"
	// FieldFirstCollectedAt holds the string denoting the first_collected_at field in the database.
	FieldFirstCollectedAt = "first_collected_at"
	// FieldHistoryID holds the string denoting the history_id field in the database.
	FieldHistoryID = "history_id"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldDocumentationJSON holds the string denoting the documentation_json field in the database.
	FieldDocumentationJSON = "documentation_json"
	// FieldUserLabelsJSON holds the string denoting the user_labels_json field in the database.
	FieldUserLabelsJSON = "user_labels_json"
	// FieldConditionsJSON holds the string denoting the conditions_json field in the database.
	FieldConditionsJSON = "conditions_json"
	// FieldCombiner holds the string denoting the combiner field in the database.
	FieldCombiner = "combiner"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldNotificationChannelsJSON holds the string denoting the notification_channels_json field in the database.
	FieldNotificationChannelsJSON = "notification_channels_json"
	// FieldCreationRecordJSON holds the string denoting the creation_record_json field in the database.
	FieldCreationRecordJSON = "creation_record_json"
	// FieldMutationRecordJSON holds the string denoting the mutation_record_json field in the database.
	FieldMutationRecordJSON = "mutation_record_json"
	// FieldAlertStrategyJSON holds the string denoting the alert_strategy_json field in the database.
	FieldAlertStrategyJSON = "alert_strategy_json"
	// FieldSeverity holds the string denoting the severity field in the database.
	FieldSeverity = "severity"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// Table holds the table name of the bronzehistorygcpmonitoringalertpolicy in the database.
	Table = "gcp_monitoring_alert_policies_history"
)

// Columns holds all SQL columns for bronzehistorygcpmonitoringalertpolicy fields.
var Columns = []string{
	FieldID,
	FieldValidFrom,
	FieldValidTo,
	FieldCollectedAt,
	FieldFirstCollectedAt,
	FieldHistoryID,
	FieldResourceID,
	FieldName,
	FieldDisplayName,
	FieldDocumentationJSON,
	FieldUserLabelsJSON,
	FieldConditionsJSON,
	FieldCombiner,
	FieldEnabled,
	FieldNotificationChannelsJSON,
	FieldCreationRecordJSON,
	FieldMutationRecordJSON,
	FieldAlertStrategyJSON,
	FieldSeverity,
	FieldProjectID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	ResourceIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCombiner holds the default value on creation for the "combiner" field.
	DefaultCombiner int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSeverity holds the default value on creation for the "severity" field.
	DefaultSeverity int
	// ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	ProjectIDValidator func(string) error
)

// OrderOption defines the ordering options for the BronzeHistoryGCPMonitoringAlertPolicy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByValidFrom orders the results by the valid_from field.
func ByValidFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidFrom, opts...).ToFunc()
}

// ByValidTo orders the results by the valid_to field.
func ByValidTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidTo, opts...).ToFunc()
}

// ByCollectedAt orders the results by the collected_at field.
func ByCollectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectedAt, opts...).ToFunc()
}

// ByFirstCollectedAt orders the results by the first_collected_at field.
func ByFirstCollectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstCollectedAt, opts...).ToFunc()
}

// ByHistoryID orders the results by the history_id field.
func ByHistoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHistoryID, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByCombiner orders the results by the combiner field.
func ByCombiner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCombiner, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySeverity orders the results by the severity field.
func BySeverity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverity, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}
