// Code generated by ent, DO NOT EDIT.

package bronzegreennodevolumevolumetype

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dannyota/hotpot/pkg/storage/ent/greennode/volume/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldContainsFold(FieldID, id))
}

// CollectedAt applies equality check predicate on the "collected_at" field. It's identical to CollectedAtEQ.
func CollectedAt(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldCollectedAt, v))
}

// FirstCollectedAt applies equality check predicate on the "first_collected_at" field. It's identical to FirstCollectedAtEQ.
func FirstCollectedAt(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldFirstCollectedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldName, v))
}

// Iops applies equality check predicate on the "iops" field. It's identical to IopsEQ.
func Iops(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldIops, v))
}

// MaxSize applies equality check predicate on the "max_size" field. It's identical to MaxSizeEQ.
func MaxSize(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldMaxSize, v))
}

// MinSize applies equality check predicate on the "min_size" field. It's identical to MinSizeEQ.
func MinSize(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldMinSize, v))
}

// ThroughPut applies equality check predicate on the "through_put" field. It's identical to ThroughPutEQ.
func ThroughPut(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldThroughPut, v))
}

// ZoneID applies equality check predicate on the "zone_id" field. It's identical to ZoneIDEQ.
func ZoneID(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldZoneID, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldRegion, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldProjectID, v))
}

// CollectedAtEQ applies the EQ predicate on the "collected_at" field.
func CollectedAtEQ(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldCollectedAt, v))
}

// CollectedAtNEQ applies the NEQ predicate on the "collected_at" field.
func CollectedAtNEQ(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNEQ(FieldCollectedAt, v))
}

// CollectedAtIn applies the In predicate on the "collected_at" field.
func CollectedAtIn(vs ...time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIn(FieldCollectedAt, vs...))
}

// CollectedAtNotIn applies the NotIn predicate on the "collected_at" field.
func CollectedAtNotIn(vs ...time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotIn(FieldCollectedAt, vs...))
}

// CollectedAtGT applies the GT predicate on the "collected_at" field.
func CollectedAtGT(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGT(FieldCollectedAt, v))
}

// CollectedAtGTE applies the GTE predicate on the "collected_at" field.
func CollectedAtGTE(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGTE(FieldCollectedAt, v))
}

// CollectedAtLT applies the LT predicate on the "collected_at" field.
func CollectedAtLT(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLT(FieldCollectedAt, v))
}

// CollectedAtLTE applies the LTE predicate on the "collected_at" field.
func CollectedAtLTE(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLTE(FieldCollectedAt, v))
}

// FirstCollectedAtEQ applies the EQ predicate on the "first_collected_at" field.
func FirstCollectedAtEQ(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldFirstCollectedAt, v))
}

// FirstCollectedAtNEQ applies the NEQ predicate on the "first_collected_at" field.
func FirstCollectedAtNEQ(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNEQ(FieldFirstCollectedAt, v))
}

// FirstCollectedAtIn applies the In predicate on the "first_collected_at" field.
func FirstCollectedAtIn(vs ...time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIn(FieldFirstCollectedAt, vs...))
}

// FirstCollectedAtNotIn applies the NotIn predicate on the "first_collected_at" field.
func FirstCollectedAtNotIn(vs ...time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotIn(FieldFirstCollectedAt, vs...))
}

// FirstCollectedAtGT applies the GT predicate on the "first_collected_at" field.
func FirstCollectedAtGT(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGT(FieldFirstCollectedAt, v))
}

// FirstCollectedAtGTE applies the GTE predicate on the "first_collected_at" field.
func FirstCollectedAtGTE(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGTE(FieldFirstCollectedAt, v))
}

// FirstCollectedAtLT applies the LT predicate on the "first_collected_at" field.
func FirstCollectedAtLT(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLT(FieldFirstCollectedAt, v))
}

// FirstCollectedAtLTE applies the LTE predicate on the "first_collected_at" field.
func FirstCollectedAtLTE(v time.Time) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLTE(FieldFirstCollectedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldContainsFold(FieldName, v))
}

// IopsEQ applies the EQ predicate on the "iops" field.
func IopsEQ(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldIops, v))
}

// IopsNEQ applies the NEQ predicate on the "iops" field.
func IopsNEQ(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNEQ(FieldIops, v))
}

// IopsIn applies the In predicate on the "iops" field.
func IopsIn(vs ...int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIn(FieldIops, vs...))
}

// IopsNotIn applies the NotIn predicate on the "iops" field.
func IopsNotIn(vs ...int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotIn(FieldIops, vs...))
}

// IopsGT applies the GT predicate on the "iops" field.
func IopsGT(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGT(FieldIops, v))
}

// IopsGTE applies the GTE predicate on the "iops" field.
func IopsGTE(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGTE(FieldIops, v))
}

// IopsLT applies the LT predicate on the "iops" field.
func IopsLT(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLT(FieldIops, v))
}

// IopsLTE applies the LTE predicate on the "iops" field.
func IopsLTE(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLTE(FieldIops, v))
}

// IopsIsNil applies the IsNil predicate on the "iops" field.
func IopsIsNil() predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIsNull(FieldIops))
}

// IopsNotNil applies the NotNil predicate on the "iops" field.
func IopsNotNil() predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotNull(FieldIops))
}

// MaxSizeEQ applies the EQ predicate on the "max_size" field.
func MaxSizeEQ(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldMaxSize, v))
}

// MaxSizeNEQ applies the NEQ predicate on the "max_size" field.
func MaxSizeNEQ(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNEQ(FieldMaxSize, v))
}

// MaxSizeIn applies the In predicate on the "max_size" field.
func MaxSizeIn(vs ...int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIn(FieldMaxSize, vs...))
}

// MaxSizeNotIn applies the NotIn predicate on the "max_size" field.
func MaxSizeNotIn(vs ...int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotIn(FieldMaxSize, vs...))
}

// MaxSizeGT applies the GT predicate on the "max_size" field.
func MaxSizeGT(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGT(FieldMaxSize, v))
}

// MaxSizeGTE applies the GTE predicate on the "max_size" field.
func MaxSizeGTE(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGTE(FieldMaxSize, v))
}

// MaxSizeLT applies the LT predicate on the "max_size" field.
func MaxSizeLT(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLT(FieldMaxSize, v))
}

// MaxSizeLTE applies the LTE predicate on the "max_size" field.
func MaxSizeLTE(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLTE(FieldMaxSize, v))
}

// MaxSizeIsNil applies the IsNil predicate on the "max_size" field.
func MaxSizeIsNil() predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIsNull(FieldMaxSize))
}

// MaxSizeNotNil applies the NotNil predicate on the "max_size" field.
func MaxSizeNotNil() predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotNull(FieldMaxSize))
}

// MinSizeEQ applies the EQ predicate on the "min_size" field.
func MinSizeEQ(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldMinSize, v))
}

// MinSizeNEQ applies the NEQ predicate on the "min_size" field.
func MinSizeNEQ(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNEQ(FieldMinSize, v))
}

// MinSizeIn applies the In predicate on the "min_size" field.
func MinSizeIn(vs ...int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIn(FieldMinSize, vs...))
}

// MinSizeNotIn applies the NotIn predicate on the "min_size" field.
func MinSizeNotIn(vs ...int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotIn(FieldMinSize, vs...))
}

// MinSizeGT applies the GT predicate on the "min_size" field.
func MinSizeGT(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGT(FieldMinSize, v))
}

// MinSizeGTE applies the GTE predicate on the "min_size" field.
func MinSizeGTE(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGTE(FieldMinSize, v))
}

// MinSizeLT applies the LT predicate on the "min_size" field.
func MinSizeLT(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLT(FieldMinSize, v))
}

// MinSizeLTE applies the LTE predicate on the "min_size" field.
func MinSizeLTE(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLTE(FieldMinSize, v))
}

// MinSizeIsNil applies the IsNil predicate on the "min_size" field.
func MinSizeIsNil() predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIsNull(FieldMinSize))
}

// MinSizeNotNil applies the NotNil predicate on the "min_size" field.
func MinSizeNotNil() predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotNull(FieldMinSize))
}

// ThroughPutEQ applies the EQ predicate on the "through_put" field.
func ThroughPutEQ(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldThroughPut, v))
}

// ThroughPutNEQ applies the NEQ predicate on the "through_put" field.
func ThroughPutNEQ(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNEQ(FieldThroughPut, v))
}

// ThroughPutIn applies the In predicate on the "through_put" field.
func ThroughPutIn(vs ...int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIn(FieldThroughPut, vs...))
}

// ThroughPutNotIn applies the NotIn predicate on the "through_put" field.
func ThroughPutNotIn(vs ...int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotIn(FieldThroughPut, vs...))
}

// ThroughPutGT applies the GT predicate on the "through_put" field.
func ThroughPutGT(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGT(FieldThroughPut, v))
}

// ThroughPutGTE applies the GTE predicate on the "through_put" field.
func ThroughPutGTE(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGTE(FieldThroughPut, v))
}

// ThroughPutLT applies the LT predicate on the "through_put" field.
func ThroughPutLT(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLT(FieldThroughPut, v))
}

// ThroughPutLTE applies the LTE predicate on the "through_put" field.
func ThroughPutLTE(v int) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLTE(FieldThroughPut, v))
}

// ThroughPutIsNil applies the IsNil predicate on the "through_put" field.
func ThroughPutIsNil() predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIsNull(FieldThroughPut))
}

// ThroughPutNotNil applies the NotNil predicate on the "through_put" field.
func ThroughPutNotNil() predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotNull(FieldThroughPut))
}

// ZoneIDEQ applies the EQ predicate on the "zone_id" field.
func ZoneIDEQ(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldZoneID, v))
}

// ZoneIDNEQ applies the NEQ predicate on the "zone_id" field.
func ZoneIDNEQ(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNEQ(FieldZoneID, v))
}

// ZoneIDIn applies the In predicate on the "zone_id" field.
func ZoneIDIn(vs ...string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIn(FieldZoneID, vs...))
}

// ZoneIDNotIn applies the NotIn predicate on the "zone_id" field.
func ZoneIDNotIn(vs ...string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotIn(FieldZoneID, vs...))
}

// ZoneIDGT applies the GT predicate on the "zone_id" field.
func ZoneIDGT(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGT(FieldZoneID, v))
}

// ZoneIDGTE applies the GTE predicate on the "zone_id" field.
func ZoneIDGTE(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGTE(FieldZoneID, v))
}

// ZoneIDLT applies the LT predicate on the "zone_id" field.
func ZoneIDLT(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLT(FieldZoneID, v))
}

// ZoneIDLTE applies the LTE predicate on the "zone_id" field.
func ZoneIDLTE(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLTE(FieldZoneID, v))
}

// ZoneIDContains applies the Contains predicate on the "zone_id" field.
func ZoneIDContains(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldContains(FieldZoneID, v))
}

// ZoneIDHasPrefix applies the HasPrefix predicate on the "zone_id" field.
func ZoneIDHasPrefix(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldHasPrefix(FieldZoneID, v))
}

// ZoneIDHasSuffix applies the HasSuffix predicate on the "zone_id" field.
func ZoneIDHasSuffix(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldHasSuffix(FieldZoneID, v))
}

// ZoneIDIsNil applies the IsNil predicate on the "zone_id" field.
func ZoneIDIsNil() predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIsNull(FieldZoneID))
}

// ZoneIDNotNil applies the NotNil predicate on the "zone_id" field.
func ZoneIDNotNil() predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotNull(FieldZoneID))
}

// ZoneIDEqualFold applies the EqualFold predicate on the "zone_id" field.
func ZoneIDEqualFold(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEqualFold(FieldZoneID, v))
}

// ZoneIDContainsFold applies the ContainsFold predicate on the "zone_id" field.
func ZoneIDContainsFold(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldContainsFold(FieldZoneID, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldContainsFold(FieldRegion, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.FieldContainsFold(FieldProjectID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BronzeGreenNodeVolumeVolumeType) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BronzeGreenNodeVolumeVolumeType) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BronzeGreenNodeVolumeVolumeType) predicate.BronzeGreenNodeVolumeVolumeType {
	return predicate.BronzeGreenNodeVolumeVolumeType(sql.NotPredicates(p))
}
